### ISSUE TITLE
Host field in swagger not filled correctly

### ISSUE THREAD

**Issue by eternal-flame-AD** [gotify/server#106]
I found that the host field in `/swagger` is always empty, however when I reviewed the source code I found this line:
https://github.com/gotify/server/blob/68b160997d982c7465db6a65b925c94f0aa2e531/docs/swagger.go#L12

I guess that you hoped to interpolate the source host into `desc.json`. However, for server requests, the `URL` field only contained the request URI. I think you would need `ctx.Request.Host` instead.

Ref:

> URL specifies either the URI being requested (for server requests) or the URL to access (for client requests).
https://golang.org/src/net/http/request.go#L115

> For server requests Host specifies the host on which the URL is sought.
https://golang.org/src/net/http/request.go#L218

**Comment by jmattheis** [comment]
Hey @eternal-flame-AD,

good catch! I'll fix that.
