### ISSUE TITLE
Gotify Community Chat

### ISSUE THREAD

**Issue by jmattheis** [gotify/server#126]
Please share your thought on whether the Gotify project needs a community chat or not. 
If yes, what chat platform would you prefer? Discord, Slack, Gitter, Spectrum or IRC?

**Comment by eternal-flame-AD** [comment]
I vote for slack:) A community chat is good for discussing ideas and obtaining feedbacks:)

**Comment by sik0vny** [comment]
Lets use decentralized, open, federated Matrix protocol

An open network for secure, decentralized communication.
https://matrix.org/

**Comment by mwild1** [comment]
Another vote for an open protocol. I feel it would be more in line with the project's spirit and audience. The recent trend of open projects all using different proprietary chats that require me to keep browser tabs open or install memory-hungry closed-source clients is intensely frustrating.

XMPP, Matrix or IRC are all sensible options. Exactly which one doesn't matter too much, as they all have bridges between them.

**Comment by jmattheis** [comment]
Okay, I've created a matrix.org chat room. You can (hopefully) join here 
https://matrix.to/#/#gotify:matrix.org
