### ISSUE TITLE
[helpful] more detailed compile instructions needed

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#131]
I need for and old, but reliable!, server a 32bit linux version. The compileinstructions are to generic for people like me without deep compiling knowledge. ;-)
Please update the instructions and maybe create some usecases like "compiling on debian 9" or "compiling on win 7" or "compiling for rasbian"
I know that this is additional work on the one hand (once), but it would help to create more binaries for different platforms by the users themself.
See also discussion on #99

**Comment by eternal-flame-AD** [comment]
>I need for and old, but reliable!, server a 32bit linux version. The compileinstructions are to generic for people like me without deep compiling knowledge. ;-)

I'm afraid that at least you need to have an idea on these points to carry out a compile:
- how to install [go](https://golang.org/doc/install) or [docker](https://www.docker.com/)
- how to identify your machine architecture (32bit is not a specific architecture, armv6, armv7, x86, etc. are all 32-bit architectures)
- (if you need to compile with sqlite3 support) how to install (cross-)gcc on your machine.

> Please update the instructions and maybe create some usecases like "compiling on debian 9" or "compiling on win 7" or "compiling for rasbian"

Besides these three points as I mentioned above, I think the current documentation is clear enough to give step-by-step instructions. So I assume that you are asking for examples of architectures of specific platforms. @jmattheis what do you think? Should we add this?

---
If you need help compiling or want a binary built for you, you could e-mail me and obtain one.
Don't forget to include these information in your email if you want an artifact as they are necessary for building a working binary:
```
Which commit or branch or tag you want to build at.
Your host OS.
Your host architecture( the result of `uname -a` should be enough)
Whether you need sqlite3 support (and if yes, your GLIBC version, the result of `ldd --version` should be enough).
```

BTW, just a reminder, next time please do not comment on other's threads for personal requests as this would create a notification for everyone involved in that discussion and it would be not very pleasant experience:( You should try to open a new thread or use the community chat for help(still under construction).

**Comment by jmattheis** [comment]
I agree with @eternal-flame-AD. The user only has to install Go and Nodejs/NPM themself, this still requires some knowledge, but can mostly be done through tutorials that already exist.

**Comment by eternal-flame-AD** [comment]
@pm-pm It has been 14 days since the last activity of this issue. Has the issue been resolved, or do you have any further question? Thanks for your feedback.

**Comment by pm-pm** [comment]
From my point we can close this. :-)
You support the 32bit i386
Thanks
