### ISSUE TITLE
Can't get reverse proxy working / Configuration question

### ISSUE THREAD

**Issue by mahescho** [gotify/server#137]
Hi,

I've setup Gotify without Docker with the Apache revers proxy config posted in documentation. The web interface works but web sockets doesn't. The client gets "internal serer error". This is what I see in the Android client log. Mod "proxy_wstunnel" is enabled. When I try to push a message by curl nothing happens at all. The message is not visible in the web UI. How to get this rolling?

What is the "stream: allowedorigins:" option in the config all about?

TIA

**Comment by jmattheis** [comment]
Hi @mahescho,

Could you add your gotify and apache configurations? Does the request that caused an "internal server error" have something inside its response? Is there any log outputted by gotify/server? It should be looking like this:
```
[GIN] 2019/03/03 - 17:28:43 | 200 |     313.201µs |             ::1 | GET      /current/user
[GIN] 2019/03/03 - 17:28:43 | 200 |     230.534µs |             ::1 | GET      /stream?token=CNQybBuBj6fCZ4K
[GIN] 2019/03/03 - 17:28:43 | 200 |     308.409µs |             ::1 | GET      /application
[GIN] 2019/03/03 - 17:28:43 | 200 |     235.532µs |             ::1 | GET      /message?since=0
```

With stream.allowedorigins you can allow third party websites to use the web socket. F.ex gotify/server runs on gotify.example.org and you want to access the web socket via myapp.example.org then you'd had to add myapp.example.org as allowed origin.

**Comment by mahescho** [comment]
Apache Config:
`
<VirtualHost *:443>
        ServerName msg.domain.link

        SSLEngine On

        ProxyPass "/stream" ws://127.0.0.1:8080/ retry=0 timeout=5
        ProxyPass "/" http://127.0.0.1:8080/ retry=0 timeout=5
        ProxyPassReverse / http://127.0.0.1:8080/
        ServerSignature Off
        Keepalive On
        CustomLog /var/log/apache2/push_access.log combined
        ErrorLog /var/log/apache2/push_error.log

	SSLProtocol             all -SSLv2 -SSLv3
	SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305.........
	SSLHonorCipherOrder     on
	SSLCompression          off
	SSLOptions +StrictRequire

        SSLCertificateFile /etc/ssl/msg.domain.link.crt
        SSLCertificateKeyFile /etc/ssl/msg.domain.link.key
</VirtualHost>
`
Apache logs:
`
[03/Mar/2019:16:55:00 +0100] "GET /stream?token=CxH5bKUi07RqYae HTTP/1.1" 502 6417 "-" "okhttp/3.12.0"
`
Gotify logs:

`
Mar  3 16:55:22 m01 gotify-linux-amd64[28515]: [GIN] 2019/03/03 - 16:55:22 | 200 |     235.462µs | 2001:1a50:5105:2:9473:459a:924a:e5ee | GET      /?token=CeGv1-dc7LflK7o
Mar  3 16:55:22 m01 gotify-linux-amd64[28515]: [GIN] 2019/03/03 - 16:55:22 | 200 |     835.027µs | 2001:1a50:5105:2:9473:459a:924a:e5ee | GET      /current/user
Mar  3 16:55:27 m01 gotify-linux-amd64[28515]: [GIN] 2019/03/03 - 16:55:27 | 200 |      176.76µs | 2001:1a50:5105:2:850a:69cd:6c0b:718 | GET      /?token=CxH5bKUi07RqYae
Mar  3 16:55:53 m01 gotify-linux-amd64[28515]: [GIN] 2019/03/03 - 16:55:53 | 200 |     193.751µs | 2001:1a50:5105:2:9473:459a:924a:e5ee | GET      /?token=CeGv1-dc7LflK7o
Mar  3 16:55:53 m01 gotify-linux-amd64[28515]: [GIN] 2019/03/03 - 16:55:53 | 200 |     749.952µs | 2001:1a50:5105:2:9473:459a:924a:e5ee | GET      /current/user
Mar  3 16:55:58 m01 gotify-linux-amd64[28515]: [GIN] 2019/03/03 - 16:55:58 | 200 |     149.284µs | 2001:1a50:5105:2:850a:69cd:6c0b:718 | GET      /?token=CxH5bKUi07RqYae

`

**Comment by jmattheis** [comment]
Looks like the proxying for the stream endpoint doesn't work. This:
```
GET      /?token=CxH5bKUi07RqYae
```
should look like this:
```
GET      /stream?token=CxH5bKUi07RqYae
```

Currently I've no apache server running, will (probably) try it out tomorrow when I find time for it. 

You could try out:
```
ProxyPass "/stream" ws://127.0.0.1:8080/stream retry=0 timeout=5
```
but not sure if it will work.

**Comment by mahescho** [comment]
Getting better. Now at least the web interface works as expected an messages get displayed. But the Android app still does not show any message.

Log when I reload in the Android app:

    ==> /var/log/apache2/push_access.log <==
    [06/Mar/2019:08:31:31 +0100] "GET /current/user HTTP/1.1" 200 4094 "-" "okhttp/3.12.0"
    
    ==> /var/log/syslog <==
    Mar  6 08:31:31 m01 gotify-linux-amd64[25235]: [GIN] 2019/03/06 - 08:31:31 | 200 |     664.102µs | 2001:1a50:5105:2:f84f:84cf:e361:8ef | GET      /current/user
    
    ==> /var/log/apache2/push_access.log <==
    [06/Mar/2019:08:29:51 +0100] "GET /stream?token=C26tKzq_-zPwB2D HTTP/1.1" 200 374 "-" "okhttp/3.12.0"
    [06/Mar/2019:08:31:31 +0100] "GET /version HTTP/1.1" 200 4160 "-" "okhttp/3.12.0"
    
    ==> /var/log/syslog <==
    Mar  6 08:31:31 m01 gotify-linux-amd64[25235]: [GIN] 2019/03/06 - 08:31:31 | 200 |      60.098µs | 2001:1a50:5105:2:f84f:84cf:e361:8ef | GET      /version
    Mar  6 08:31:31 m01 gotify-linux-amd64[25235]: [GIN] 2019/03/06 - 08:31:31 | 200 |     581.767µs | 2001:1a50:5105:2:f84f:84cf:e361:8ef | GET      /stream?token=C26tKzq_-zPwB2D
    
    ==> /var/log/apache2/push_access.log <==
    [06/Mar/2019:08:31:31 +0100] "GET /application HTTP/1.1" 200 4055 "-" "okhttp/3.12.0"
    
    ==> /var/log/syslog <==
    Mar  6 08:31:31 m01 gotify-linux-amd64[25235]: [GIN] 2019/03/06 - 08:31:31 | 200 |     594.785µs | 2001:1a50:5105:2:f84f:84cf:e361:8ef | GET      /application
    Mar  6 08:31:31 m01 gotify-linux-amd64[25235]: [GIN] 2019/03/06 - 08:31:31 | 200 |     557.246µs | 2001:1a50:5105:2:f84f:84cf:e361:8ef | GET      /message?limit=100&since=0
    
    ==> /var/log/apache2/push_access.log <==
    [06/Mar/2019:08:31:31 +0100] "GET /message?limit=100&since=0 HTTP/1.1" 200 4111 "-" "okhttp/3.12.0"
    [06/Mar/2019:08:31:31 +0100] "GET /stream?token=C26tKzq_-zPwB2D HTTP/1.1" 200 3964 "-" "okhttp/3.12.0"

**Comment by jmattheis** [comment]
Is there any log in the Android app? It is the last entry in the navigation drawer.

**Comment by mahescho** [comment]
Plenty after first login, mainly Java stack traces. When I kill the app and restart it a few websocket reconnections get logged. And then no further log entries. I found no way to grab the log to paste it here.

**Comment by pm-pm** [comment]
Hardcopy? ;-)

**Comment by jmattheis** [comment]
Yeah, a screenshot would be good :).

**Comment by mahescho** [comment]
Well ... at login a two page stack traces every 2 seconds ... let's see how I can manage to do screenshots of that. An other idea: put the mobile on a photocopier, then scann the print and post it ...

**Comment by mahescho** [comment]
Next I will try to use an other device but this will take a few days. Perhaps my Moto Z 3 is the problem.

**Comment by jmattheis** [comment]
You could also use adb if you have the android dev tools installed:
```
adb logcat "gotify:I" "*:S"
```
You got mail (:.

**Comment by eternal-flame-AD** [comment]
@mahescho It has been 20 days since the last activity of this issue. Has your problem been resolved?:)
