### ISSUE TITLE
Reverse proxy usage still not working with subpath in url (still static URL in code?)

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#138]
Still the webinterface is not working (white page) in reverse proxy konfiguration when you use a SUBPATH in URL like "https://mydomain.com/gotify"
Looks like "/static/..." and maybe some other pathes have still leading "/"
```
--- apache
ProxyPass        /gotify         http://localhost:86
ProxyPassReverse /gotify         http://localhost:86
```
```
[06/Mar/2019:14:04:05 +0100] "GET /gotify HTTP/1.1" 200 1071 "-"
[06/Mar/2019:14:04:06 +0100] "GET /static/css/main.99a0ea00.css HTTP/1.1" 404 561 "https://mydomain.com/gotify"
[06/Mar/2019:14:04:06 +0100] "GET /static/js/main.93537239.js HTTP/1.1" 404 559 "https://mydomain.com/gotify"
```

**Comment by pm-pm** [comment]
Adding this rewrite statement (as workaround) in apache configuration it is possible to see (open) the webinterface, but it is not possible to login.

```
        RewriteCond %{REQUEST_URI} ^(/static)(.*)$
        RewriteRule ^/(.*)$ http://localhost:86/$1  [P,NS]
```
```
Login still not possible
[06/Mar/2019:14:05:52 +0100] "POST /client HTTP/1.1" 404 692 "https://mydomain.com/gotify"
```

**Comment by jmattheis** [comment]
Are you using the newest gotify version?

**Comment by pm-pm** [comment]
Yes i do.
As a remark: In the last version (1.2.1) i needed about 10 redirects for only accessing the web interface (due to static path), in this version (2.0.1) at least one redirect is necessary to access the web interface. (But in both cases working was not possible)

From my point:
Using gotify in this way as subdomain "https:||**gotify**.mydomain.com" could/should work, but using as subpath "https:||mydomain.com/**gotify**" is not possible. 

Why is this important? When using gotify in a subpath you do not need an addition https certificate for your domain.
(Changed "//" to "||" for formatting reason)

**Comment by jmattheis** [comment]
With the following config it works for me:
```
<VirtualHost *:*>
    ProxyPass /gotify/stream ws://192.168.178.34:8080/stream retry=0 timeout=5
    ProxyPass /gotify/ http://192.168.178.34:8080/
    ProxyPassReverse /gotify/ http://192.168.178.34:8080/

    ServerName localhost
</VirtualHost>
```
full httpd.conf: https://gist.github.com/jmattheis/46028237ff00f6b78415a52ac482208c

I used the httpd docker container with docker compose:
```
version: '3'
services:
    apache:
        image: httpd:2.4
        ports:
            - "12345:80"
        volumes:
            - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
```

**Comment by pm-pm** [comment]
Thanks for verification!
I am checking in detail later. Maybe a trailing "/" in browser address bar causes the confusion.

**Comment by jmattheis** [comment]
Yeah probably. see here https://github.com/gotify/server/pull/127#discussion_r255595404 we should document that behavior.

**Comment by pm-pm** [comment]
Collected information from me:

**1. Version**
apache conf:
```
ProxyPass        /gotify  http://localhost:86 # No trailing "/"
ProxyPassReverse /gotify  http://localhost:86 # No trailing "/"
```
Edge Browser and Firex 65 same result:
```
https://mydomain.com/gotify  # Partly loaded Website (WISH TO WORK)
https://mydomain.com/gotify/ # Working Website - Trailing Slash needed, this is "crude". *Note
```
Without trailing "/" some parts of the website are already loaded, so we are on a good way. ;-)

**2. Version**
apache conf now:
```
ProxyPass        /gotify/  http://localhost:86 # WITH trailing "/"
ProxyPassReverse /gotify/  http://localhost:86 # WITH trailing "/"
```
Edge Browser and Firex 65 same result:
```
https://mydomain.com/gotify  # URL not found
https://mydomain.com/gotify/ # Partly loaded Website
```
More problematic response. No good idea.

To **avoid** an additional rewrite rule and avoid syntax errors in rewrite please check if it is possible to modify the code that no rewrite is necessary and **1. Version** can be used. 

Please note: Before the last update of gotify server there where more problems. **Could it be possible that you have not found all static url´s in code?** ;-)

A code check would be the most elegant way to solve the problem.


*Note: Be shure while testing, that no additial "/" is added to URL from Browser cache!

**Comment by jmattheis** [comment]
When using your config from version 2:
>     ProxyPass        /gotify/  http://localhost:86 # WITH trailing "/"
>     ProxyPassReverse /gotify/  http://localhost:86 # WITH trailing "/"

Then apache outputs errors, this is not the fault of gotify:
```
apache_1  | 172.18.0.1 - - [08/Mar/2019:09:44:59 +0000] "GET /gotify/ HTTP/1.1" 200 619
apache_1  | [Fri Mar 08 09:44:59.477899 2019] [proxy:error] [pid 13:tid 140010162419456] [client 172.18.0.1:39302] AH00898: DNS lookup failure for: 192.168.178.34:8080static returned by /gotify/static/css/main.99a0ea00.css, referer: http://localhost:12345/gotify/
```

> Could it be possible that you have not found all static url´s in code?

No. Like said in https://github.com/gotify/server/pull/127#discussion_r255595404 it is currently only supported with having trailing slashes.

> Your example only works with a trailing "/" in the URL. Is this correct?

Yes.

> To avoid an additional rewrite rule and avoid syntax errors in rewrite please check if it is possible to modify the code that no rewrite is necessary and 1. Version can be used.

You don't need mod rewrite, it could be done with a redirect from `/gotify` to `/gotify/`.
```
<VirtualHost *:*>
    Redirect 301 /gotify /gotify/

    ProxyPass /gotify/stream ws://192.168.178.34:8080/stream retry=0 timeout=5
    ProxyPass /gotify/ http://192.168.178.34:8080/
    ProxyPassReverse /gotify/ http://192.168.178.34:8080/

    ServerName localhost
</VirtualHost>
```

@eternal-flame-AD What do you think, should we add support the 1. Version in https://github.com/gotify/server/issues/138#issuecomment-470665635?

**Comment by eternal-flame-AD** [comment]
Did I get this right? So if we need to support URLs without the trailing slash, we need to do the following step to obtain the base path:
1. Check if the URL ends with index.html, if yes, remove it.
1. Check if the URL ends with a trailing slash. If no, add it.

To be frank, I am still in favor of a redirect on the reverse proxy side, as it is more in accordance with the standards of URLs.

**Comment by jmattheis** [comment]
Yeah, right. 
I guess it is not that easy to accomplish too. The UI imports js and css files via `./static/*`, we'd have to dynamically load these files depending if a trailing slash is present. 

Having a redirect on the reverse proxy seems like the best option.

**Comment by eternal-flame-AD** [comment]
I agree. I am not very familiar with Apache, but it seems that a lot of people are using that and encountering problems. Maybe we need to write a working configuration and post it on the documentation.

**Comment by pm-pm** [comment]
Hello. [small] I don´t like the idea. [/small] ;-)
Please keep reverse proxy configuration in 3rd party products (like apache) as simple as possible. Especially "mod_rewrite" can cause many problems/questions to users.

Please have in mind that you might have many reverser configuration in one apache server config. Adding rewrite statements can cause trouble to other services.
```
mydomain.com/gotify
mydomain.com/special-login
mydomain.com/data-on-appliance

```
BTW: I do not understand the "index.html" problem. If you enter the URL " https://mydomain.com/gotify "
some data from gotify server is already loaded by the browser, so you do not need to check for "index.html"?!

Sorry for my bad english, but sometimes it is difficult to explain a problem or idea. I am sure there will be a solution. :-) Maybe your solution is ok, but in the moment i am not convinced. ;-)

You already managed to load all the other files within proxy configuration. Please have a try to solve this problem, too.

**Comment by eternal-flame-AD** [comment]
Firstly, there would be five possible URL to base URL combinations if we support URLs without trailing slashes. I can't think of a better way to support all these five URL patterns than the one I mentioned above.
- `//mydomain.com/` -> `//mydomain.com/`
- `//mydomain.com/index.html` -> `//mydomain.com/`
- `//mydomain.com/some/path` -> `//mydomain.com/some/path/`
- `//mydomain.com/some/path/` -> `//mydomain.com/some/path/`
- `//mydomain.com/some/path/index.html` -> `//mydomain.com/some/path/`

Secondly, as is the convention of HTTP file servers, a trailing slash denotes that the path is a directory and the index file should be returned. However, if we do not end the URI with a trailing slash, it denotes the resource located at that point, and should not silently return `index.html` in that directory. As far as I know, nginx and caddy either returns 404 or a redirect by default if you did not end a directory path with a slash.

**Comment by eternal-flame-AD** [comment]
Still, my apologies for not providing a working apache configuration on the documentation upgrade. I have to admit that I know basically nothing in how to configure apache so I did not sort this out. @jmattheis what about adding the final configuration to the documentation after this issue is resolved?

**Comment by jmattheis** [comment]
Yeah. I've opened https://github.com/gotify/website/pull/7 @pm-pm could you have a look at it and verify that this is working for you?

**Comment by pm-pm** [comment]
Yes ist working fine. :-)
Comment left on the other page.
Thanks!
