### ISSUE TITLE
gotify logo licensing

### ISSUE THREAD

**Issue by eternal-flame-AD** [gotify/server#141]
I did not find the licensing information for the gotify logo.

Say I want to make a electron/native app for gotify, am I allowed to use the gotify logo, and to what extent, how should I provide attribution information?

**Comment by jmattheis** [comment]
Good question, I'm thinking of using the "CC by attribution" license https://creativecommons.org/licenses/by/4.0/ 
what do you think?

**Comment by eternal-flame-AD** [comment]
That's awesome:)

This is a relatively free and permissive license, which permits others to directly use the gotify logo as their project logo as long as they provide attribution to you. If you don't like this behavior, you can add an additional requirement here.

**Comment by jmattheis** [comment]
The CC faq states that it shouldn't be used for logos
> Could I use a CC license to share my logo or trademark?
> 
> Creative Commons does not recommend using a CC license on a logo or trademark. While a logo or trademark can be covered by copyright laws in addition to trademark laws, the special purposes of trademarks make CC licenses an unsuitable mechanism for sharing them in most cases. Generally, logos and trademarks are used to identify the origin of a product or service, or to indicate that it meets a specific standard or quality. Allowing anyone to reuse or modify your logo or trademark as a matter of copyright could result in your inability to limit use of your logo or trademark selectively to accomplish those purposes. Applying a CC license to your trademarks and logos could even result in a loss of your trademark rights altogether.

https://creativecommons.org/faq/

But I still think this is the right license.

**Comment by eternal-flame-AD** [comment]
Okay, it's just a reminder:)

If you don't bother other's potentially using this as their project logos, I would say that this license is suitable.

**Comment by jmattheis** [comment]
See https://github.com/gotify/logo
