### ISSUE TITLE
Errormessage on server "404 /favicon.ico" but everything looks fine.

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#142]
On the online Server log there is always:

`[GIN] 2019/03/08 - 19:54:48 | 404 |      94.415µs |   195.111.111.111 | GET      /favicon.ico`

From my point the favicon is visible on the tab of the browser. Everything Looks good.
What does this error message mean? Can i (re-)place an own favicon anywhere?

**Comment by jmattheis** [comment]
In gotify/server there is no reference to `/favicon.ico`. My guess is that your browser is trying to get a favicon without having the index.html loaded.
```
$ git grep favicon.ico
ui/public/index.html:    <link rel="icon" href="static/favicon.ico">
```

**Comment by pm-pm** [comment]
Yes the favicon is loaded and visible on browser tab.
Just the errormessage is irritating.

**Comment by jmattheis** [comment]
Yeah, but the error isn't gotify's fault so I'll close this issue.

**Comment by pm-pm** [comment]
For information:
Using gotify server 2.0.3
```
Direkt access of gotify server:
Firefox---->mydomain.com:8080 no favicon error - gotify icon on browser tab
W10Edge---->mydomain.com:8080    favicon ERROR - gotify icon on browser tab*

With Apache ReverseProxy:
Firefox---->mydomain.com/gotify no favicon error - gotify icon on browser tab
W10Edge---->mydomain.com/gotify no favicon error - webserver /favicon on browser tab
```

* This is annoying to see so many error messages, but only in this combination.

![fii](https://user-images.githubusercontent.com/47995430/54478266-7f10e100-4810-11e9-8190-38a7fbaba462.png)
