### ISSUE TITLE
32 bit linux binary?

### ISSUE THREAD

**Issue by canDry** [gotify/server#143]
Was hoping to install this on an old 32bit home automation server running debian.

**Comment by eternal-flame-AD** [comment]
32bit is not an architecture. We do have arm-7 official builds, which is a 32-bit architecture. See [this](https://github.com/gotify/server/issues/131#issuecomment-467465742) or google "linux find architecture" to know how to find the architecture of your server.

You can also e-mail me for a built artifact as is described in that comment.

**Comment by canDry** [comment]
Sorry for not being clear... I meant for “i386” architecture.

**Comment by eternal-flame-AD** [comment]
@jmattheis do you think we should add this as a target for official build?

Still, you could compile your gotify for your platform yourself through the documentation [here](https://gotify.net/docs/build) you will need `GOOS=linux GOARCH=386` as the target.

**Comment by canDry** [comment]
Bah... so I tried cross compiling on a virt machine... default/available versions of go and node were behind the requirements.. so had to get newer versions.  Got as far as the ui build and npm just dies with many errors.

**Comment by eternal-flame-AD** [comment]
You can use the [gotify/build](https://github.com/gotify/build) docker image.

**Comment by eternal-flame-AD** [comment]
Here I can provide you with a built artifact:)
```bash
file gotify-server 
gotify-server: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, Go BuildID=BEfonVP0Xs9i_9u_RZGC/9AZ-HxJUtesGGRmX4Miv/4TqxWis8PV1RtPgmUpPC/4x-pbrIBi6xIFMhl8HZz, BuildID[sha1]=f4be466ff7f498f1977a20aa1e466a3f9fe5f485, stripped
```

[gotify-server.gz](https://github.com/gotify/server/files/2949111/gotify-server.gz)

**Comment by jmattheis** [comment]
Yeah, we should add a build target for i386

**Comment by canDry** [comment]
You're a saint.  :)
Unfort it wants IPv6 and being and older system/router it only supports IPv4.  LOL!!  
I really do appreciate your effort though.

**Comment by eternal-flame-AD** [comment]
You need a [configuration](https://github.com/gotify/server/blob/master/config.example.yml) file to tune server behavior(such as listening address, port, etc.)

Download the file as `config.yml` to your server directory and modify `listenaddr` and `port`.

**Comment by jmattheis** [comment]
linux i386 is now included into our build pipeline. You can download the binary here:
https://github.com/gotify/server/releases

**Comment by pm-pm** [comment]
Thanks also from my side! :-)

**Comment by canDry** [comment]
Thanks for the awesomely quick response!
