### ISSUE TITLE
Some characters do not work (password)

### ISSUE THREAD

**Issue by oxodao** [gotify/server#145]
Hi,

Using a password manager which generated this password: "3F7ßx[Zy[0ô_<5/MÃd&l"
I couldn't login after I've set it (both on the web ui and the android app)
Fortunately I was still logged in so I changed it back to something with less weird characters and I could log back in again.

If you just don't want to bother supporting those kind of characters, maybe you should tell the user when the password doesn't meet the correct charset

**Comment by eternal-flame-AD** [comment]
Thanks for the issue:) I am able to reproduce the problem and is investigating on it.
