### ISSUE TITLE
2.0.2 Docker : Websocket: request origin not allowed by Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by SuperKingZ** [gotify/server#149]
After starting a clean 2.0.2 docker 8030:80 container I get this error in the terminal when I login.  I didn't experience this error in 1.2.0

```
 Websocket: request origin not allowed by Upgrader.CheckOrigin
```

**Comment by eternal-flame-AD** [comment]
I ran over the history and found https://github.com/gotify/server/commit/b5b2f19dc2ed19165615719d49b9ad8919537476 to be related to the issue. Seems that it is comparing a host with a port number with a host without a port number. I will send a PR for a fix. Thanks.

**Comment by pm-pm** [comment]
This is not only a docker issue. v2.0.2 accessing with FF 63

```
[GIN] 2019/03/10 - 19:31:51 | 403 |     807.832µs |  178.111.111.111 | GET      /stream?token=C_aewZynao3lltX
Error #01: websocket: request origin not allowed by Upgrader.CheckOrigin
[GIN] 2019/03/10 - 19:31:51 | 200 |    1.005693ms |  178.111.111.111 | GET      /current/users
```
Token ist the token of the webbrowser. When Firefox is logged out there is no error
The android client does not raise such an error.

**Comment by eternal-flame-AD** [comment]
Yes, it is a bug in the code for verifying connection origin of websocket connections. So it would affect all browser use cases.

**Comment by pm-pm** [comment]
Error still exist wit 2.0.3. 
I am using a advised apache reverse proxy setup. 
```
[GIN] 2019/03/16 - 15:22:20 | 403 |     281.446µs |   195.111.11.11 | GET      /stream?token=Cl_jWMYrm7DJwxl
Error #01: websocket: request origin not allowed by Upgrader.CheckOrigin
[GIN] 2019/03/16 - 15:22:20 | 200 |     299.882µs |   195.111.11.11 | GET      /current/user
```

**Comment by jmattheis** [comment]
`ProxyPreserveHost On` should fix the problem

**Comment by pm-pm** [comment]
Yes, please have a look here for information:
https://github.com/gotify/server/issues/154#issuecomment-473552571
