### ISSUE TITLE
Problem with Edge browser and reverse proxy configuration

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#154]
I have a strange problem.

I can "not" login with Edge (W10) and proxy configuration. I will be logged out after less than a second.

```
On the same W10 machine i tested this:

Firefox 65 accessing mydomain.com:8080 ok *1
Firefox 65 accessing mydomain.com/gotify ok *2

Edge (W10) accessing mydomain.com:8080 ok *1
Edge (W10) accessing mydomain.com/gotify NOT ok *2
```

For a very short moment you can see a login and than you are back in the login screen.

*1 No proxy at all
*2 Apache Reverseproxy configuration as advised.
```
[GIN] 2019/03/11 - 14:32:10 | 200 |  165.006785ms |   195.111.111.111 | POST     /client
[GIN] 2019/03/11 - 14:32:10 | 200 |     784.661µs |   195.111.111.111 | GET      /current/user
[GIN] 2019/03/11 - 14:32:10 | 403 |     536.698µs |   195.111.111.111 | GET      /stream?token=CAXhS2a_6Njwnqt
Error #01: websocket: request origin not allowed by Upgrader.CheckOrigin
[GIN] 2019/03/11 - 14:32:10 | 200 |    1.225617ms |   195.111.111.111 | GET      /message?since=0
[GIN] 2019/03/11 - 14:32:10 | 404 |      89.282µs |               ::1 | GET      /gotify/current/user
[GIN] 2019/03/11 - 14:32:10 | 200 |    2.978808ms |   195.111.111.111 | GET      /application
[GIN] 2019/03/11 - 14:32:10 | 404 |      53.934µs |               ::1 | GET      /gotify/client
```
![ge](https://user-images.githubusercontent.com/47995430/54128093-92d0d780-440b-11e9-83ef-4479b53ad2a1.png)

Any ideas?

**Comment by eternal-flame-AD** [comment]
When you say edge browser, did you mean that the problem only happens on Edge or you only tested on Edge?

**Comment by eternal-flame-AD** [comment]
The fix for check origin problem is pending in #150. Current workaround is to explicitly allow your gotify hostname in the websocket allowedorigin configuration.

**Comment by pm-pm** [comment]
The "CheckOrigin" problem is not the issue here. I just left the line it in for completeness. Or is this the key point?? In all other cases i have no problem to access the gotify server.

I tested all 4 cases on the same W10 computer. See above. With Firefox 65 no problem to access non-proxy and proxy gotify server. With Edge browser only access to non-proxy gotify server was successful.

Could you please crosscheck to access a (apache) proxyed gotify server with Edge browser?

See red circle:
Have a look at the "::1" localhost entry? There should be not such a entry. Also the shown path is wrong.

Should i wait for the gotify server update where the "CheckOrigin" bug is fixed? But why can i access all other combinations?

**Comment by eternal-flame-AD** [comment]
Yeah I don't think this is related to the websocket problem then.

The reason of "::1" requests are a little ambigous and I cannot guess where it could came from. Can you collect some info from the edge [network](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/network) data, which might provide some insights to the issue on which request failed led to the client to logout? Thanks.

**Comment by pm-pm** [comment]
I have "recorded" the networktraffic with dev tools for login. how can you transfer that trustingly? ;-)

**Comment by eternal-flame-AD** [comment]
Thanks for the follow-up:) You can send me an e-mail. The email address is ef@eternalflame.info, as indicated in my account. You can also optionally PGP encrypt your email using the key in [this](https://keybase.io/eternal_flame) keybase account.

**Comment by pm-pm** [comment]
Done. :-)

**Comment by eternal-flame-AD** [comment]
You've got mail:)

**Comment by pm-pm** [comment]
Problem still exists. Windows 10 Edge Browser with Apache reverse proxy setup is the problem. The other combinations work. See above. Any proxys in between don´t matter.

**Comment by eternal-flame-AD** [comment]
Have you got my e-mail reply in which I thought there might be a problem in your windows proxy configuration and tried to connect directly first?

**Comment by pm-pm** [comment]
Yes. :-) I have answered you already.

**Comment by eternal-flame-AD** [comment]
Sorry to bother but I just want to make sure that we are not discussing on the same problem. Yesterday, when you collected the HAR file, I suspect your Edge browser has HTTP proxy(the browser front proxy, which could be configured in the windows internet options, not the Apache reverse proxy) enabled because the HAR file you sent me includes a lot of CONNECTs.  I sent you an e-mail suggesting you verify that you are using the same set of proxy configuration on Firefox and Edge, because Firefox has its own proxy configurations, but you still have not provided a clear yes/no answer on (I) do you really have a forward proxy configured (II) does connecting directly(without the forward proxy) solves the issue.

**Comment by pm-pm** [comment]
You don´t bother me. It is maybe a misunderstanding on my side. Sorry.
Yes. First har File include the way via a proxy server. Second har file is **without** forward proxy.

From my point the forward proxy was/is NOT the problem. To be sure i did the test without the forward proxy and recorded the second har file. The problem still exists.

```
(1. har File) LoginProblem
Win10+Edge+ProxyConfiguration-->Proxy-->Internet-->Apache+ReverseProxy-->GotifyServer


Now same computer, Windows/Edge Proxy config deleted! and used at home with direct internet connection.(no proxy in line)
(2. har File) LoginProblem
Win10+Edge----------------------------->Internet-->Apache+ReverseProxy-->GotifyServer
```

This still works:
```
For information: This two configuration work:
Win10+Edge+ProxyConfiguration-->Proxy-->Internet------------------------>GotifyServer:8080
Win10+Edge----------------------------->Internet------------------------>GotifyServer:8080
```

Is this helpful?

**Comment by eternal-flame-AD** [comment]
Sorry, then I have to apologize that I just inspected the first HAR file, I did not see there is a second one. 
Would you please send me the other one without forward proxy again, cuz that would be more helpful as communication with the forward proxy does not get mangled with real communication to gotify?

**Comment by pm-pm** [comment]
I have send you the second har file again. it was recorded without any proxy, but the problem is still the same.

**Comment by eternal-flame-AD** [comment]
Sorry but I did not get your e-mail:( Did you type the e-mail address right? If yes, last time your e-mail went into the spam box directly, though I did not see your e-mail in my quarantine list also, maybe you need to check your e-mail domain on DNSBL, etc.

**Comment by pm-pm** [comment]
"If you have trouble, the next trouble is not far away" :-(

it looks like my mail provider has had problems since yesterday. let's wait a few hours. i've already sent them 2 times and at the moment he's not available. Please excuse this.

**Comment by eternal-flame-AD** [comment]
If you know PGP you can also post the file encrypted with PGP to me here:) My [key](https://keybase.io/eternal_flame). Or you can also find me in the community chat:)

**Comment by pm-pm** [comment]
It llok like the the provider works stable again. I re-send the information. Could you please check this.
Thanks.

**Comment by eternal-flame-AD** [comment]
I still can't get your email. Can you not use a burner email provider, send the har file here directly after masking your token and hostname, or drop a PGP encrypted HAR file here?

**Comment by pm-pm** [comment]
ok. :-/
Accessinformation is the same as first time.
[g2a.zip](https://github.com/gotify/server/files/2963038/g2a.zip)

Thanks for feedback. I keep attention on the mail problem. Others receive mails without problems, but maybe some black/grey/dust listings cause the problem.

**Comment by eternal-flame-AD** [comment]
Okay, I inspected the HAR file and will post a short summary of all my findings here:
- The websocket allow origin problem is hit, you can try to refer to the configuration file in your documentation to see how to explicitly add your hostname to the allowed origins, I know this should not be directly related to the problem you are talking about, but it does no harm to verify that:)
-  The most interesting part is that it seems that after the failed websocket connection attempt, some APIs begin to return 404 to a perfectly normal request. Two requests to `/current/user` just less than 0.5s apart and two requests to `/client` only 1s apart returned 200 for the first time, and 404 for the second time(the 404 response is from gotify itself, not apache). I noticed that you mentioned that some requests arrived at your gotify server without the `/gotify/` URL prefix stripped off. It is the 404 response that eventually caused you to be logged out.

I still have limited information from my side, since you saw IPv6 requested mixed with IPV4 requests, and problems only occur in IPV6 requests, maybe it was because your Apache was not configured correctly to handle IPV6 requests. To verify this I want to rule out websocket and authentication factors. Can you do this several times in a row and try if it ever fails with a not found response and shows request origin from `::1` on the server side?
```bash
curl  https://example.com/gotify/version
```

**Comment by pm-pm** [comment]
Yes i think your analysis is correct. The conclusion is not correct, because i have not configured a IPv6 DNS entry for my domain. The curl result confirm that.
For testing i used the same Windows 10 Comupter. I downloaded a curl version from here: https://curl.haxx.se/windows/

Here ist the result: Domain names and source (PC) IP replaced.
```
C:\curl>curl  https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv4 https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv6 https://example.com/gotify/version
curl: (6) Could not resolve host: example.com

C:\curl>curl  https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv4 https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv6 https://example.com/gotify/version
curl: (6) Could not resolve host: example.com

C:\curl>curl  https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv4 https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv6 https://example.com/gotify/version
curl: (6) Could not resolve host: example.com

C:\curl>curl  https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv4 https://example.com/gotify/version
{"version":"2.0.2","commit":"6e92bcd8e5f4e09a5f01a1d3dbf8d6c4765d5658","buildDate":"2019-03-10-10:10:51"}
C:\curl>curl --ipv6 https://example.com/gotify/version
curl: (6) Could not resolve host: example.com


[GIN] 2019/03/14 - 02:53:38 | 200 |      58.402µs |  178.111.11.111 | GET      /version
[GIN] 2019/03/14 - 02:53:38 | 200 |      43.922µs |  178.111.11.111 | GET      /version

[GIN] 2019/03/14 - 02:53:42 | 200 |     223.087µs |  178.111.11.111 | GET      /version
[GIN] 2019/03/14 - 02:53:43 | 200 |      46.887µs |  178.111.11.111 | GET      /version

[GIN] 2019/03/14 - 02:53:47 | 200 |      58.755µs |  178.111.11.111 | GET      /version
[GIN] 2019/03/14 - 02:53:47 | 200 |      45.997µs |  178.111.11.111 | GET      /version

[GIN] 2019/03/14 - 02:53:50 | 200 |       37.65µs |  178.111.11.111 | GET      /version
[GIN] 2019/03/14 - 02:53:50 | 200 |      45.428µs |  178.111.11.111 | GET      /version


example.com - 178.111.11.111 - - [14/Mar/2019:02:53:38 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"
example.com - 178.111.11.111 - - [14/Mar/2019:02:53:38 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"

example.com - 178.111.11.111 - - [14/Mar/2019:02:53:42 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"
example.com - 178.111.11.111 - - [14/Mar/2019:02:53:43 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"

example.com - 178.111.11.111 - - [14/Mar/2019:02:53:47 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"
example.com - 178.111.11.111 - - [14/Mar/2019:02:53:47 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"

example.com - 178.111.11.111 - - [14/Mar/2019:02:53:50 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"
example.com - 178.111.11.111 - - [14/Mar/2019:02:53:50 +0100] "GET /gotify/version HTTP/1.1" 200 3469 "-" "curl/7.64.0"
```

**Comment by eternal-flame-AD** [comment]
Can you post your complete apache configuration? Let's see if I can reproduce your problem.

**Comment by pm-pm** [comment]
Let me say my idea, i can not prove it, but these are my thoughts:
Is it possible that only these two "pathes" have a "special" character or a double "//" in the source code that confuses Edge and not Firefox?
```
[GIN] 2019/03/12 - 01:52:20 | 404 |      50.923µs |             ::1 | GET      /gotify/current/user
[GIN] 2019/03/12 - 01:52:20 | 404 |      59.259µs |             ::1 | GET      /gotify/client
```

**Comment by pm-pm** [comment]
Apache Config will follow.

**Comment by eternal-flame-AD** [comment]
The HAR file should be the most accurate and actual dump of all the requests that have ever come out of the browser. If some relative paths are not resolved correctly, we should see paths such as `/gotify/gotify/client` in the HAR file, but to me it seems perfectly normal.

**Comment by pm-pm** [comment]
From my side nothing special.
The only thing i see is "RewriteEngine On". Some old from testing. Could be removed. Is that the problem? There is no RewriteRule in my config!
The main apache config file should be default
```
<VirtualHost *:443>
        ServerName example.com
        ServerAdmin webmaster@localhost

#SSL
         SSLEngine on
         SSLCertificateFile      /etc/.../fullchain.pem
         SSLCertificateKeyFile   /etc/.../privkey.pem

        DocumentRoot /var/www/example.com_webserver
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/example.com_webserver/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Require all granted
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Require all granted
        </Directory>

ProxyRequests On
ProxyVia On

        ProxyPass        /othertool1     http://localhost:661/

        ProxyPass        /othertool2 ws://127.0.0.1:662/othertool2 retry=3
        ProxyPassReverse /othertool2 ws://127.0.0.1:662/othertool2 retry=3

# -GOTIFY -
        Redirect   301  "/gotify"         "/gotify/"
        ProxyPass        /gotify/stream   ws://localhost:8080/stream retry=0 timeout=5
        ProxyPass        /gotify/         http://localhost:8080/     retry=0 timeout=5
        ProxyPassReverse /gotify/         http://localhost:8080/

        RewriteEngine On

       ErrorLog /var/log/apache2/error.log
       LogLevel warn
       CustomLog /var/log/apache2/access.log combined
</VirtualHost>
```

**Comment by pm-pm** [comment]
I apologize for the inconvenience, i hope it is a real bug, but I can't find a problem on my site. :-(
I will come back later, but i need a break. ;-)

**Comment by pm-pm** [comment]
Please note: The machine itself has a lokal IPv6 interface/address. It this helpful/important?

```
ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 111.11.11.111  netmask 255.255.254.0  broadcast 111.11.11.255
        inet6 fe80::abab:12ff:fe12:abab  prefixlen 64  scopeid 0x20<link>
        ether 6a:ce:94:da:65:17  txqueuelen 1000  (Ethernet)
        RX packets 777609312  bytes 53696266074 (50.0 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 38151660  bytes 23903170799 (22.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by eternal-flame-AD** [comment]
> Please note: The machine itself has a local IPv6 interface/address. It this helpful/important?
I think if your reverse proxy is not running on the same server as your browser is running on, that's not very important:(

Okay, I am also having difficulties getting my apache running:( Sorry I don't have any previous experience dealing with apache.

@jmattheis Can you try if you can reproduce this? Otherwise, I suggest we wait a few days and, if no one else encountered the same error, we can only conclude that every effort is taken to understand this issue but we really don't have a clue.

**Comment by jmattheis** [comment]
I tried to reproduce it on a windows vm but it does work as expected for me. I only tested it with http.

**Comment by pm-pm** [comment]
Problem still exist with version 2.0.3.
Tested also on a second server, but with same Win10 Client/Edge Computer. (I only have one W10 Computer.)
A forward proxy is non configured. Firefox Browser "only" has "CheckOrigin" problem.
```
[GIN] 2019/03/16 - 15:24:50 | 403 |     258.657µs |   195.111.11.11 | GET      /stream?token=CGT5Q7-Ndh8p1_3
Error #01: websocket: request origin not allowed by Upgrader.CheckOrigin
[GIN] 2019/03/16 - 15:24:50 | 200 |      531.12µs |   195.111.11.11 | GET      /message?since=0
[GIN] 2019/03/16 - 15:24:50 | 404 |      22.129µs |       127.0.0.1 | GET      /gotify/current/user
[GIN] 2019/03/16 - 15:24:50 | 404 |       15.91µs |       127.0.0.1 | GET      /gotify/client
```

**Comment by jmattheis** [comment]
@pm-pm could you try to add `ProxyPreserveHost On` to your configuration.

**Comment by pm-pm** [comment]
Yes. This did the trick.
What did i do wrong? What is wrong in setup?
I never needed this command to make my tools/config run.
Is this the solution or a workaround?

At the moment all other tools in my configuration seem to be still running. 👍 

`ProxyPreserveHost On`
https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost
> When enabled, this option will pass the Host: line from the incoming request to the proxied host, instead of the hostname specified in the ProxyPass line.
> 
> **This option should normally be turned Off**. It is mostly useful in special configurations like proxied mass name-based virtual hosting, where the original Host header needs to be evaluated by the backend server.

**Comment by pm-pm** [comment]
Could this please added to documentation. Thanks.

**Comment by jmattheis** [comment]
Yeah gotify/server explicitly validates the origin against the host for WebSocket requests, therefore the second part of the docu applies:
> where the original Host header needs to be evaluated by the backend server.

So this is the solution.
