### ISSUE TITLE
What is the sense behind the text on the first screen?

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#156]
The link binhind "All messages" is not valid before login and the Text "Some Server \ A Raspberry PI" i do not understand.
Maybe no text or a link to github would be better?

![firstscreen](https://user-images.githubusercontent.com/47995430/54167036-37810280-4468-11e9-96e7-f07396fe0194.png)

**Comment by eternal-flame-AD** [comment]
It's a placeholder for applications when you have not logged in.
