### ISSUE TITLE
Link to the main page

### ISSUE THREAD

**Issue by joy4eg** [gotify/server#159]
Hey there, thanks for the great app!

From my point of view, clicking on `gotify` should redirect to the main page `/`, and not to github.
(Yes, I saw `all messages`, but from UX side it's a bit confusing)
We can add a separate button to the header/footer like `about` which will do the same thing :)

![image](https://user-images.githubusercontent.com/878385/54201332-08a17580-44d6-11e9-8f39-873a9e83fe41.png)

**Comment by jmattheis** [comment]
I don't know, I currently see no problem here. @eternal-flame-AD what do you think?

**Comment by eternal-flame-AD** [comment]
I think this can be improved, as I also sometimes make this mistake, but not a priority though. I would say let's keep it and see if anyone can submit a PR for this.
