### ISSUE TITLE
Use cryptographic random source for token generation

### ISSUE THREAD

**Issue by eternal-flame-AD** [gotify/server#160]
[math/rand#Seed](https://godoc.org/math/rand#Seed), as is indicated on godoc, only provides at most 31 bit of randomness, which is really not a good choice for generating tokens.

I also want to propose newly generated tokens to be longer, now it has about 78 bits, which is not ideally secure from my point of view.

**Comment by pm-pm** [comment]
Is is necessary for this kind of tool? Normally agree, but here i think it is sufficient.

**Comment by eternal-flame-AD** [comment]
It has only around 2e+9 possible states, so it is relatively cheap to enumerate basically every possible state.

I wrote a simple benchmark to simulate enumerating every possible state and generating the first 20 tokens, it is really incredibly fast.
```golang
import (
	"math/rand"
	"testing"
)

func BenchmarkMockGenerateToken(b *testing.B) {
	length := 13
	charsCount := 65
	for i := 0; i < b.N; i++ {
		for tokenNum := 0; tokenNum <= 20; tokenNum++ {
			token := make([]byte, length)
			for index := range token {
				token[index] = byte(rand.Intn(charsCount))
			}
		}
	}
}
```
```
goos: linux
goarch: amd64
pkg: play
BenchmarkMockGenerateToken-8   	  200000	      8878 ns/op	     336 B/op	      21 allocs/op
PASS
ok  	play	1.872s
Success: Benchmarks passed.
```

It only took 8878ns per state on my i7-6700HQ processor, which is not a very modern and performant one, I did some simple math and it told me I can finish enumerating every possible state in less than 20000 seconds, which is less than a whole day.

**Comment by eternal-flame-AD** [comment]
Just verified that the generated token can really be predicted. The number of states is a little too large for a random attack over the Internet. However, the potential issue is if I could obtain a token with only application/user privilege, I would be able to reversely calculate all tokens generated by the server on the same run which might include tokens with admin privileges.

**Comment by furyfire** [comment]
What about limiting the range of characters in the process? 
I do not like the use of anything besides [a-zA-Z0-9] since it makes it hard to separate GET parameters in the URL. 
Maybe use md5 or sha hashing?

**Comment by eternal-flame-AD** [comment]
I am not very bothered by this though. It is easy to change the character set but I don't really see the need for that:(

If you really wanted that please create a new issue and we would wait for other user's opinions on whether to make the change:)
