### ISSUE TITLE
Add refresh button in WebUI message list

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#171]
If you delete a message on/via phone it does not disappear on the ui automatically.

First this, works well:
```
1. Open web ui
2. Send message via CLI
3. Message is pushed to mobile phone and instantly visible in web ui. Works as aspected.
```

Now the non working part:
```
1. Leave web ui open!
2. Delete message on/via phone
3. Message deleted on phone, but NOT disappear in the web ui.
```
If you click in web ui between different "APPS" or switch "CLIENTS <-> APPS" in menu the already deleted message is still visible in web ui.
You only can "clear" (make disappear) the message from the web ui if you use the browser reload button or logout and login.

Is it possible to make the message disappear automatically on web ui if deleted on/via phone?

**Comment by eternal-flame-AD** [comment]
Yes, currently WebSocket only notifies clients of new messages, but not message deletion, read/unread( #21 related), etc. But the current WebSocket message scheme does not include event types, thus it would break the API to fix the problem.

**Comment by pm-pm** [comment]
Ok, i understand that is a bigger thing.
I do NOT need this funktion very often, more for testing, so i can do without this function.

Two ideas for a workaround (I prefer the second one):
- Reload the messages when you click/switch on the left side from one App to an other App
or
- Add a reload button on top. See picture.

![rms](https://user-images.githubusercontent.com/47995430/54506101-24c06f00-493b-11e9-8125-59e1fd362958.png)

Using the browser reload button is not so good.

**Comment by eternal-flame-AD** [comment]
I would say let's add a refresh button in the messages list. What do you think? @jmattheis

**Comment by jmattheis** [comment]
A refresh button is okay.

**Comment by foxbit19** [comment]
Hi, what about this issue?
I had a look at the code. I suggest to do some refactor tasks on `DefaultPage` component to support more than one button at the top fo the page.

What do you think?

**Comment by jmattheis** [comment]
Yeah seems good, the default page could accept a react node then it would be more customizable
```
<DefaultPage title="" maxWidth={250} rightControl={<Button onClick={...}>Cool button</Button>}>
```
Another option would be a [Fab](https://material-ui.com/components/buttons/#floating-action-buttons) button, sadly we already have one which scrolls to the top.

**Comment by foxbit19** [comment]
`DefaultPage` + react node seems good! I would discard `Fab` button for now.

**Comment by pm-pm** [comment]
Top! :-) Great work.

Thanks.

**Comment by blabasodfiu** [comment]
> Yes, currently WebSocket only notifies clients of new messages, but not message deletion, read/unread( #21 related), etc. But the current WebSocket message scheme does not include event types, thus it would break the API to fix the problem.

Will this ever be implemented?

**Comment by blabasodfiu** [comment]
@eternal-flame-AD Without a proper scheme any future event that may be necessary cannot be implemented. Think for example about the Web UI, which could automatically hide an application that has been deleted by another client. I would like to use Gotify and support this project, but without a more flexible WebSocket scheme any client will be full of notifications if not used regularly.

**Comment by jmattheis** [comment]
Hey @blabasodfiu,

while breaking the api sucks, it still should be done if it improves the UX of Gotify. In this case, I think it would be enough to add a `type`-property to messages send over the web socket. This could be done without breaking the api by directly subscribing to event types and having only the `message` type as default.

Currently, I do not plan on implementing it but I'd be accepting pull requests.
