### ISSUE TITLE
Single device registered multiple times

### ISSUE THREAD

**Issue by doekia** [gotify/server#177]
Everytime we login to the serveur, a similar device with different token key is created.
I log 10x  it create 10 devices.

**Comment by eternal-flame-AD** [comment]
When you log out manually, the token stored in the browser local storage is deleted, so there is nothing we can do except to create a new token when you tried to log in again. You can safely delete the obsolete token.

However, I think we can support logging-in with an existing token, both on Android and WebUI, what do you think? @jmattheis

**Comment by jmattheis** [comment]
We could support this, however on logout the device will be removed, so if you logout there shouldn't be 10 devices for a single device.

**Comment by eternal-flame-AD** [comment]
> however on logout the device will be removed, so if you logout there shouldn't be 10 devices for a single device.

@jmattheis Did you mean this is already implemented? I don't think we have this feature now.

**Comment by jmattheis** [comment]
Yeah, dunno if it is not working but we have it:
https://github.com/gotify/server/blob/c89623abd0e729e97dfe4f2cb5ad4fc42545507f/ui/src/CurrentUser.ts#L93-L105

**Comment by eternal-flame-AD** [comment]
I will check on it later, however after several times during which I was logged out(most of which was due to I stopped the server while leaving the WebUI browser tab open) I always need to delete the obsolete client manually.

**Comment by jmattheis** [comment]
This is a bit different, when you stop the server the websocket connection gets closed and normally a closed ws conn means that the user/client was deleted, therefore the ui deletes the token client side.

**Comment by eternal-flame-AD** [comment]
Okay, @doekia would you please clarify your question a bit further? When you say "every time you log in", did you log out on the WebUI, or you just manually cleared your browser local storage? If the token is cleared, there is nothing we could do at the next login but to create another session. 

Thus, I suppose you are asking for _supporting logging in with an existing client token_, right?

**Comment by doekia** [comment]
I restarted the application, and see multiple time my own device.
To be honest I was expecting some sort of local storage that the device will use to present its previously acquired token (ala ip reservation in dhcp). But on my phone there seems to be not storage.

**Comment by jmattheis** [comment]
It will be stored in the localstorage, but currently if an error (in this case a network error) occurs the token will be deleted. This problem should be fixed with https://github.com/gotify/server/pull/178

**Comment by doekia** [comment]
Regarding localstorage, could it be that the last(s) server(s) be in that storage too.
It is painfull to reenter such url each time we start the application ?

**Comment by jmattheis** [comment]
Are the servers on different urls? If so they shouldn't be able to modify each others local data.

**Comment by doekia** [comment]
Sorry I may be misexpressing my-self. Once I restart the android application, I have to painfully reentrer the url of the server. No autofill, no proposition, did I have misunderstood something?_

**Comment by jmattheis** [comment]
Normally you should stay logged in inside the android application.

**Comment by jmattheis** [comment]
Could you have a look in the logs (it in the upper left corner in the login screen and otherwise in the navigation). Is there any error after you restarted the android app and need to login again.

**Comment by doekia** [comment]
Quite odd, now I restart the application, it does not ask for logon again (hence auto log). 
Probably I made something wrong earlier, nut I have not clues of what.
My apologyze.
