### ISSUE TITLE
An example of using the `/stream` endpoint

### ISSUE THREAD

**Issue by atakanyenel** [gotify/server#179]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

The documentation has examples on how to push messages. It would be nice to have an example that shows how to consume sent messages through websockets and by using the token. Currently the only way to discover is to read the swagger API and find the `/stream` endpoint

**Comment by eternal-flame-AD** [comment]
The process itself is simple, just connect to `/stream` and listens for messages, every new notification is sent as a websocket message. 

@jmattheis Do you think the current documentation needs to include this?

**Comment by jmattheis** [comment]
I think only power users will use the web socket, others will just use the android app or web app and therefore I'd say the current documentation via swagger is enough.

Maybe we could add a link pointing to https://gotify.net/api-docs#/message/streamMessages on the pushmsg documentation page.

**Comment by eternal-flame-AD** [comment]
Yeah, I also think this is relatively straightforward, and I don't think extra documentation is really necessary.
