### ISSUE TITLE
Get 401 Unauthorized while logging with android app with gotify behind traefik (while WebUI works)

### ISSUE THREAD

**Issue by Leosirth** [gotify/server#182]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [X] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

Hi,

I have created the gotify-server docker container with default configuration (only exposed the /app/data volume) and have a traefik container with https entry point and letsencrypt.

I can reach and login the gotify WebUI using the traefik entry point, but I'm not able to login using the gotify android app at the same URL.

Could you please help me to find the root cause?

<details><summary>Gotify Server logs</summary><br><pre>

,[GIN] 2019/04/02 - 15:22:23 | 404 |      36.591µs |     192.168.1.1 | GET      /favicon.ico
,[GIN] 2019/04/02 - 15:22:35 | 200 |     248.386µs |     192.168.1.1 | GET      /stream?token=CG_HdIrFWwdQlGo
,[GIN] 2019/04/02 - 15:22:35 | 200 |      218.67µs |     192.168.1.1 | GET      /application
,[GIN] 2019/04/02 - 15:22:35 | 200 |     335.578µs |     192.168.1.1 | GET      /message?since=0
,[GIN] 2019/04/02 - 15:22:35 | 200 |      50.995µs |     192.168.1.1 | GET      /static/favicon-32x32.png
,[GIN] 2019/04/02 - 15:22:35 | 304 |      32.253µs |     192.168.1.1 | GET      /static/favicon-32x32.png
,[GIN] 2019/04/02 - 15:22:35 | 200 |      35.812µs |     192.168.1.1 | GET      /static/favicon-16x16.png
,[GIN] 2019/04/02 - 15:22:35 | 200 |     137.993µs |     192.168.1.1 | GET      /static/favicon-96x96.png
,[GIN] 2019/04/02 - 15:22:35 | 200 |     121.186µs |     192.168.1.1 | GET      /static/favicon-128.png
,[GIN] 2019/04/02 - 15:22:35 | 200 |     179.026µs |     192.168.1.1 | GET      /static/favicon-196x196.png
,[GIN] 2019/04/02 - 16:19:47 | 200 |   22.445894ms |        10.0.3.1 | GET      /
,[GIN] 2019/04/02 - 16:19:47 | 200 |     395.361µs |        10.0.3.1 | GET      /static/css/main.99a0ea00.css
,[GIN] 2019/04/02 - 16:19:47 | 200 |   40.662157ms |        10.0.3.1 | GET      /static/js/main.08f1207d.js
,[GIN] 2019/04/02 - 16:19:47 | 200 |     749.006µs |        10.0.3.1 | GET      /static/media/roboto-latin-400.5d4aeb4e.woff2
,[GIN] 2019/04/02 - 16:19:47 | 200 |      873.59µs |        10.0.3.1 | GET      /static/media/roboto-latin-500.28546717.woff2
,[GIN] 2019/04/02 - 16:19:47 | 200 |      46.523µs |        10.0.3.1 | GET      /version
,[GIN] 2019/04/02 - 16:19:47 | 200 |      44.331µs |        10.0.3.1 | GET      /static/favicon-32x32.png
,[GIN] 2019/04/02 - 16:19:47 | 200 |      46.824µs |        10.0.3.1 | GET      /static/favicon-16x16.png
,[GIN] 2019/04/02 - 16:19:47 | 200 |      99.212µs |        10.0.3.1 | GET      /static/favicon-96x96.png
,[GIN] 2019/04/02 - 16:19:47 | 200 |     111.809µs |        10.0.3.1 | GET      /static/favicon-128.png
,[GIN] 2019/04/02 - 16:19:47 | 200 |     152.234µs |        10.0.3.1 | GET      /static/favicon-196x196.png
,[GIN] 2019/04/02 - 16:19:47 | 200 |    2.058401ms |        10.0.3.1 | GET      /static/favicon.ico
,[GIN] 2019/04/02 - 16:54:53 | 200 |      37.231µs |   5.169.232.113 | GET      /version
,[GIN] 2019/04/02 - 16:55:31 | 401 |  142.213309ms |   5.169.232.113 | GET      /current/user
,Error #01: you need to provide a valid access token or user credentials to access this api

</pre></details>

<details><summary>Android logs</summary><br><pre>

![image](https://user-images.githubusercontent.com/800911/55421483-97575e80-5579-11e9-905f-7fa980b8cb4d.png)

</pre></details>

**Comment by jmattheis** [comment]
Hey @Leosirth,
could you append your traefik and gotify/server config to this issue? 

The 401 request was done with a public ip. The other successful requests were done with a not public ip, maybe it only works in the local network, but it is only a guess.

It also could be that traefik doesn't proxy the `Authorization` header to gotify/server. This could be caused by a middleware, but without config it is hard to say.

**Comment by Leosirth** [comment]
Hi @jmattheis ,
thanks for your feedback.

Gotify has been launched without any configuration and/or environment variables so has all the defaults.

<details><summary>Traefik config</summary><br><pre>

logLevel="DEBUG"
defaultEntryPoints = ["https"]
################################################################
# API and dashboard configuration
################################################################
[api]
entrypoint="dashboard"
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "XXX"
watch = true
exposedByDefault = false

[entryPoints]
  [entryPoints.http]
  address = ":81"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":82"
  [entryPoints.dashboard]
  address = ":8181"
  [entryPoints.https.tls]

[acme]
acmeLogging = true
email = "XXX"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

</pre></details>

<details><summary>Gotify docker labels</summary><br><pre>
traefik.enable=true
traefik.port=80
traefik.frontend.passHostHeaders=true
</pre></details>

**Comment by jmattheis** [comment]
@Leosirth how do you specify the url in the android app with http (`http://yourdomain.com`) or with https (`https://yourdomain.com`). When using http it wont work because the login credentials will be omitted when the redirect from http -> https happens.

**Comment by Leosirth** [comment]
@jmattheis I use the https URL with a custom port

**Comment by Leosirth** [comment]
I started from scratch re-creating the gotify docker container and now is working fine.
Sadly I don't know what was the problem.

Sorry to have bothered you.
