### ISSUE TITLE
Install Gotify with Nginx Server

### ISSUE THREAD

**Issue by mskian** [gotify/server#189]
Hey I looking for Proper and Clean Nginx VHOST setup for Gotify on Nginx

**Comment by eternal-flame-AD** [comment]
Can you refer to https://gotify.net/docs/nginx?

**Comment by mskian** [comment]
Thanks, mate I forget this 
I am going to run Gotify using Binary file instead of docker

This systemd configuration is OK (Tested on my local system works well)

```
[Unit]
Description=Start Gotify - a simple server for sending and receiving messages
Requires=network.target
After=network.target

[Service]
Type=simple
User=mrbot
WorkingDirectory=/home/grootSanthosh/gotify
ExecStart=/bin/bash /home/groot/Santhosh/gotify/start.sh
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```

**Comment by eternal-flame-AD** [comment]
If it works on your system then it should be fine.

Can you take a look at our issue template and include necessary information to resolve you problem? Thanks. I am having difficulty interpreting your question.

**What do you want to achieve?**

**What have you done?**

**what problem did you encounter?**

**Comment by mskian** [comment]
sorry mate 
actually, I am looking for Nginx setup but I forget our docs 
I need your Nginx Configuration if possible share it
also Share the perfect read, connect and send timeout for WebSocket

**Comment by eternal-flame-AD** [comment]
So I guess the docs has resolved your problem, right?

**Comment by mskian** [comment]
Yes done
