### ISSUE TITLE
Error is not returned on database error

### ISSUE THREAD

**Issue by harishkumar574** [gotify/server#190]
**Can the issue be reproduced with the latest available release? (y/n)** Y

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x] Linux machine
- [ ] Windows machine

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [x] gotify-cli
- [x] Android Client 
- [x] 3rd-party API call (Please include your code)

**Bug Details**
When i send messages containing emoji then those messages will be pushed but not stored on database. They disappear after refresh.

**Comment by eternal-flame-AD** [comment]
@harishkumar574 Which database are you using?

@jmattheis I think we should not ignore database errors.

**Comment by harishkumar574** [comment]
> @harishkumar574 Which database are you using? Mysql

**Comment by eternal-flame-AD** [comment]
You will need to enable multibyte support on your mysql database by taking a look at [this](https://mathiasbynens.be/notes/mysql-utf8mb4) article. @harishkumar574

**Comment by harishkumar574** [comment]
Thanks @eternal-flame-AD ,

Worked after changing **CHARSET**  to utf8mb4 and **COLLATE** to utf8mb4_unicode_ci

Here is what i did:

1. Alter Database charset and collate by using following command
`ALTER DATABASE database_name CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`
2. Alter table where messages are stored which is **messages** table
`ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`
3. Now, modify mysql connection to use `utf8mb4` in `config.yml` by changing it to below
`connection: database_user:database_password@tcp(127.0.0.1)/gotifydb?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local` 
4. Now reload and restart gotify and nginx by executing following commands:
`sudo systemctl daemon-reload`
`sudo systemctl restart gotifypush`
`sudo service nginx restart`

**Comment by jmattheis** [comment]
@eternal-flame-AD Yeah, errors like this should lead to a 500 internal server error.

**Comment by mskian** [comment]
> Thanks @eternal-flame-AD ,
> 
> Worked after changing **CHARSET** to utf8mb4 and **COLLATE** to utf8mb4_unicode_ci
> 
> Here is what i did:
> 
> 1. Alter Database charset and collate by using following command
>    `ALTER DATABASE database_name CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`
> 2. Alter table where messages are stored which is **messages** table
>    `ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`
> 3. Now, modify mysql connection to use `utf8mb4` in `config.yml` by changing it to below
>    `connection: database_user:database_password@tcp(127.0.0.1)/gotifydb?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local`
> 4. Now reload and restart gotify and nginx by executing following commands:
>    `sudo systemctl daemon-reload`
>    `sudo systemctl restart gotifypush`
>    `sudo service nginx restart`

Same issue I am also facing  
this method working well

**Comment by mskian** [comment]
This Guide too share the Perfect Solution [Storing Emoji to Mysql with Golang]( https://hackernoon.com/today-i-learned-storing-emoji-to-mysql-with-golang-204a093454b7)
