### ISSUE TITLE
Best Practice: Run as service

### ISSUE THREAD

**Issue by superwinni2** [gotify/server#192]
Whats the best way to run Gotify server as service on normal server? (No docker)

I created a service file  in /etc/systemd/system and did a deamon-reoad.
But the whole Log runs into syslog / journal ....
Is it possible to change the logging path?

What would be best practice for running as a service?

**Comment by eternal-flame-AD** [comment]
I don't think there is a "best practice" for this, as long as it suits your needs. That is why we support multiple deployment methods.

As for the logging path, I suggest you consult systemd documentation on how to optimize logging.

**Comment by mskian** [comment]
@superwinni2 Check this (Install and Configure Gotify without Docker in Apache Server) - https://github.com/mskian/gotify-apache

**Comment by PanderMusubi** [comment]
See https://github.com/gotify/website/pull/71
