### ISSUE TITLE
I can not send Messages

### ISSUE THREAD

**Issue by Z31L1** [gotify/server#194]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [x ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [ ] Linux native platform
- [x ] Windows native platform

**Describe your problem**

Hi I have set up the Server, I can create apps I reach the server over the http adress in the whole network but it told me always I have wrong Tokens or I don´t be allowed to use the API (403). What I´m doing wrong?  

Thanks for the Help.

**Comment by eternal-flame-AD** [comment]
Would you please provide a general description of the steps you took from creating the application to attempting to send a message? Thanks. (you can mask your application token with `Axxxxx`)

**Comment by Z31L1** [comment]
I have downloaded the Executable for windows, and insert the config.yml Default to Desktop/Gotify/data. Also I downloaded the Gotify App and connect it to the Server. First I have created stuff with the WebUI. Than I tried curl comands looks like it all works only the Message comand get an error. After this I try the CLI but it don´t start. After some more trys I write this Question.

**Comment by eternal-flame-AD** [comment]
Would you please post your curl command you used to create the message? Mask your token with `Axxxx`

**Comment by Z31L1** [comment]
curl -X POST "http://198.168.40.98:80/message?token=<Axxxx>" -F "title=my title" -F "message=my message" -F "priority=5"

**Comment by Z31L1** [comment]
I´m so sorry it was a Noobish Fault token works fine without <> all work thx.
