### ISSUE TITLE
text/markdown in php

### ISSUE THREAD

**Issue by propositionjoe** [gotify/server#206]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

contents here

</pre></details>

**Comment by propositionjoe** [comment]
I have to give 1h to add "text/markdown" fonction on the exemple of the .php in this page https://gotify.net/docs/more-pushmsg .

**Comment by eternal-flame-AD** [comment]
Sorry I am having difficulty understanding your question, did you mean how to add the content type for the push message in PHP?

**Comment by propositionjoe** [comment]
Yes, that's exactly it.

**Comment by jmattheis** [comment]
You can enable display in markdown with adding `text/markdown` as contentType. In PHP you can do it like this:
```php
$data = [
    "title"=> "Helxlo World",
    "message"=> "Test push From **PHP** cURL.",
    "priority"=> 5,
    "extras" => [
        "client::display" => [
            "contentType" => "text/markdown"
        ]
    ]
];
// see https://gotify.net/docs/more-pushmsg#php-using-curl for sending the request
```

**Comment by propositionjoe** [comment]
Perfect,
Thanks
