### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by iDJHost** [gotify/server#209]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.
**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform
**Describe your problem**
Should the app play a notification sound and provide a "popup" push notification?
App is downloaded from Google Play Store
gotify/android v2.0.7; gotify/server v2.0.6

Side question, I can open another "issue" if needed, I use cPanel and my domain.tld has cPanel assigned ssl, is there anyway for gotify to recognize and use it? I currently get Status Code 499 when I try to use https

**Comment by jmattheis** [comment]
Hey @iDJHost,

depending on the priority, the gotify android app will display notifications in a more intrusive way.
0 - not intrusive; 10 - very intrusive (sound & popup). (Only works on Android Version >= 8)

> Side question, I can open another "issue" if needed, I use cPanel and my domain.tld has cPanel assigned ssl, is there anyway for gotify to recognize and use it? I currently get Status Code 499 when I try to use https

Do you experience this issue in the android app, in a browser or both? Does gotify/server output any error messages, when accessing the site via https?

**Comment by iDJHost** [comment]
Browser:
This site can’t provide a secure connection domain.tld:port sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
![ssl4site](https://user-images.githubusercontent.com/21136403/63166580-73f6f280-bff4-11e9-840e-d1620eb1dc1e.png) image is showing https://domain.tld (no port)

From Gotify Android App:
Request to 'https://domain.tld:port/version' failed with status code 0

Cpanel SSL status -  AutoSSL Domain Validated
Expires on November 8, 2019. The certificate will renew via AutoSSL.

I don't mind using http (instead of https) if it's necessary, but for "End Users" (using the app) I'm sure https would be preferred, it's just odd everything I read says you should be able to use https with any port so I'm kind of at a loss.

**Comment by iDJHost** [comment]
Also, Thank you for letting me know about the priority,testing shows 0 gives me an app indicator, then 1-3, App is "just" an inbox but shows messages in pull down, 4-7, gets sound, 8-10, gets sound & popup. Amazing work on the app! Thank You.

**Comment by jmattheis** [comment]
Np. In the upper left corner of the android app is a logs button, could you try to login and then make a screenshot of the logs?

**Comment by iDJHost** [comment]
I cleared the logs and tried reconnecting using https in the app to try to keep the image as small as possible.

![Gotify Log trying to use https](https://user-images.githubusercontent.com/21136403/63177768-3d2dd600-c00e-11e9-84c2-8ea7dc6d47d0.png)

**Comment by jmattheis** [comment]
Could you check which tls versions your server supports?, you can do it here https://www.cdn77.com/tls-test (I don't know this site). Via nmap
```
nmap --script ssl-enum-ciphers -p 443 yourdomain.tld
```
Or via some other way :D.

I'd guess your server only supports tls1.3 and the android app somehow has problems with that.

**Comment by iDJHost** [comment]
TLS 1.3 | NO
TLS 1.2 | YES
TLS 1.1 | NO
TLS 1.0 | NO
SSLv3 | NO
SSLv2 | NO

I am currently in the process Rebuilding apache to support all, will update once complete

**Comment by iDJHost** [comment]
I guess cPanel only supports TLS 1.2, trying to enable more anyway

**Comment by jmattheis** [comment]
TLS 1.2 should work fine. Would you mind sending me your domain where gotify is hosted at per email? (You can find my email on my GitHub profile) Otherwise its pretty difficult to debug (:.

**Comment by iDJHost** [comment]
sent

**Comment by iDJHost** [comment]
Since the original answer has been resolved, I am going to close this. Thank You so much for all your help
