### ISSUE TITLE
How do I use a config file with docker?

### ISSUE THREAD

**Issue by bluuman** [gotify/server#210]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [x] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm trying to set up gotify/server in docker with SSL. I understand docker container is using some separate filesystem, but due to my limited knowledge of docker, I don't understand how to place my config file in the container. The documentation says place config file in /etc/gotify/config.yml, so I have placed it there in my main filesystem, but the docker instance doesn't read my config file. So, is there a command that I can issue or append to the docker run command to copy the config file into the docker container?

**Comment by eternal-flame-AD** [comment]
You can use env vars for configuration. Details are [here](https://gotify.net/docs/config#environment-variables)

**Comment by bluuman** [comment]
thanks. I ended up just mapping the container storage to my /etc/gotify/config.yml file, by issuing this command:  docker run -p 443:443 -p 80:80 -v /var/gotify/data:/app/data -v /etc/gotify/config.yml:/etc/gotify/config.yml gotify/server

**Comment by vivekascoder** [comment]
For setting up gotify with reverse proxy with nginx.

```
server {
	listen 443 ssl http2;
	server_name gotify.example.com;
	
	# For SSL 
	ssl_certificate /etc/letsencrypt/live/gotify.example.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/gotify.example.com/privkey.pem;
	
	# REverse Proxy.
	location / {
	    proxy_pass http://localhost:3000/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
	}
}

```

For creating SSL certificate use certbot.
```bash
sudo certbot certonly --standalone --preferred-challenges http-01 -d gotify.example.com
```

**Comment by siredwin** [comment]
I am finally able to use the environment variables on docker. This project could benefit from using Viper and its ability to auto-convert yml to env variables on demand.
