### ISSUE TITLE
Set Up SSL Through Docker

### ISSUE THREAD

**Issue by bluuman** [gotify/server#211]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I want to run gotify in docker with the letsencrypt ssl option.
`docker run -p 443:443 -p 80:80 -v /var/gotify/data:/app/data -v /etc/gotify/config.yml:/etc/gotify/config.yml -t gotify/server`
config.yml:

> server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 80 # the port for the http server
  ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: true # if the certificate should be requested from letsencrypt
      accepttos: true # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
        - mydomain.com
        - www.mydomain.com
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"
  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed, default only same origin)
database: # see below
  dialect: sqlite3
  connection: data/gotify.db
defaultuser: # on database creation, gotify creates an admin user (these values will only be used for the first start, if you want to edit the user after the first start $  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
pluginsdir: data/plugins # the directory where plugin resides (leave empty to disable plugins)

This config file works when running the gotify binary, and I can connect to the server through SSL. However, when run in docker and try to access site from browser, I get 
`$ sudo docker run -p 443:443 -p 80:80 -v /var/gotify/data:/app/data -v /etc/gotify/config.yml:/etc/gotify/config.yml -t gotify/server`
`Starting Gotify version 2.0.6@2019-07-17-17:41:29`
`Started Listening for TLS connection on :443`
`Started Listening for plain HTTP connection on :80`
`http: TLS handshake error from IP:52497: Get https://acme-v01.api.letsencrypt.org/directory: x509: certificate signed by unknown authority` <-- first connect attempt
`http: TLS handshake error from IP:52499: acme/autocert: missing certificate` <-- subsequent attempts
`http: TLS handshake error from IP:52500: acme/autocert: missing certificate`

**Comment by eternal-flame-AD** [comment]
This is caused by `ca-certificates` not installed in the docker container. I will fix this.

**Comment by bluuman** [comment]
thanks eternal-flame! that package fixed it
