### ISSUE TITLE
Cannot Build the Go App

### ISSUE THREAD

**Issue by cbalano** [gotify/server#214]
**Have you read the documentation?**
- [ x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm having difficulties building the Go code.

When I run: <pre>go build -o gotify.exe app.go</pre> I see this:

<pre>
.....
go: finding golang.org/x/sys v0.0.0-20180927150500-dad3d9fb7b6e
go: finding github.com/mattn/go-sqlite3 v1.9.0
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /var/vendor/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection refused
go: error loading module requirements
</pre>

Any idea why this might be, please?

**Comment by jmattheis** [comment]
Seems like git.apache.org/thrift was moved to https://github.com/apache/thrift/tree/master/lib/go/thrift this bug will probably be fixed when we upgrade the deps from gotify/server. See f.ex. https://github.com/googleapis/google-api-go-client/issues/347

**Comment by zaddok** [comment]
What is the workaround for this. We are unable to deploy to app engine at the moment because of this.

**Comment by jmattheis** [comment]
We probably could use replace in go.mod https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive and replace the old path with the new one. The other way would be to update dependencies as thrift is only a transitive dependency of some deps that gotify/server uses. I'll have a look at it in the afternoon (cest).

**Comment by cbalano** [comment]
FYI, I got past the issue by adding this line in go.mod, right above the require section:
<pre>
replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0
</pre>
