### ISSUE TITLE
Cannot Compile the UI

### ISSUE THREAD

**Issue by cbalano** [gotify/server#215]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Tried to compile the UI via: "npm run build" on Windows
**What did you expect to see?**
The UI compiled
**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\node.js\\node.exe',
1 verbose cli   'C:\\node.js\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle gotify-ui@0.2.0~prebuild: gotify-ui@0.2.0
6 info lifecycle gotify-ui@0.2.0~build: gotify-ui@0.2.0
7 verbose lifecycle gotify-ui@0.2.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle gotify-ui@0.2.0~build: PATH: C:\node.js\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\+p\gotify\ui\node_modules\.bin;...
9 verbose lifecycle gotify-ui@0.2.0~build: CWD: C:\+p\gotify\ui
10 silly lifecycle gotify-ui@0.2.0~build: Args: [ '/d /s /c', 'react-scripts-ts build' ]
11 silly lifecycle gotify-ui@0.2.0~build: Returned: code: 1  signal: null
12 info lifecycle gotify-ui@0.2.0~build: Failed to exec build script
13 verbose stack Error: gotify-ui@0.2.0 build: `react-scripts-ts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\node.js\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\node.js\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid gotify-ui@0.2.0
15 verbose cwd C:\+p\gotify\ui
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\node.js\\node.exe" "C:\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error gotify-ui@0.2.0 build: `react-scripts-ts build`
22 error Exit status 1
23 error Failed at the gotify-ui@0.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Failed to compile.

C:/+p/gotify/ui/node_modules/@material-ui/core/Button/Button.d.ts
(5,18): Interface 'ButtonProps' incorrectly extends interface 'Pick<ButtonBaseProps, "disabled" | "media" | "hidden" | "dir" | "form" | "slot" | "style" | "title" | "color" | "children" | "innerRef" | "name" | "action" | "defaultChecked" | ... 267 more ... | "TouchRippleProps"> & StyledComponentProps<...> & { ...; }'.
  Type 'ButtonProps' is not assignable to type 'Pick<ButtonBaseProps, "disabled" | "media" | "hidden" | "dir" | "form" | "slot" | "style" | "title" | "color" | "children" | "innerRef" | "name" | "action" | "defaultChecked" | ... 267 more ... | "TouchRippleProps">'.
    Types of property 'type' are incompatible.
      Type 'string | undefined' is not assignable to type '"button" | "reset" | "submit" | undefined'.
        Type 'string' is not assignable to type '"button" | "reset" | "submit" | undefined'.

**Comment by jmattheis** [comment]
I don't really know why this broke because we haven't updated any deps that could result in such a failure. Anyway, I'll update the ui deps which should fix this problem.
