### ISSUE TITLE
Consistently getting WebSocket errors

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [gotify/server#217]
**Can the issue be reproduced with the latest available release? (y/n)**: y

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [ ] Nginx
- [ ] Apache
- [x] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
Using Cloudflare
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [x] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Turned off my phone for 5 minutes, then turned it back on

**What did you expect to see?**
That the Gotify app was still connected to the server

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
Connection failed, trying again in 1 minute...
![Screenshot_20190912-073719](https://user-images.githubusercontent.com/15848969/64781340-9b2bdb80-d530-11e9-8b90-dd12a934a1a4.png)

**Comment by jmattheis** [comment]
@ThatNerdyPikachu does this problem also occurs on wifi? Otherwise, it should be kinda normal to have disconnects on mobile network.

**Comment by ThatNerdyPikachu** [comment]
yes, consistently on wifi.

**Comment by jmattheis** [comment]
@ThatNerdyPikachu hey sorry for the late response, you checked caddy for your reverse proxy config. Could you paste you caddy config?
