### ISSUE TITLE
Gotify docker image for armv7 / raspberrypi outdated

### ISSUE THREAD

**Issue by f4b1en** [gotify/server#218]
Hello,
Image for armv7 is 9 month old v1.2.1: https://hub.docker.com/r/gotify/server-arm7
Is it possible to get an image with the latest release v2.0.6?
Thanks

**Comment by jmattheis** [comment]
We removed the armv7 image because it wasn't that much used. But sure thing, we can readd it.

**Comment by jmattheis** [comment]
@f4b1en `gotify/server-arm7:2.0.7` is now available.
