### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by mskian** [gotify/server#225]
Found this issue on Latest Version `2.0.7`
I am using Binary package `gotify-linux-amd64`
While starting the server got this Below error

```bash
./gotify-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./gotify-linux-amd64)
```
> No issues on Previous Version

- Ubuntu 18.04 LTS
- Server Apache

**Comment by eternal-flame-AD** [comment]
We recently advanced our go docker image version for release builds. The lastest build version is based on debian buster, released in 2019, which prolly has a higher glibc version. @jmattheis I think we should revert to an older glibc version for compatibility?

**Comment by jmattheis** [comment]
Yeah, I guess we go for `golang:1.13.1-stretch`. this images has the same glibc version as `golang:1.12.5` (which we used previously)
```
$ docker run --rm -it golang:1.13.1 ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ docker run --rm -it golang:1.13.1-stretch ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ docker run --rm -it golang:1.12.5 ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by eternal-flame-AD** [comment]
Yes let's keep using stretch images

**Comment by mskian** [comment]
Got this from Superuser Forum - https://superuser.com/a/537694

**Comment by jmattheis** [comment]
@mskian Yeah, that's basically what we were talking about :D.

**Comment by jmattheis** [comment]
@mskian Could you try out the newest release?

**Comment by mskian** [comment]
@jmattheis Now Working Perfect :100:

**Comment by manishalankala** [comment]
![image](https://user-images.githubusercontent.com/33985509/75429316-de94cd80-5949-11ea-9f01-91e09d705d24.png)

**Comment by jmattheis** [comment]
@manishalankala This isn't a problem related to gotify. Therefore I'm disabling this issue.

Anymay, as described in https://superuser.com/a/537694 your glibc version is below the glibc version that urbackuprestoreclient is compiled against. You can find the glibc version that your system uses via `ldd --version`.
