### ISSUE TITLE
Automatically reconnect

### ISSUE THREAD

**Issue by quthla** [gotify/server#226]
Currently, when connection to backend is lost, be it due to an update of the container, network outage or something else, the frontend will wait for the user to manually click the retry button.

It would make sense to automatically retry at an interval without any user interaction.

**Comment by eternal-flame-AD** [comment]
Did you mean the android client? It should automatically retry after a few minutes. 
What did you see on the persistent notification? If it was an unexpected disconnect it should show 'retrying in ... minutes'

**Comment by quthla** [comment]
I'm talking about the web frontend.

**Comment by eternal-flame-AD** [comment]
Sorry I was my fault. Yeah this is indeed a limitation.

**Comment by foxbit19** [comment]
Hi, I could take this issue and insert a new feature to manage connection lost state.

**Comment by eternal-flame-AD** [comment]
of course! thx for the contribution!

**Comment by quthla** [comment]
@foxbit19 For me it's not working. The red bar is not showing but it's also not reconnecting by itself.

**Comment by jmattheis** [comment]
@quthla yeah, I tested it like so:
* start gotify
* open website, create application
* stop gotify
* wait some seconds
* start gotify again
* send a message
* *message appears in the still open window*

**Comment by quthla** [comment]
That's exactly what I did. It's also posting `WebSocket connection errored` to the console but other than that it's not working. I'm running gotify behind a reverse proxy which returns a 503 error when it can't connect go gotify. Maybe that confuses gotify?

**Comment by quthla** [comment]
If I stop gotify and then instantly start it again, it will reconnect just fine but when it's offline for a few secs, it will not reconnect again.

Unless I'm missing something in the code, it's reconnecting only once after 3000 msecs and not making any further attempts after. As the red bar is also missing after this PR, there's no other way to manually reconnect other than refreshing the page.

Can you confirm this?
