### ISSUE TITLE
Message search

### ISSUE THREAD

**Issue by gerroon** [gotify/server#236]
Hi

It would be nice if the web app provide a way to search and list the messages. Also would be nice if the cli app can do that too.

thanks

**Comment by jmattheis** [comment]
Do you have a specific use-case in mind for searching messages? I see messages as one-time notifications not something that still has value after a month.

**Comment by gerroon** [comment]
Hi

I was  thinking that the message backend could be used to take simple notes, as in the client send the message to that particular note app.

**Comment by natedalliard** [comment]
notes ≠ notifications

**Comment by jmattheis** [comment]
I don't think that message search is needed. I think gotify isn't used for storage of information only for notifying of events which have a short livespan.

**Comment by Bensawsome** [comment]
I personally would like this search function as well. Sometimes I use my gotify for product sales notifications and get many a day. Sometimes I want to send one link to a friend or sometimes at the end of the day I want to search for a specific product to see if it went on sale that day.

**Comment by Turbo123T3** [comment]
I started using Gotify last month due to me setting up a Reddit Pushover through HASS.IO.

https://community.home-assistant.io/t/reddit-to-pushover-for-mobile-post-notifications-help-solved/231745

I really enjoy Gotify and it's definitely the best use-case for the platform I'm using. I could REALLY use the search function for the same reason Bensawsome posted above.

**Comment by fdw** [comment]
I'm receiving several similar notification about similar batch jobs at about the same time and need to, for example, find out whether a particular job has finished or not. Without a search, I need to read all of them carefully.

**Comment by jmattheis** [comment]
Looks like this fetaure isn't needed by the broader user-base.

**Comment by xiaoweihong** [comment]
search function is good as well,can add it ?

**Comment by jmattheis** [comment]
No, as said, it seems like the broader user-base doesn't need this.
