### ISSUE TITLE
Keeps using the same thumbnail for all image links

### ISSUE THREAD

**Issue by gerroon** [gotify/server#239]
**Can the issue be reproduced with the latest available release? (y/n)** yes

**Which one is the environment gotify server is running in?**
- [x ] Docker
- [ x] Linux machine

Hi

I am using Gotify to notify the clients with links sometimes, and sometimes these links are direct links to the images. I am glad that Gotify can show thumbnails of these images, but it seems like it keeps using the same thumbnail for all the images in the notifications. Please see the image for how it looks. All those thumnbails are different images from different links, except the Gotify's own icon. 

It would be very nice if those images are represented properly in the thumbnails. 

https://i.imgur.com/0R2GYuy.png

thanks

**Comment by jmattheis** [comment]
Gotify does not show any thumbnails for links that were included inside the message. The images on your screenshot can be configured on the applications page.
![image](https://user-images.githubusercontent.com/14895212/68876207-62f97280-0704-11ea-96fd-11a0e44bcfd5.png)

You can use markdown to show the image inside the message. See https://gotify.net/docs/msgextras#client-display

**Comment by gerroon** [comment]
I see, I did not know I assumed it was making a preview based on the image. I will take a look at the link.

**Comment by gerroon** [comment]
Hi,

I looked at the page but I do not understand how I can use it. Mainly because I do not know much about stuff :(

This is my command and I do not know hopw to implement that in the command.

`curl -X POST "http://127.0.0.1:6000/message?token=XXXXXXX" -F "title=MSG" -F "message=$URL" -F "priority=5"

**Comment by jmattheis** [comment]
Extras require a JSON request.

With curl:
```bash
curl --data '{"message": "logo: ![](https://gotify.net/img/logo.png)", "title": "mytitle", "extras": {"client::display": {"contentType": "text/markdown"}}}' -X POST -H Content-Type:application/json "$URL"
```
With [gotify/cli](https://github.com/gotify/cli):
```
gotify push --contentType text/markdown --title mytitle "logo: ![](https://gotify.net/img/logo.png)"
```

**Comment by gerroon** [comment]
thank you

**Comment by gerroon** [comment]
Hi
I cant get this to work :( I d onot know if this is an issue with curl or  gotify.

` curl --data '{"message": "logo: ![$1]($URL)", "title": "IMG", "extras": {"client::display": {"contentType": "text/markdown"}}}' -X POST "http://127.0.0.1:6000/        message?token=XXXXXXXXXXX" -H Content-Type:application/json`

Basically what I see is thet `$URL` replacement is not happening. I get `logo:$1` in the ui instead of seeing the image at all.

**Comment by jmattheis** [comment]
Bash does not evaluate variables in single quotes:
```
$ export URL=https://gotify.net
$ echo 'MY URL IS $URL'
MY URL IS $URL
$ echo "MY URL IS $URL"
MY URL IS https://gotify.net
```

The android app should render markdown as well:
![image](https://user-images.githubusercontent.com/14895212/68992248-475bac80-0869-11ea-94d8-ebece227b5ca.png)
Do you have the newest version?
