### ISSUE TITLE
gotify behind traefik with traefik's automatic cert resolver

### ISSUE THREAD

**Issue by JoeX84** [gotify/server#241]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I'm having difficulties setting up gotify behind a traefik reverse proxy.
I using latest docker, latest docker-compose, and traefik 2.0.5 (which is uses another config methods than 1.x)
So! I want to use gotify throught https but without it's certificate provider.
Is there a way to just enable that, or I must harvest certificates from traefik and provide to gotify

I don't provide my configs now, because I already did some. Please tell if I may try something, or ask if I tried before.

**Comment by jmattheis** [comment]
When traefik is responsible for tls certificates, then you can ignore any tls settings in Gotify. Traefik should proxy the requests to the http endpoint of Gotify.

**Comment by JoeX84** [comment]
Okay, thank you, I'll try

**Comment by hornedfiend** [comment]
I know I'm resurrecting this but I'm trying to get gotify to work behind traefik v2 and not having much luck. Wondering if anyone else managed to get this running and what are the required Header settings and such?

**Comment by jmattheis** [comment]
@hornedfiend open a new issue for this.
