### ISSUE TITLE
[Question] Plan for native desktop client?

### ISSUE THREAD

**Issue by wusatosi** [gotify/server#246]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ ] Docker
- [x] Linux native platform
- [x] Windows native platform

**Describe your problem**
Hi! I would like to inquire if there's any plan for a desktop client?

Yes, the web app is functional with sufficient features, however, the web push-based notifications will not work after the tab is closed. Even if we employ a service worker in the background, it still will not work after the chrome process has exited. Such limitation makes those who want to view notifications on a, for example, a windows desktop, quite difficult.

However, I understand the weight of maintaining another desktop app, so this is not submitted as a feature request, rather as a question. 

So, are there any plans for a basic desktop client?

**Comment by jmattheis** [comment]
Hey @wusatosi,

there aren't any plans for an official native app. However, if someone from the community want to tackle this, I'd be happy to help with it.

**Comment by wusatosi** [comment]
> Hey @wusatosi,
> 
> there aren't any plans for an official native app. However, if someone from the community wants to tackle this, I'd be happy to help with it.

Great, I would like to try that, [electron](https://electronjs.org/) with [node-notifier](https://electronjs.org/) npm module seems to be a good fit, but I'm not experienced with js and apps (I'm more of a backend java/kotlin guy).

Anyhow, I might open up a repo and try that...

Thanks for the reply tho
