### ISSUE TITLE
Long word/URL escapes it's parent box in the WebUI

### ISSUE THREAD

**Issue by PSSGCSim** [gotify/server#247]
**Can the issue be reproduced with the latest available release? (y/n)** y

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>docker-compose up -d</summary><br>

```
version: "3.7"

services:

  server:
    image: docker.io/gotify/server:latest
    restart: unless-stopped
    ports:
      - XXX.XXX.XXX.XXX:3000:8080
    volumes:
      - ./config:/etc/gotify
      - ./data:/app/data
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presence of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
upstream XX_XXXXXXX_PUSH__GOTIFY {
    server nodeXXX.lan.XXXXXXX:3000;
}


server {
    listen [::]:80;
    listen 80;

    server_name push.xxxxxxx.xx;

    location / {
        return 301 https://push.xxxxxxx.xx$request_uri;
    }

    access_log /www/xx.xxxxxxx.push/log/access.log js_access_log;
    error_log  /www/xx.xxxxxxx.push/log/error.log warn;
}


server {
    listen [::]:443 ssl http2;
    listen 443 ssl http2;

    ssl_certificate     /etc/nginx/certs/xxxxxxx.xx/fullchain.cer;
    ssl_certificate_key /etc/nginx/certs/xxxxxxx.xx/xxxxxxx.xx.key;
    include snippets/tls.conf;

    root /www/xx.xxxxxxx.push/public;
    server_name push.xxxxxxx.xx;

    location / {
        # We set up the reverse proxy
        proxy_pass http://XX_XXXXXXX_PUSH__GOTIFY/;
        proxy_http_version 1.1;

        # Ensuring it can use websockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_redirect http:// $scheme://;

        # The proxy must preserve the host because gotify verifies the host with the origin
        # for WebSocket connections
        proxy_set_header Host $http_host;

        # These sets the timeout so that the websocket can stay alive
        proxy_connect_timeout 7m;
        proxy_send_timeout 7m;
        proxy_read_timeout 7m;
    }

    access_log /www/xx.xxxxxxx.push/log/access.log js_access_log;
    error_log  /www/xx.xxxxxxx.push/log/error.log warn;
}
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

Receive message including long URL like "https://example.com/v5jr33wlbi5pe9td31pfiaeja70qfh2w5cnu0bdszoqxo9ue939bjtn2dihl0ki0f5mfqjk27u5djwbtkb3owpn7ns1sov7ptm52vfkcuzp5nctzsieuuvqow5t75o9v3pt0t6nnrwpw1bvjywndxnkwqod5pqbdybxtdmr942unphw8qkhbnf9w35ayxmyotc2u61onqipx2v02qn8gwpqq7rfdgaba8x46feok5ac3hrixuzexeas1lx4shvdd" or any other text including long "word".

**What did you expect to see?**

Text in web GUI should fit into it's box

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

The text is escaping it's parent element and is going outside of the page

![Screenshot_2019-12-14 Gotify](https://user-images.githubusercontent.com/42121756/70845728-50cd3a00-1e52-11ea-8afb-d1855517c57c.png)

This should be an easy fix, adding something like this:

```
word-break: break-all;
```

to the parent element should do the trick.

**Comment by jmattheis** [comment]
Hey @PSSGCSim,

Thanks for you bug report. Would you like to file a pull request for this bug?

**Comment by PSSGCSim** [comment]
Hello @jmattheis
sure, I have submitted the PR https://github.com/gotify/server/pull/248

Thank you
