### ISSUE TITLE
Guidance on extending server API

### ISSUE THREAD

**Issue by dylanparker** [gotify/server#249]
Hey Gotify devs.

I was interested in extending the API specifically so that I could display total message counts beside the application list in the Android client.

First, is this something I should pursue? 

Second, how might one of you approach it?
The call would be requesting an Application list along with a tally of Messages associated with each Application. So, there are message-related aspects, but no actual messages... and Application-related info, with a message count added.

It seems building on the `api/application.go:GetApplications()` function would make the most sense, but of course would make the call heavier with the extra DB calls. It would also require extending the `model/application.go` struct with an overall message count --  which seems to  pollute the current clean model structure.

Are there other precedents in the API where cross-model results are being retrieved and returned?

Any guidance appreciated.

**Comment by jmattheis** [comment]
Hey @dylanparker,

this seems like a useful information, so, feel free to file a PR for it :D.

The count of the messages won't require an additional database call, it can most likely be integrated in the existing query (via join and groupby). In this case, the best place for the count property would be the model.Application. However, we will not need the count for e.q. validating if a application token is valid. In this case, -1 should be set as value. Maybe there could be different methods which give the Application-model with and without count.
