### ISSUE TITLE
Database: Userpassword verify directly

### ISSUE THREAD

**Issue by reschresch** [gotify/server#250]
Hello,
I want to verify a given username and password from my external program. I have access to the database, the username is no problem but the password is in a hash-code.
How I have to translate my given passwort to compare it with this hash-code?

Best regards,

reschresch

**Comment by jmattheis** [comment]
The password is hashed via [bcrypt](https://en.wikipedia.org/wiki/Bcrypt).
https://github.com/gotify/server/blob/6dc783d99d27571c5488da52ae563997f6f225df/auth/password/password.go#L15-L17
