### ISSUE TITLE
Blank page on first install of Gotify

### ISSUE THREAD

**Issue by LoiLock** [gotify/server#254]
Just installed Golang using the binary and used the example config whilst only changing the port and admin credentials.

When I go to the subdomain that I've set-up for Gotify I just get a simple blank page. Using Firefox development tools obviously shows that the HTML is being served without any issues.  
![inspector](https://valvesoftwa.re/rQERJlW4.png)

However 2 javascript files are failing to load:
- Loading failed for the <script> with source “https://[redacted].network/static/js/2.947762c6.chunk.js”. [redacted].network:1:1
- Loading failed for the <script> with source “https://[redacted].network/static/js/main.d94d8f95.chunk.js”. [redacted].network:1:1

When visiting these files directly by going to the location of the file Firefox gives me this error:
![firefox](https://valvesoftwa.re/4PM4GhpJ.png)

It seems to be an issue with gzip. Is there a way to disable this?

**Comment by jmattheis** [comment]
Do you use some kind of reverse proxy like nginx or caddy?

Btw. I cannot open the screenshots, it just says: `Error Fetching Resource`. Could you upload them again or somewhere else?

**Comment by LoiLock** [comment]
It was an issue with the Redbird reverse-proxy that I was using. I've switched to nginx and things seem to work beautifully! Ty
