### ISSUE TITLE
Notification Client?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [gotify/server#255]
Hi all,

I'm trying to replace Pushbullet and am brand spanking new to Gotify. I just installed the server, and now am looking for a client that I can install on my windows machines to popup notifications as they come in, like PB does. Is there one available?

TIA

**Comment by jmattheis** [comment]
Currently no native client for windows is available. You can however get notifications if you have the gotify ui open inside the browser.

**Comment by YouveGotMeowxy** [comment]
Hi @jmattheis 

Is there another, 3rd party, client that is somehow able to do so? By just adding in whatever necessary gotify info into it's settings? Something like a Growl or whatever?

**Comment by jmattheis** [comment]
I dunno, but it should be easy scriptable. 

On linux it could be something like this:
```
$ wscat -c "wss://p.fkng.eu/stream?token=CMKNIeVfsU109vP" | xargs -I '{}' -d$'\n' bash onmessage.sh {}
```
-> `onmessage.sh`
```
all=$@

notify-send --app-name "Gotify" "`echo $all | jq -r .title`" "`echo $all | jq -r .message`"
```
this should basically show notifications on incoming messages (haven't testet it)

**Comment by 4oo4** [comment]
That works really well for me, thanks!

I modified the `onmessage.sh` to be a bit cleaner, and to prevent `notify-send` from complaining about "No summary specified" (even though it still sends?). I also set the urgency on mine to critical, otherwise you don't see the notification right away.

```bash
#!/bin/bash
all=$@

summary="$(echo $all | jq -r .title)"
message="$(echo $all | jq -r .message)"

notify-send --urgency critical --app-name "Gotify" "${summary}" "${message}" > /dev/null 2>&1
```

I'm trying to make a systemd service from this too, and will post that when I have it working.

**Comment by jmattheis** [comment]
> I modified the onmessage.sh to be a bit cleaner, and to prevent notify-send from complaining about "No summary specified" (even though it still sends?).

This is because wscat returns empty lines.
```
$ wscat -c "wss://p.domain.com/stream?token=AAAAAAAA"  | xargs -I '{}' -d$'\n' echo '{}'
{"id":113,"appid":2,"message":"contenxt","title":"test","priority":0,"date":"2020-01-11T09:40:40.710037679+01:00"}

{"id":114,"appid":2,"message":"contenxt","title":"test","priority":0,"date":"2020-01-11T09:40:41.743705346+01:00"}

{"id":115,"appid":2,"message":"contenxt","title":"test","priority":0,"date":"2020-01-11T09:40:42.853833682+01:00"}

```
We can workaround this by checking if `$all == ""` inside the onmessage.sh
```
#!/bin/bash
all=$@

if [ "$all" = "" ]; then
    exit 0
fi

summary="$(echo $all | jq -r .title)"
message="$(echo $all | jq -r .message)"

notify-send --urgency critical --app-name "Gotify" "${summary}" "${message}"
```
The urgency could also depend on the priority of the message.

**Comment by 4oo4** [comment]
Ooh, good idea, didn't think of that. I suppose something that reads priority would look like this:

```bash
priority="$(echo $all | jq -r .priority)"


if [[ $prority -lt 4 ]]; then
  urgency=low
elif [[ $priority -ge 4 ]] && [[ $prority -lt 7 ]]; then
  urgency=normal
elif [[ $priority -ge 7 ]]; then
  urgency=critical
fi

```

**Comment by rystaf** [comment]
Here's a version using powershell and [BurntToast](https://github.com/Windos/BurntToast) for windows 10 notifications
```powershell
param ($domain="p.domain.com", $token="AAAAAAAA")
wscat -c "wss://$domain/stream?token=$token" | %{ convertfrom-json $_ } | where-object {$_.message.length -gt 0} |
 %{ 
    $appid = $_.appid
    $icon = iwr https://$domain/application?token=$token |
        %{ (convertfrom-json $_.content) } | where-object {$_.id -eq $appid} | select -expandproperty image
    new-burnttoastnotification -applogo https://$domain/$icon -Text $_.title, $_.message
  } 
```
