### ISSUE TITLE
Allow overriding base URL

### ISSUE THREAD

**Issue by manicolosi** [gotify/server#256]
I couldn't find anything in the docs to allow setting gotify server to be rooted as a subdirectory (e.g. my.domain.tld/gotify). Would it be possible to add this functionality?

Thanks!

**Comment by jmattheis** [comment]
Our documentation contains reverse proxy configurations with subdirectories [nginx](https://gotify.net/docs/nginx) / [apache](https://gotify.net/docs/apache)

**Comment by manicolosi** [comment]
I completely missed that. I tried something really similar using rewrite in nginx but ran into an issue. When the page would load all the resources were being referenced by the root instead of relative and 404'ing. I'll try again with the exact nginx configuration in case there was something (else) I was missing.

Thanks!

**Comment by samcro1967** [comment]
Is there an example for Caddy that can be shared?

**Comment by jmattheis** [comment]
Yes, have a look at our docs.
