### ISSUE TITLE
Option for created datetime instead of timeago on message show

### ISSUE THREAD

**Issue by x-jokay** [gotify/server#258]
Having an option to show the `created datetime` instead of `timeago` for messages, see [here](https://github.com/gotify/server/blob/6dc783d99d27571c5488da52ae563997f6f225df/ui/src/message/Message.tsx#L102).

**Comment by jyvern** [comment]
+1

**Comment by jmattheis** [comment]
FYI: You can hover to see the timestamp for the date.

Gotify is pretty opinionated and has as few settings as possible. I don't think that adding a switch for date time is a necessary feature. Nevertheless, if enough people from the community want this, I'd be open for PRs.

**Comment by x-jokay** [comment]
And I don't think `timeago` is useful, because it's unprecise 😉

**Comment by eternal-flame-AD** [comment]
This is not really necessary, gotify is more of something to replace some push messaging service rather being like a logging system for events so I don't see why we would need precise timestamps.
