### ISSUE TITLE
Docker compose Nginx + Gotify Server

### ISSUE THREAD

**Issue by mrspartak** [gotify/server#260]
**Is your feature request related to a problem? Please describe.**
So this is not about a problem (problem was to make it run) and now I'd like to share my solution for those who want to deploy with couple commands and don't want to make many config manipulations.

https://github.com/mrspartak/gotify-dc
Pull > Edit .env > docker-compose up

**Comment by jmattheis** [comment]
Hey there, feel free to add your repo to https://github.com/gotify/contrib. 

I'll close this issue because this issue tracker is solely for feature requests, questions and bug reports.
