### ISSUE TITLE
IOS app?

### ISSUE THREAD

**Issue by siredwin** [gotify/server#262]
Thanks for this service. I was on my way to creating something similar in about a month for my needs.  
What is the status of the issue [#87](https://github.com/gotify/server/issues/87)?

**Comment by jmattheis** [comment]
I think the status is still the same. iOS doesn't allow a persistent tcp connection which is required for using the /stream api from Gotify. Maybe it could be implemented via polling (like you said in a earlier revision of the issue), but I don't know if iOS provides a way to execute a service every x minutes.

**Comment by chmac** [comment]
@jmattheis I realise it's a long time after, hope this is useful rather than annoying.

In working with React Native I've found that iOS does have a background job capability. It's possible to run a job every 15 minutes or so, but the precise timing is unreliable. So the polling option may be viable on a technical level. Whether it makes sense or not, well, that's a decision I'll stay clear of!

**Comment by jmattheis** [comment]
@chmac Yep, I think it would be useful to have that. If someone wants to create such an iOS app, I would be happy to support.

**Comment by strider72** [comment]
You may want to follow a very similar project, NTFY, and their work to create an iOS app.

https://github.com/binwiederhier/ntfy/issues/4

**Comment by siredwin** [comment]
@strider72, that looks like a good project that can work in iOS. I will follow it. I decided to do a plugin for WhatsApp notifications. I will contribute when it's done, and I don't need to worry about potential clients having to set up anything.

**Comment by geokvant** [comment]
Hi everyone.
Is there any plan to support push notifications of gotify for Web Apps within new Web Push functionality for iOS 16.4 in Safari?
https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/

**Comment by berot3** [comment]
Maybe @jmattheis can help us? Wanted to ask the same as @geokvant.

Of course, this is not iOS-specific. Does gotify have Web Push under Safari?

**Comment by geokvant** [comment]
> Of course, this is not iOS-specific. Does gotify have Web Push under Safari?

There is some specific implementation for iOS Safari Web Push.

At the moment Safari on my Mac works fine with my Gotify server, but iOS Web App (on iPhone with 16.4 iOS) doesn't work with push :(

**Comment by jmattheis** [comment]
Currently, there is no plan for it. Using Web Push would send the message to another server which then forwards it to the push client. This doesn't really align with Gotify as third-party services are used to deliver the messages.

**Comment by geokvant** [comment]
As I understand in this case there are two options (may be only one):
1) make some Gotify plugin that can do this connection between Gotify server and Apple push-servers
or
2) develop some third-party web-app relay with two interfaces:
- one interface to connect as client to gotify server
- other one - to initiate and maintain connection to Apple URLs *.push.apple.com

**Comment by jmattheis** [comment]
I'd recommend the second option, as the plugin api currently doesn't support subscribing to incoming messages see https://github.com/gotify/plugin-api/issues/3

**Comment by siredwin** [comment]
How about a micro-server running on a different port? The gotify server can run on port :8000 and the other server running on port :8013 for example. That way it can be easily done at the individual server level.

**Comment by jmattheis** [comment]
Yep, I think this is basically the second option geokvant mentioned.
