### ISSUE TITLE
Alpha Desktop Client Available (unofficial)

### ISSUE THREAD

**Issue by ajmcateer** [gotify/server#271]
Wasn't sure where to put this. Please delete if not allowed.

I am building a Desktop Client in .Net Core 3.0 using Avalonia as the front end so it will work on All 3 platforms. This build is very early and I am looking for feedback. 

Downloads can be found on Github Page here under releases.
https://github.com/ajmcateer/GotifyDesktop

I have also provided a C# library for people to use, but note this is a very early version as well and there will be breaking changes, possibly a lot so don't use for anything beyond experimenting for now.
https://github.com/ajmcateer/GotifySharp

Current version (0.1.0) will sync and get the last 200 messages plus listen for new messages via the /stream endpoint.

Toast notifications will be added when https://github.com/AvaloniaUI/Avalonia/pull/3389 is merged. 

There is no error checking if server can't be reached so it will crash. This is being worked on for the next release as well as more descriptive error messages for configuring the server. 

A more comprehensive timeline will be created in the coming weeks.

**Comment by eikendev** [comment]
Nice work! I believe this belongs into the [contrib](https://github.com/gotify/contrib) repository.

**Comment by jmattheis** [comment]
Hey there looks good! I've created https://github.com/ajmcateer/GotifyDesktop/issues/2 for some feature requests/improvements. 

I'll close this issue because this issue tracker is solely for feature requests, questions and bug reports. Feel free to add your project to [gotify/contrib](https://github.com/gotify/contrib).
