### ISSUE TITLE
picture-transfer

### ISSUE THREAD

**Issue by reschresch** [gotify/server#272]
Hello,
I want to send a picture (jpg or png).
Is this possible?

Best regards,

reschresch

**Comment by jmattheis** [comment]
You can display images with markdown. With this it is possible to embed images into the message with `![](url_to_image)`. To enable markdown in messages you have to set the contentType to text/markdown inside the message extras see https://gotify.net/docs/msgextras#client-display

Image upload is not possible.

**Comment by reschresch** [comment]
Thank you very much.
I will have a look.

Best regards,
reschresch

**Comment by jmattheis** [comment]
reopen, if you have further questions.
