### ISSUE TITLE
How to set timezone for Gotify in Docker

### ISSUE THREAD

**Issue by eltiel** [gotify/server#274]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I ran the official Docker image with TZ environment variable but it seems to have no effect. Timezone remains at GMT+0.

**Any errors, logs, or other information that might help us identify your problem**
I can tell the timezone does not match by going through the log timestamps via the Android app.

**Comment by jmattheis** [comment]
Does this result in any problems?

**Comment by eltiel** [comment]
Not a real problem. It's just a bit more difficult to read the logs as the time is not in sync.

**Comment by jmattheis** [comment]
The fix will be included in the next release.

**Comment by x-jokay** [comment]
> Does this result in any problems?

The effective time on hover of the timeago is shown in `GMT+0` as well.

**Comment by eltiel** [comment]
I tested 2.0.15 but TZ still doesn't seem to do anything. Has anyone gotten it to work?

**Comment by jmattheis** [comment]
For me TZ has an effect on server logs.
```bash
$ date
Tue 05 May 2020 07:03:18 PM CEST

$ docker run --rm -it -p 8080:80 gotify/server:2.0.15
Starting Gotify version 2.0.15@2020-04-26-12:01:05
Started Listening for plain HTTP connection on :80
[GIN] 2020/05/05 - 17:03:24 | 200 |     286.811µs |      172.17.0.1 | GET      /version

$ docker run --rm -it -e TZ="Europe/Berlin" -p 8080:80 gotify/server:2.0.15
Starting Gotify version 2.0.15@2020-04-26-12:01:05
Started Listening for plain HTTP connection on :80
[GIN] 2020/05/05 - 19:03:31 | 200 |      105.34µs |      172.17.0.1 | GET      /version
```

**Comment by x-jokay** [comment]
For me `TZ` works as well:

```yml
  ...
  environment:
      - TZ=Europe/Zurich
  ...
```

gives 

```sh
/app # date
Tue May  5 19:07:36 CEST 2020
```

**Comment by eltiel** [comment]
I'm seeing the logs through the Android app 2.0.11.

![IMG_20200506_012946](https://user-images.githubusercontent.com/11868456/81096579-326af680-8f39-11ea-95d4-db866e9bcfd9.jpg)

You can see that the new messages received are in +8 but the log entry timestamp itself is +0

**Comment by jmattheis** [comment]
This issue is only about the logs inside the docker container. Not in android.

**Comment by eltiel** [comment]
> This issue is only about the logs inside the docker container. Not in android.

OK. I guess I wrongly assumed that the logs are pulled from the server to begin with.

**Comment by Bra-Ger** [comment]
Hello,
Thank you for your fast reply.  The answer for me was already given deep down in the remarks of [Bug #53 ]. 
Gotify needs `TZ=UTC ` as timezone if you are using Unraid.

Thank you for the hint. This bug can be closed.
