### ISSUE TITLE
Plugin hook on message applications 

### ISSUE THREAD

**Issue by pchampio** [gotify/server#278]
The current plugin system does not expose any hooks on an application's message.
 For each message sent on an application, a plugin hook function would be called with the request body and prams, allowing the plugin to have more control.
 What I would like to do is to relay all of the incoming gotify messages of some applications to a [Signal](https://www.signal.org/) group chat.
Such plugin would allow me to use Gotify on iOS!

**Comment by jmattheis** [comment]
Hey @pchampio,

you could add a [webhook plugin](https://gotify.net/docs/plugin-write#webhooker) which mirrors the message api and then send a message via [messenger](https://gotify.net/docs/plugin-write#messenger). Also, you could make a simple bash script which listens on the websocket and then forwards the messages to signal.

I'll close this issue in favor of https://github.com/gotify/plugin-api/issues/3 as it matches the functionality.
