### ISSUE TITLE
App token is not unique per app.

### ISSUE THREAD

**Issue by happymario** [gotify/server#286]
**Can the issue be reproduced with the latest available release? (y/n)**

Yes I can.
I run it on docker latest.

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details>
<summary>
I run docker by this command.
</summary>
<br>

```
docker run -p 80:80 -v /var/gotify/data:/app/data gotify/server.
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>There is any configuration.</summary><br>

```
No I have no proxy.
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
I login to webUI by admin.

And I ran android two devices.
It has different tokens.
I login in same two accounts.

I send push by command.
curl "http://192.168.0.117/message?token=AnU.0L_1wm8qV8P" -F "title=my title" -F "message=my message" -F "priority=5"

It showed me same push on two devices.

**What did you expect to see?**

I want to see one push per device.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
It 
![Image 1](https://user-images.githubusercontent.com/22416542/77409886-fb131100-6df4-11ea-8a26-68a3e2c518da.png)

**Comment by jmattheis** [comment]
Hey, in Gotify every devices receives notifications from all application that a user owns.

**Comment by happymario** [comment]
I want to send notification per device.
How can I do it?

**Comment by jmattheis** [comment]
You could create multiple accounts.

**Comment by happymario** [comment]
I think, it is not good way to create user account per device.
Why don't you implement it like fcm?

**Comment by pm-pm** [comment]
> Why don't you implement it like fcm?

Because this is not FCM? ;-)

**Comment by happymario** [comment]
It is your project name "A self-hosted push notification service".
FCM is the general Push Notification Service for all developers.

**Comment by jmattheis** [comment]
If you want exactly the functionality of FCM then use FCM :P. I only implemented the features that I needed for Gotify, I didn't try nor wanted to replicate FCM.

**Comment by happymario** [comment]
ok
