### ISSUE TITLE
Why does it need client token?

### ISSUE THREAD

**Issue by happymario** [gotify/server#287]
I hope to use the client token by device identifier.
Is it possible?

I hope to send notification to device by it.

**Comment by jmattheis** [comment]
You can only send notifications via an application token. It is not possible to send notifications via a device token.

**Comment by happymario** [comment]
Client Token is unique per device, I want to send one notification per device.

**Comment by jmattheis** [comment]
Could you explain a little more what you are trying to achieve?

**Comment by happymario** [comment]
I am trying to send notification to a specific device on admin web page.
In Web page, I see client token is created per device, so it can use device identifier.
Is it possible?

**Comment by jmattheis** [comment]
No only the tokens can be used for authentication.

**Comment by happymario** [comment]
Can you add this feature by send it to a specific device?

**Comment by jmattheis** [comment]
See https://github.com/gotify/server/issues/186

**Comment by happymario** [comment]
Thank you. I will wait this feature
