### ISSUE TITLE
Linked Data Notifications support

### ISSUE THREAD

**Issue by muety** [gotify/server#289]
Did you ever consider implementing the "Receiver"-side of the [Linked Data Notifications](https://www.w3.org/TR/ldn/) protocol? Personally, I'm tinkering with linked data technologies and decentralized social web approaches right now and Gotify was the first thing that came to my mind when I learned about LDN. 

I'm not sure if there's an actual need for LDN support. But it probably wouldn't be too hard to implement in Gotify and could help spread those concepts designed by W3C.

**Comment by jmattheis** [comment]
I don't think this is needed.
