### ISSUE TITLE
Unraid Plugins installation

### ISSUE THREAD

**Issue by pfckiko** [gotify/server#291]
Does anyone know or having any experience in getting the pluggings installed on the  Unraid Gotify container? I can't figure out what I am doing wrong and have not had any type of success getting the plugins installed. the only one I really need is the webhook plugin.
 I know someone will be reading this and say 
![image](https://media1.giphy.com/media/j5TuBLY1lTXBC/source.gif)
but while you say that please help me. the tutorials I read are not working. so far I was able to install **GO** inside the docker image but when I try to install the plugin by using **Go Build** command it says 

```
# command-line-arguments
./webhook.go:7:2: undefined: Plugin
```
then I try to run it as root and instead of building it I run it by using the command  
**su root ./webhook.go**  and I get this error 
```
./webhook.go: line 1: package: not found
./webhook.go: line 3: import: not found
./webhook.go: line 5: //: Permission denied
Webhooker: not found
interface: not found
{ is a shell keyword
./webhook.go: line 7: Plugin: not found
./webhook.go: line 8: //: Permission denied
./webhook.go: line 9: syntax error: unexpected word (expecting ")")
``` 
![image](https://media.giphy.com/media/9u1mPQs4JPVY3sokXp/giphy.gif)
If you charge for your time and the price is not high I might be able to pay you just let me know.

**Comment by jmattheis** [comment]
Hey there. Have you used the plugin template and have tried building it with: `make GOTIFY_VERSION="v2.0.14" FILE_SUFFIX="for-gotify-v2.0.14" build`? You may need to execute `make download-tools` before.

**Comment by pfckiko** [comment]
> Hey there. Have you used the plugin template and have tried building it with: `make GOTIFY_VERSION="v2.0.14" FILE_SUFFIX="for-gotify-v2.0.14" build`? You may need to execute `make download-tools` before.

I did but i don't remember what happen when i tried it. I know for a fact i didn't execute the tools. So today ill do both and hope it works.

**Comment by pfckiko** [comment]
ok so i ran in to a big issue. i cant install make since gotify is in a docker container and the container does not have the apt get command. any other ideas.? or if you can make a container can i pay you to make a few?

**Comment by jmattheis** [comment]
You only need make on your host system and not inside a gotify container. make runs docker commands and builds the plugin.
Like this:
![makebuild](https://user-images.githubusercontent.com/14895212/80004555-fef88880-84b1-11ea-871c-8cc36b98eb72.gif)

You don't even need a build environment. You can let travis-ci build your plugin: https://github.com/gotify/plugin-template/blob/master/.travis.yml

**Comment by pfckiko** [comment]
I swear if it's not one thing is another. The only way to install make is currently not working. I'll try again in a month or so. hopefully, they fix the make plugin.
