### ISSUE TITLE
Showing the server version number before login could pose a security risk.

### ISSUE THREAD

**Issue by EdrisT** [gotify/server#292]
Showing the server version number in the upper left corner before login could pose a security risk. I dont se any reason why it should it be there.

My suggestion is to not show the server version number before login.

**Comment by jmattheis** [comment]
Hi @EdrisT,

Thanks for your issue (:.

There is actually an api for the version, it can used by clients to check which apis are available https://gotify.net/api-docs#/version/getVersion 
Nevertheless, you could use a reverse proxy to return some arbitrary version number in /version (something really high to ensure that clients don't break).

Without the version endpoint it should still be pretty easy to identify which version of gotify is running. F.ex. by checking the static resources of the ui. (the hash is unique per build)
```bash
$ docker run -d --name gotify -p 1333:80 gotify/server:2.0.13
1b7a73fa9036259b751b49a821e07a7b76142e68ea5882655b03527dec9ddd75
$ http http://localhost:1333/static/js/main.858acb9d.chunk.js -h
HTTP/1.1 404 Not Found
... other stuff

$ docker rm gotify -f
gotify
$ docker run -d --name gotify -p 1333:80 gotify/server:2.0.14
59a7ce778c521649a3f9c24500271c6b3fad7bb86299ea4e538b8a0de69a78d1
$ http http://localhost:1333/static/js/main.858acb9d.chunk.js -h
HTTP/1.1 200 OK
... other stuff
```
Hiding the version would not improve security and would certainly decrease user experience and make client development harder. Therefore, I don't think it it worth to remove the version endpoint.

**Comment by EdrisT** [comment]
Ok, I understand. 
Thanks for the quick response and your work on this project.
