### ISSUE TITLE
Is it possible to change the message icon?

### ISSUE THREAD

**Issue by wsw70** [gotify/server#295]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

Currently I receive all messages, from all apps with the same (cute) icon of the gopher with the enveloppe.

Is it possible to change the icon:
- on a per-message basis? (by integrating the icon in the message)
- ~~on a per-app basis? (where the icon would be hosted on the server)~~ (I found that one: it is possible to set this up at the app level)

**Comment by jmattheis** [comment]
Currently it is only possible to change the icons per application.

**Comment by wsw70** [comment]
Thank you, I will create as many apps as there are families of messages then.
