### ISSUE TITLE
Notifications by Email

### ISSUE THREAD

**Issue by siredwin** [gotify/server#296]
If I was trying to add Email notifications, would writing a plug-in be enough?

**Comment by jmattheis** [comment]
What do you mean exactly sending emails for gotify notifications or posting messages to gotify and receive an email?

**Comment by siredwin** [comment]
The latter(posting messages to gotify and receive an email?). I know I could easily do that with a script but I would like Gotify to Push to Android and send me an Email. What is the right approach?

**Comment by jmattheis** [comment]
Subscribing to messages via plugins is currently not supported. See  https://github.com/gotify/plugin-api/issues/3 for the feature request. Like you said, you could write a script, that connects to the websocket. You can probably copy most of the script from this issue https://github.com/gotify/server/issues/255 and only replace the line where a desktop notification is sent.

**Comment by mat-l** [comment]
Sending a push notification to the gotify android app and as well to an email account would be great to replace the the not existing iOS app.

By this idea one could send the information to several parties, android app users and other user on iOS or PC.

I am really interested im such a feature/hack.

**Comment by siredwin** [comment]
Well, connecting to the stream might work for getting messages.  
It looks like the Plugin can "Send messages as an application" in the feature description.  
If that is the case, I don't need to see the message details.  
Since I know the application and possibly the user, I can modify how else to deliver that message, perhaps finding the same message in the stream above.
It would be nice if the Application Model can be extended to have a "extras" parameter.

@mat-l is right, the Android App is an overkill for me.

**Comment by siredwin** [comment]
One more thing.
I see that stream links a message-id to an app-id.
How would I link an app to user or a message to a user?

**Comment by jmattheis** [comment]
You access the stream with a client token, with this token you can retrieve the current user -> https://gotify.net/api-docs#/user/currentUser

**Comment by siredwin** [comment]
Perfect! I forgot about the tokens. I will update when I come up with something.

**Comment by siredwin** [comment]
@jmattheis, this actually works.
If I was to convert this whole script into a plugin, would it be ok? Or would I be breaking something else?

**Comment by jmattheis** [comment]
If you can implement it as a plugin, then it shouldn't be possible to break something from gotify/server :D.
