### ISSUE TITLE
Docker setup not working

### ISSUE THREAD

**Issue by mat-l** [gotify/server#297]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [x] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I'm having difficulties setting up my docker configuration. The configured image and plugin folder are not considered and the sqlite is still in the docker container itself, although I used the envs. Not sure what I am doing wrong. :-(

**Any errors, logs, or other information that might help us identify your problem**

Please find attached the screenshot of my Portainer configuration:

![IMG_20200415_213907](https://user-images.githubusercontent.com/5571947/79381657-99ad1080-7f62-11ea-99f9-d343b108b040.png)

</pre></details>

**Comment by jmattheis** [comment]
what do you mean with "not considered". What are you expecting to happen?

**Comment by mat-l** [comment]
I mean, that the database is still keept in the docker image itself. Same for image which I upload to the Gotify application. Theybare not stored in the volume and therefore all of the data is not persistant while updating the docker image for example.

**Comment by jmattheis** [comment]
> `/app/data` contains the database file (if sqlite is used), images for applications and cert-files (if lets encrypt is enabled).

https://gotify.net/docs/install

You've defined `/var/gotify/data` as volume mount.

With `GOTIFY_DATABASE_CONNECTION=gotify.db` you override the default of `data/gotify.db`. In your configuration the database file would be inside /app/gotify.db. You probably don't want to override this default, because you do not want to mount /app because it contains the binary.

**Comment by mat-l** [comment]
Thanks for the hint. Now I understood the misconfiguration and it is working perfectly.
Thanks for your work and the project. :-)
