### ISSUE TITLE
Allow multiple CORS origins

### ISSUE THREAD

**Issue by StewartThomson** [gotify/server#299]
First off, thanks for this project. I make use of it literally every day.

I realize this is a fairly niche request.

I would be happy to implement it myself, and do all necessary documentation/testing should this be approved.

**Is your feature request related to a problem? Please describe.**
I am currently actively developing a [browser extension](https://github.com/StewartThomson/Gotify-Ext) for gotify. One issue I've run into is the setting of the CORS `Access-Control-Allow-Origin` header. Currently, it can only be set to one origin at a time. Which means that I, or any user, can't use both the Chrome extension and the Firefox extension (or any other browser client they desire).

**Describe the solution you'd like**
I think it would make the most sense to make this similar to the 'stream: allowedorigins' config already present, as that permits multiple origins. It could be 'cors: allowedorigins'. The code would just need to loop through that list and see if the request matches any of the specified origins, in order to set the response header correctly.

**Describe alternatives you've considered**
Currently, the only way to achieve this functionality is to set 'Access-Control-Allow-Origin: "*"' which would certainly work but is not ideal for security purposes

Let me know! Thanks

**Comment by jmattheis** [comment]
Hey there,

this seems like a good addition. It sucks that it's not included in the http spec :D.
To prevent breaking changes, this setting must receive a new property inside the config.
