### ISSUE TITLE
Test bug: Environment config overrides in config testing

### ISSUE THREAD

**Issue by StewartThomson** [gotify/server#300]
Hope it's ok that I didn't follow a template, but this isn't directly related to the server

In the config_test (and perhaps others, haven't thoroughly checked), some functions like `TestConfigEnv` set environment variables to test the config without clearing them after the test is complete. As a result, if different values are given in the `TestConfigFile`, that test will fail as the `Configuration` struct will pick up the environment variables set earlier.

I can fix this in the branch that I'm doing #299 in if that's ok. Or I can make a separate branch

**Comment by StewartThomson** [comment]
lol nevermind. this was my own doing.

**Comment by jmattheis** [comment]
See https://github.com/gotify/server/commit/66ae74f830bce997d6c96c49a2a50977d5d6f4a7
