### ISSUE TITLE
Add curl package to enable Docker healthcheck

### ISSUE THREAD

**Issue by sadmin91** [gotify/server#308]
**Is your feature request related to a problem? Please describe.**
I am using your image for my personal use.
Actually, I build a custom image (using your image as source) in order to add curl package to create a healtcheck for my swarm service.
I think the addition of this package could help others users.

**Describe the solution you'd like**
Add curl package on Docker image

**Describe alternatives you've considered**
Build a custom Docker image to add this package

**Comment by jmattheis** [comment]
I think we can also include the healthcheck to our docker images. 

What do you think of this?
https://github.com/gotify/server/blob/76de16e72a644720498422acbe22e947993e448d/docker/Dockerfile#L1-L7

**Comment by sadmin91** [comment]
@jmattheis Yes, i'm doing this today.
But why not include curl package on the official Gotify image?

**Comment by jmattheis** [comment]
Ahh, I'm planning on including this in the official image :D.

**Comment by jmattheis** [comment]
Fixed with #310

**Comment by sadmin91** [comment]
curl package has been added on _standard_ Dockerfile.
is it possible to add this package on ARM Dockerfile?
