### ISSUE TITLE
I need Plugin access to  current request URL host, path, etc

### ISSUE THREAD

**Issue by siredwin** [gotify/server#322]
I need to be able to construct URLs in the Plugin based on the current server without having to hard-code anything. Example `myurl := "ws://" + host + "/stream?token=" +token`
Is this something that can be done on Webhooker? Or is there another way to access it easily?

**Comment by jmattheis** [comment]
The host should be present on the http request inside the gin context:
```
func (c *EchoPlugin) RegisterWebhook(baseURL string, g *gin.RouterGroup) {
	c.basePath = baseURL
	g.GET("/echo", func(ctx *gin.Context) {
		host := ctx.Request.Host
	})
}
```
