### ISSUE TITLE
Attributions on footer and a chance to use personal logo.

### ISSUE THREAD

**Issue by siredwin** [gotify/server#328]
I am going to be fully incorporating and using Gotify as my main push service/notifier.
Thank you so much.
I promise I will have contributions in the future!

The UI works perfectly that I don't see a need to re-create it or even do my own that does API calls, except maybe create new users.

Since I will be having clients go there to create Client or App tokens, it would be nice for them to see my logo/name rather than "Gotify"

Why not create a permanent footer that has all your attributions instead i.e "Powered by Gotify,  version #, Github link, etc"?

That way I can get a chance at personalizing and still correctly attribute.

**Comment by jmattheis** [comment]
Hey @siredwin,

nice that you've found a use-case for Gotify (:. 

> Since I will be having clients go there to create Client or App tokens, it would be nice for them to see my logo/name rather than "Gotify"

I like to keep the settings and overall Gotify as simple as possible. Your use case seems only be useful to a small amount of people, thus, I'm against implementing such settings in gotify/server.

In case you still want to personalize Gotify, you can [build Gotify from scratch](https://gotify.net/docs/build) and edit the `gotify`-header text.
https://github.com/gotify/server/blob/92a468bf74f243c94f2c2a94db96247c962bef03/ui/src/layout/Header.tsx#L103-L105
the title
https://github.com/gotify/server/blob/92a468bf74f243c94f2c2a94db96247c962bef03/ui/public/index.html#L8
And the favicon:
https://github.com/gotify/server/blob/92a468bf74f243c94f2c2a94db96247c962bef03/ui/public/index.html#L23

**Comment by siredwin** [comment]
Thanks, this will work too.
