### ISSUE TITLE
Extend main config or add my own config file inside data?

### ISSUE THREAD

**Issue by siredwin** [gotify/server#330]
I have successfully created an email plugin.
The problem is that it has some sensitive variables hard-wired into it.
I can get some variables from the configurer(which I do), but I also need some variables on a JSON, YML, or TOML file.

1. Can I add extra variables to the main config file? How would I access them from the plugin?
2. Can I add a yml/json file to /data? How can I access it from the plugin?

A  good idea might be to use a `GOTIFY_DATADIR=data` from which I can use to reconstruct a file path to my file inside the data directory. I will experiment on this using `GOTIFY_UPLOADEDIMAGESDIR`

Thanks in advance.

**Comment by siredwin** [comment]
I forgot that this is just a regular go server at its core.
`"."` is the location of the go binary.
`"./data"` would be the data directory.

So far so good.

**Comment by jmattheis** [comment]
I think you can use environment variables to define secrets for your go plugin.

**Comment by siredwin** [comment]
Environment variables will probably work for docker. But for now I can extend the original config or use my own. That is all I wanted.
