### ISSUE TITLE
setting up windows version

### ISSUE THREAD

**Issue by kamikazem** [gotify/server#339]
setting up windows version seems impossible , there is no documentation & the config.yml is not getting recognized , so i think because i have an iis runnig on port 80 on my server , i get the error : 
listen tcp :80: bind: an attempt was made to access a socket in a way forbidden by its access permissions.

any help please ?

**Comment by jmattheis** [comment]
You can't run two processes on the same port. Choose a different one.

Have you put the config.yml in the same directory as the binary?

**Comment by kamikazem** [comment]
> 
> 
> You can't run two processes on the same port. Choose a different one.
> 
> Have you put the config.yml in the same directory as the binary?

yes , i did put the config.yml as the binary (.exe) file

**Comment by jmattheis** [comment]
And you've changed the port inside this file?

**Comment by kamikazem** [comment]
on the first two lines , i did :
server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 6016 # the port the HTTP server will listen on

**Comment by jmattheis** [comment]
How do you start gotify?

**Comment by kamikazem** [comment]
i open an administrator command prompt & type in the exe file name

**Comment by jmattheis** [comment]
is your current working directory the directory of the config file and the binary?

**Comment by kamikazem** [comment]
i manage to run the exe and get the error from it , isn't that enough ? 
if not , how should i check or set  my working directory ?

**Comment by jmattheis** [comment]
How are you executing gotify inside your command prompt (show screenshots).

Do you execute something like
```
> gotify-windows-amd64.exe
```
or like this:
```
> somepath/gotify-windows-amd64.exe
```
in case it is the second, `cd` into the directory where the gotify bin lives.

**Comment by kamikazem** [comment]
thanks , that did the job
