### ISSUE TITLE
What special rights are needed to delete a message via the API?

### ISSUE THREAD

**Issue by wsw70** [gotify/server#340]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I would like to create, and then to delete a message via the API. The problem I am having is that the delete fails because it is unauthorized.

First I successfully send a message:

```
# echo  '{"title": "hello", "message": "world"}' | http POST "https://gotify.xxxx/message?token=AU_
-lQ5DHV4XM.G"
HTTP/1.1 200 OK
Content-Length: 107
Content-Type: application/json
Date: Sat, 11 Jul 2020 07:08:58 GMT
Server: Caddy

{
    "appid": 3,
    "date": "2020-07-11T07:08:58.906503687Z",
    "id": 448,
    "message": "world",
    "priority": 0,
    "title": "hello"
}
```

I then try to delete it:

```
# http DELETE "https://gotify.xxxx/message/448?token=AU_-lQ5DHV4XM.G"
HTTP/1.1 401 Unauthorized
Content-Length: 141
Content-Type: application/json
Date: Sat, 11 Jul 2020 07:09:36 GMT
Server: Caddy

{
    "error": "Unauthorized",
    "errorCode": 401,
    "errorDescription": "you need to provide a valid access token or user credentials to access this api"
}
```

Which authorization is missing?

**Comment by jmattheis** [comment]
https://gotify.net/docs/
> A client is a device or application that can manage clients, messages and applications. However a client is not allowed to send messages.

> An application is a device or application that only can send messages.

You need a client token to delete messages.

**Comment by wsw70** [comment]
Thanks, this is still confusing to me.

So to send a message I use the token of an application.
And to delete said message (having its `id`) I use a client, and its token.

I am not sure how a client is authorized to delete a message of an application but I will give it a try, thanks.

**Comment by jmattheis** [comment]
A client token is like authentication via basic authentication, you get all rights from the user. Application can only send messages and clients may delete messages from any application owned by the user.

**Comment by wsw70** [comment]
OK thanks. What I was missing is that an application does not have to be authorized by a user to send messages to that user.
Thanks again.
