### ISSUE TITLE
Frequent Websocket and TCP Keep Alives keep LTE connection open and drain battery

### ISSUE THREAD

**Issue by heurekus** [gotify/server#343]
Hi,

I have installed Gotify on an Ubuntu 18.04 server VM, no docker, no proxy, straight forward. The server works well but I notice that there is frequent TCP traffic, **around every 10 seconds** between the server and the Android client. This keeps the LTE connection to the network constantly in RRC-Connected state and has a significant impact on battery use.

I ran a Wireshark trace, see screenshot attach which shows that this is caused by two thing:

WebSocket keep alives (ping/pong)
TCP keepalives

Both keepalives are always triggered from the servers side.

Note: Other messaging systems such as Prosody/Conversations/XMPP only send tcp-keep alive messaging every 7-10 minutes. This is way more batter efficient.

Are there any settings to adapt Gotify's keep alive messaging frequency?

Thanks,
Martin

![2020-07-28_13-50-Gotify-tcp-ack and websocket ping](https://user-images.githubusercontent.com/47881430/88679695-f8e8f800-d0ef-11ea-999e-d29a7ebd43ca.png)

**Comment by jmattheis** [comment]
Currently there are no ways to configure the websocket ping or the keepalive interval. But they probably could be added.

**Comment by heurekus** [comment]
It would be very useful to have that. Currently with packets flowing every 10 seconds, I can't install the client app on an Android device. Could you label it as a feature request? If anyone implements this, I would be very happy to do beta-testing for it :-)

**Comment by jmattheis** [comment]
Hey @heurekus, In https://github.com/gotify/server/tree/keepalive I've added the settings `server.keepaliveperiodseconds` and `server.stream.pingperiodseconds` to the config.yml (see config.example.yml).

Could you try it out and check if it fixes your problem?

**Comment by heurekus** [comment]
Hi Jannis, cool! Would you have the amd64 executable of that branch for me? I haven't set up a dev environment for the project so this would obviously make things easier :-) Let me know if you need a place to drop it, let me know and I'll send you a link by email.

**Comment by jmattheis** [comment]
Sure, here's the build: [keepalive.zip](https://github.com/gotify/server/files/5010626/keepalive.zip)

**Comment by heurekus** [comment]
Hi Jannis,

works like a charm! I tried it for 6 hours now, with both parameters set to 550 seconds. While the Android App is still a bit chatty and establishes 3 Websockets simultaneously and messages are transported over each, they do their ping/pong keep alives almost simultaneously. This way, I get silence on the channel for around 6-7 minutes without running into NAT timeouts. 

TCP keep alives are only sent for inactive web sockets. I guess the OS recognizes that TCP traffic was sent and thus sends no TCP keep alives. Nice!

Very cool! Thanks!

**Comment by jmattheis** [comment]
Nice, I'll add the changes to the next release.

**Comment by heurekus** [comment]
That is great, thanks again! Already integrating Gotify with my server monitoring system now :-)

**Comment by heurekus** [comment]
Ups, looks like the keepalive change breaks TLS connection establishment. Here's the output, seems to have happened in other Go projects before as well.

```
$ sudo ./gotify-linux-amd64
Starting Gotify version keepalive@2020-08-01-16:08:45
Started Listening for TLS connection on :7222
Started Listening for plain HTTP connection on :7221
panic: interface conversion: net.Conn is *tls.Conn, not *net.TCPConn

goroutine 11 [running]:
github.com/gotify/server/v2/runner.setKeepAlivePeriod.func1(0x1673620, 0xc00035aa80, 0x0)
        /proj/runner/runner.go:68 +0x10c
net/http.(*conn).setState(0xc0002ebb80, 0x1673620, 0xc00035aa80, 0x0)
        /usr/local/go/src/net/http/server.go:1725 +0xe4
net/http.(*Server).Serve(0xc000344380, 0x1667fe0, 0xc0003abc20, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2932 +0x320
net/http.(*Server).ServeTLS(0xc000344380, 0x16690a0, 0xc0003aacc0, 0xc00026b3b0, 0x21, 0xc00026b3e0, 0x24, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2973 +0x297
net/http.(*Server).ListenAndServeTLS(0xc000344380, 0xc00026b3b0, 0x21, 0xc00026b3e0, 0x24, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:3130 +0x11b
github.com/gotify/server/v2/runner.Run.func2(0xc000344380, 0xc0000ed980)
        /proj/runner/runner.go:44 +0x58
created by github.com/gotify/server/v2/runner.Run
        /proj/runner/runner.go:43 +0x2c7
```

Startup of the standard binary works o.k.:
```

sudo ./gotify-linux-amd64.original 
Starting Gotify version 2.0.17@2020-07-18-19:24:04
Started Listening for TLS connection on :7222
Started Listening for plain HTTP connection on :7221
[GIN] 2020/08/06 - 08:17:03 | 200 |    1.712239ms |   79.216.53.160 | GET      "/current/user"
[GIN] 2020/08/06 - 08:17:03 | 200 |     2.21981ms |   79.216.53.160 | GET      "/stream?token=xxxxxx"
[GIN] 2020/08/06 - 08:17:03 | 200 |    3.126486ms |   79.216.53.160 | GET      "/application"
[GIN] 2020/08/06 - 08:17:03 | 200 |    5.126883ms |   79.216.53.160 | GET      "/message?since=0"
[GIN] 2020/08/06 - 08:17:04 | 200 |    1.086982ms |   79.216.53.160 | GET      "/current/user"
```

A quick search revealed a similar problem in another project with a fix. Perhaps useful here as well:

https://github.com/etcd-io/etcd/issues/2184

**Comment by jmattheis** [comment]
I'll have a look at that.

**Comment by heurekus** [comment]
When you look at this and have a fix, could you send me another binary before the next version? Would like to put this into private production use with tls enabled :-) Thanks!

**Comment by jmattheis** [comment]
@heurekus Sorry that it took so long, here the updated code https://github.com/gotify/server/compare/keepalive and the built binary: 
[keepalive2.zip](https://github.com/gotify/server/files/5154702/keepalive2.zip)

Could you recheck if it works correctly?

**Comment by heurekus** [comment]
Had it running yesterday and overnight with https, timeouts set to 500 seconds and IPv6 thrown in for good measure with lots of messages being sent. Starts and runs o.k., looks very nice! Fixed! Thank you very much!!!

**Comment by EVOTk** [comment]
Hello,
I have a docker installation, is it also possible to modify this parameter?

**Comment by jmattheis** [comment]
Yeah, you can use the environment variables `GOTIFY_SERVER_STREAM_PINGPERIODSECONDS` and `GOTIFY_SERVER_STREAM_PINGPERIODSECONDS`. See https://gotify.net/docs/config

**Comment by EVOTk** [comment]
Thx, I had not seen them on the documentation!

**Comment by jmattheis** [comment]
Yeah, just added them (:.

**Comment by EVOTk** [comment]
Hello,
If I use:
GOTIFY_SERVER_STREAM_PINGPERIODSECONDS=120
GOTIFY_SERVER_KEEPALIVEPERIODSECONDS=300

I have a lot of message:
`WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF`

If I delete the settings, it goes back to normal in the logs

**Comment by jmattheis** [comment]
As written in the documentation

> Only change this value if you know what you are doing.

https://gotify.net/docs/config

This isn't a magic setting that increases batterylife without drawbacks.

**Comment by Tey** [comment]
The default keep-alive interval is a [hard-coded value](https://github.com/golang/go/blob/81188661f1fd51f67dfff40c451d4e878b533a66/src/net/dial.go#L17) in Go set to 15 seconds. There also exists a system default value (`net.ipv4.tcp_keepalive_intvl` on Linux), but for some reasons, the Go developers decided to ignore it. The hard-coded value is too small for battery powered devices, so you should really consider using a different value in the default server configuration. For instance, on most Linux systems I've tried, the default keep-alive interval value is set to 75 seconds. Since the WS ping period is set to 45 seconds by default on the server (and 1 minute on the Android app), maybe a 60 seconds default keep-alive interval would make more sense.

One a side note, setting `GOTIFY_SERVER_KEEPALIVEPERIODSECONDS` to a negative value disable the sending of keep-alive packets. It seems like relying only on WS ping mechanisms works good enough for me (even after increasing the WS ping period to 5 minutes), but YMMV I guess.

**Comment by jmattheis** [comment]
Hey @Tey, it certainly could improve battery life, but it could also break things for existing users. F.ex, I've seen some load balancers that kill connections if there wasn't a frequent TCP keep alive. Sure, it unlikely, but connection stuff is a pain in the ass to debug.

Power users that want to have the best experience and can debug bugs themselves can change the existing settings for TCP keep-alive & web socket ping period.

**Comment by Tey** [comment]
@jmattheis just to be clear, my point was that the default value in Go makes no sense because it is different from the system default value which has been carefully chosen by people who actually designed the system network stack. I don't quite see the reason why Go programs would use a different keep-alive interval value than other programs that work just as well. But well, maybe I should open a ticket in golang/go about that instead of talking about it here :)

Anyway, if you still believe the default Go value is reasonable, can you consider changing the comment about `keepaliveperiodseconds` so that it indicates that a value of 0 will use the Go default instead of the "system default" please? Maybe something like:
````
    keepaliveperiodseconds: 0 # 0 = use Go default (15s); -1 = disable keepalive; set the interval in which keepalive packets will be sent. Only change this value if you know what you are doing.
````

**Comment by jmattheis** [comment]
Alright (:, I'll change the comment.

**Comment by heurekus** [comment]
For what it's worth I've set both parameters to 550 because the NAT of my wireless network provider kills TCP connections 10 minutes after the last packet. Works like a charm but I'm sure other network operators or load balancers have stricter values. So to get the best setting, watching the log or a tcpdump for frequent reconnects is the only way to find the right value without breaking something along the way. Some more details [here.](https://blog.wirelessmoves.com/2020/08/improving-the-keep-alive-behavior-of-gotify.html)

**Comment by bam80** [comment]
> my point was that the default value in Go makes no sense because it is different from the system default value which has been carefully chosen by people who actually designed the system network stack. I don't quite see the reason why Go programs would use a different keep-alive interval value than other programs that work just as well. But well, maybe I should open a ticket in golang/go about that instead of talking about it here :)

Hi @Tey and all, just stumbled upon it in another Go project (Telegram proxy):
https://github.com/9seconds/mtg/issues/526
Thank you for the research, it helped a lot! Didn't try to fix it there yet but looks like the problem is the same.

So it seems like a bug in the Go library indeed, and should be addressed there in the first place. Otherwise, the story will continue, since many years it was fist discovered.
I see no reason to hard override system-default value specifically for Go, it looks like a nonsense.

Have you had a chance to report it upstream?

**Comment by Tey** [comment]
> Have you had a chance to report it upstream?

Hey @bam80. No I haven't, and to be honest, I don't feel brave enough to argue and fight for such a change for a language I barely know. Feel free to do it then😉

**Comment by bam80** [comment]
Done, thanks for the input:
https://github.com/golang/go/issues/79621

BTW, I don't know Go at all ;)
