### ISSUE TITLE
Gotify at subdir gives blank screen

### ISSUE THREAD

**Issue by pieterhouwen** [gotify/server#346]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [x] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I have installed gotify on my server that is also running some other services with nginx, when configuring nginx to use the upstream gotify server (I configured the subdirectory to go to /push/ instead of /gotify/), but when I go the the URL I only see an empty page, and when looking at the Network Requests tab in my Firefox I can see that a bunch of requests that result in a 404.

![get requests](https://user-images.githubusercontent.com/10866686/89081449-9744ba00-d38b-11ea-9b13-e28866c1689b.PNG)

**Any errors, logs, or other information that might help us identify your problem**

I'm a little hesitant to post my entire config files here because gotify isn't the only thing running on my server and pasting the output here would make this an extremely long post which may or may not help. On the other hand I don't know whether my other nginx configurations might be responsible for this issue. 

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

(perhaps relevant parts) nginx.conf

upstream push {
# Set the port to the one you are using in gotify
  server localhost:6645;
}

    location /push/ {
        proxy_pass         http://push;
        rewrite ^/push(/.*) $1 break;
        proxy_http_version 1.1;

        # Ensuring it can use websockets
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto http;
        proxy_redirect     http:// $scheme://;

        # The proxy must preserve the host because gotify verifies the host with the origin
        # for WebSocket connections
        proxy_set_header   Host $http_host;

        proxy_connect_timeout   7m;
        proxy_send_timeout      7m;
        proxy_read_timeout      7m;

    }

I left out the server directive at the "location /push/" part because my nginx server already redirects all traffic on port 80 to 443

To be safe I also copied above directives into the existing sites-available configuration file. 

</pre></details>

I'm not sure exactly what is happening or what I'm doing wrong, so any help would be appreciated!

I'm using Firefox as my browser by the way if that's any help.

**Comment by jmattheis** [comment]
How have you installed gotify/server? Are there also 404 errors when you access gotify/server directly?

**Comment by pieterhouwen** [comment]
Yes I have tried both installing locally and using the docker image. When I do a docker logs -f I only see the requests for / and not for the rest of them.

**Comment by jmattheis** [comment]
I cannot reproduce your problem. I can access http://localhost:12345/push/ without any problems.

docker-compose.yml
```yml
version: '3'
services:
    nginx:
        image: nginx:1.14.2
        ports:
            - "12345:80"
        volumes:
            - ./config.conf:/etc/nginx/conf.d/config.conf
    gotify:
        image: gotify/server:2.0.17
```
config.conf
```
server {
  listen 80;

  server_name localhost;

    location /push/ {
        proxy_pass         http://gotify:80;
        rewrite ^/push(/.*) $1 break;
        proxy_http_version 1.1;

        # Ensuring it can use websockets
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto http;
        proxy_redirect     http:// $scheme://;

        # The proxy must preserve the host because gotify verifies the host with the origin
        # for WebSocket connections
        proxy_set_header   Host $http_host;

        proxy_connect_timeout   7m;
        proxy_send_timeout      7m;
        proxy_read_timeout      7m;

    }
}
```

**Comment by pieterhouwen** [comment]
Thanks for your reply. I think the issue was with the existing nginx configuration, hadn't occured to me yet that I could also just have nginx in the Docker environment. 

So looking at the docs if I wanted to use SSL I would use the following config files:

config.yml

server:
 ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # /etc/ssl/fullchain.pem
    certkey: # /etc/ssl/privkey.pem

docker-compose.yml

version: '3'
services:
    nginx:
        image: nginx:1.14.2
        ports:
            - "12345:80"
            - "12354:443"
        volumes:
            - ./config.conf:/etc/nginx/conf.d/config.conf
            - /etc/letsencrypt/live/site/privkey.pem:/etc/ssl/privkey.pem
            - /etc/letsencrypt/live/site/fullchain.pem:/etc/ssl/fullchain.pem
    gotify:
        image: gotify/server:2.0.17

With the same nginx conf you posted above?
Do I need the full config.yml?

**Comment by pieterhouwen** [comment]
Closing this issue because my initial question has been resolved but help would still be greatly appreciated!

**Comment by jmattheis** [comment]
@pieterhouwen When using tls then gotify should just act as a normal http server (not https) and nginx should handle all the tls traffic and forward it to the http api of gotify.

**Comment by monsdar** [comment]
Sorry for bringing this up again... As far as I understand the blank screen is the result of gotify WebUI trying to load further resources from non-subpath pathes like `/static/index-eGvATxVq.js`.

* Site resides at `http://localhost/push`
* User accesses site in browser
* nginx config parses the path, forwards request to gotify (without the /push), so gotify thinks its root is requested
* gotify returns root page, browser begins to load the page
* On top of the page there are further resources like `/static/index-eGvATxVq.js` which need to be loaded
* Browser requests `http://localhost/static/index-eGvATxVq.js`
* nginx does not know how to handle, as the needed resource would be behind `http://localhost/push/static/index-eGvATxVq.js`

Using subpathes behind a reverse proxy will not work as long as gotify does not provide support for this. Or did I miss something?

*NOTE: I understand that this is an old issue. Perhaps back then there were no dynamically loaded resources in the services webui?*

**Comment by eternal-flame-AD** [comment]
Hi, is this a problem you are having right now or are you simply curious about the problem this user is experiencing? 

> Using subpathes behind a reverse proxy will not work as long as gotify does not provide support for this. Or did I miss something?

I don't think so, as with the above reply, gotify should support this as long as the URL is rewritten correctly, a known good config is posted.

In your example, the rewrite didn't work likely because you used "/push" instead of "/push/" which messes up with relative URL resolution. /push ( without slash) should return 404 or redirect to "/push/"

**Comment by monsdar** [comment]
You're right, the trailing slash seems to be the solution. I missed the forward there. I also found the docs on using different types of reverse proxies along with gotify. Thank's for coming back 👍
