### ISSUE TITLE
Potential import collision: import path should be "gopkg.in/yaml.v2", not "github.com/go-yaml/yaml".

### ISSUE THREAD

**Issue by KateGo520** [gotify/server#347]
## Background
The `go-yaml/yaml` has already renamed it’s import path from "github.com/go-yaml/yaml" to "gopkg.in/yaml.v2".
As [README](https://github.com/go-yaml/yaml/blob/v2.1.0/README.md) of `go-yaml/yaml` v2.1.0 said, downstream repos should use "gopkg.in/yaml.v2" to get or import `go-yaml/yaml`.

```
Example
Some more examples can be found in the "examples" folder.

package main
import (
        "fmt"
        "log"
        "gopkg.in/yaml.v2"
)
…
```

But `gotify/server` still used the old path:
https://github.com/gotify/server/blob/master/go.mod#L9 
```
github.com/go-yaml/yaml v2.1.0+incompatible 
```

When you use the old path "github.com/go-yaml/yaml" to import the `go-yaml/yaml`, it will be very easy to reintroduce `go-yaml/yaml` through the import statements "import gopkg.in/yaml.v2" in the go source file of `go-yaml/yaml`.
https://github.com/go-yaml/yaml/blob/v2.1.0/decode_test.go#L12
```
package yaml_test
import (
	…
	. "gopkg.in/check.v1"
	"gopkg.in/yaml.v2"
)
```

The "gopkg.in/yaml.v2" and "github.com/go-yaml/yaml" are the same repos. This will work in isolation, bring about potential risks and problems.

## Solution
Replace all the old import paths, change `"github.com/go-yaml/yaml"` to `"gopkg.in/yaml.v2"`.
Where did you import it: https://github.com/gotify/server/search?q=github.com%2Fgo-yaml%2Fyaml&unscoped_q=github.com%2Fgo-yaml%2Fyaml

**Comment by KateGo520** [comment]
@jmattheis  @eikendev  Could you help me review this issue? Thx :p

**Comment by jmattheis** [comment]
I'm fine with changing this. @KateGo520 would you like to open a pull request for this?

**Comment by 0x111** [comment]
@jmattheis I can take this if it is still up for grabs. (if KateGo520 is not interested of course)

**Comment by jmattheis** [comment]
Feel free to do so (:.
