### ISSUE TITLE
How users works?

### ISSUE THREAD

**Issue by steevanb** [gotify/server#348]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [X] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Hi,

I don't understand how users works.
When i log into Android app with admin user, all notifications are received.
If I create an user, then connect with it on Android app, notifications are not received.

How can I send a notification to a particular user? Or how user works?

Thanks

**Comment by jmattheis** [comment]
See https://gotify.net/docs/
> Users are only able to manage (view/edit/delete) clients and applications (includes messages sent by the app) that they've created.

A user sees only messages from applications they've created.

**Comment by steevanb** [comment]
Thanks a lot, i've misssed this partin the documentation.

My bad !
