### ISSUE TITLE
Add curl package on ARM Dockerfile

### ISSUE THREAD

**Issue by sadmin91** [gotify/server#350]
On issue #308, curl package has been added on standard Dockerfile.
is it possible to add this package on ARM Dockerfile?

**Comment by jmattheis** [comment]
That's not that easy because we need some kind of emulation on travis-ci to install packages while building the arm docker image.
I'll see what I can do.

**Comment by minecraftchest1** [comment]
Github actions supports multiple operating systems on multiple architectures, including arm64.

**Comment by Enissay** [comment]
Please update on this. It is needed to enable container healthcheck
