### ISSUE TITLE
Add "Version" Information for monitoring

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#360]
Hello,

i would like to have some more information at the /[version ](https://gotify.net/api-docs#/version/getVersion)url

Especially i want to have a static item to check it during monitoring. With uptimerobot.com you can check a static website regularly and check its content.

If the page /version could also give rudimentary information about the system status (Errors yes or no) this would be a good idea.

```
{
  "buildDate": "2018-02-27T19:36:10.5045044+01:00",
  "commit": "ae9512b6b6feea56a110d59a3353ea3b9c293864",
  "version": "5.2.6"
  "ApplicationName": "Gotify Server" # To perform a static "running yes/no" check. THIS is what i need. :-) (No need to change monitoring after Server Update) ;-) 
  "Architecture": "amd" # Maybe?
  "Errors": "No" # A simple hint if you should check the server or not.
}
```

Thanks.
pm-pm

**Comment by jmattheis** [comment]
For errors, Gotify already exposes a /health api -> https://gotify.net/api-docs#/health/getHealth
You could also use this for the static running check.

**Comment by pm-pm** [comment]
**Sorry** for not having seen this. it was just too late tonight.
I didn't think that something like this already existed.

The ticket may be closed. Thanks.
