### ISSUE TITLE
Errors in Serverlogfile, but no problems. I have no idea

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#362]
Hello.

Running gotify server on debian buster behind an apache proxy. **Works well**. :-)

There are always errors in the logfiles and I have no idea where they come from or what the cause could be.
Does anybody have an idea where I could have a look or what these errors mean?

Thanks.

![gotify random errors](https://user-images.githubusercontent.com/47995430/93580890-ac5bc380-f9a0-11ea-9d00-093869c12c56.png)

**Comment by jmattheis** [comment]
Errors like this can be caused by a faulty reverse proxy, but they are also common in a correctly deployed Gotify instance. i/o timeouts or web socket closures because EOF can happen when a client loses connection this is likely when using the android app with cellular network.
