### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by strugee** [gotify/server#364]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to download Gotify releases, including future updates, without having to trust GitHub except on the first download.

**Describe the solution you'd like**

Binaries in GitHub Releases should be accompanied by detached signatures, either from GPG or (something compatible with) OpenBSD Signify. (Signify is much easier to use than GPG. I hear minisign is a popular compatible format.)

**Describe alternatives you've considered**

None really. Running a package manager repository, I suppose?

**Additional context**

None

**Comment by jmattheis** [comment]
Gotify is built automatically on travis-ci, so the builds would be signed there as well. I don't think it adds much security because travis ci still could add malicious code to the binary.

**Comment by strugee** [comment]
Yeah, agreed. Feel free to close if you don't think you'll ever move to building locally.
