### ISSUE TITLE
Can't make text/markdown extra work

### ISSUE THREAD

**Issue by alforlea** [gotify/server#365]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

Making use of server v2.0.17 and android app v2.0.14.

**Describe your problem**
Good morning. I'm not being able sending markdown messages following the instructions from the documentation. I'm using the python requests library as suggested in the docs as well as the client::display extra, but regardless of how I try to set it up the message is always shown in plain/text mode. I tried send a bold text with the cli and in that case it worked well.

**Any errors, logs, or other information that might help us identify your problem**
Here's the code that I'm using. In the attached image you can see in the UI that plain/text is being shown, the same is happening in the android app so I suspect that it may be because of my code.

`
requests.post(gotify_complete_url,data={"extras":{"client::display":{"contentType":"text/markdown"}},"title":"Test!","message":"Foo *bar* ![](https://www.w3schools.com/images/w3schools_green.jpg)","priority":"5"})             
`

![Selección_001](https://user-images.githubusercontent.com/31888101/95969361-e6d54680-0e0e-11eb-81ab-9072707c11e4.png)

**Comment by jmattheis** [comment]
See https://gotify.net/docs/more-pushmsg#python on how to send messages with python. You sending your request parameters with form content type, and not with json.

changing your `data=` to `json=` should do the trick.

**Comment by alforlea** [comment]
Thanks Jannis!

I had already tried with "json" instead of "data", but in contrast to the "data" one, any notification was shown. 

However, I've just realized about the error, which was setting the priority value as a string instead of as an integer, which prevented anything to be displayed when used with the json key.

Thanks again
