### ISSUE TITLE
json: cannot unmarshal string into Go struct field MessageExternal.id of type uint

### ISSUE THREAD

**Issue by mcnaveen** [gotify/server#367]
**Can the issue be reproduced with the latest available release? (y/n)** - Yes

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine

**Do you have a reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presence of a reverse proxy)**
- [ ] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [x] 3rd-party API call (Please include your code)

**What did you do?**
I'm trying to send push via HTTP. and getting the following error.

`json: cannot unmarshal string into Go struct field MessageExternal.id of type uint`

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

Unfortunately, I can't provide the code. Because I'm using a third-party tool (SilferBots)
![image](https://user-images.githubusercontent.com/8493007/98850325-9e935d80-247a-11eb-8426-4778a7c87f13.png)

**Comment by jmattheis** [comment]
Your request looks fine:
```bash
$ http POST "https://push.example.com/message?token=Aoaeuouoeuoe&title=Support123&priority=10&message=123-abc&id=444"
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Wed, 11 Nov 2020 19:02:12 GMT
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding

{
    "appid": 3,
    "date": "2020-11-11T20:02:12.589471105+01:00",
    "id": 232,
    "message": "123-abc",
    "priority": 10,
    "title": "Support123"
}
```
I can reproduce your problem, when sending a json body with an id property with a string as value:
```bash
jm@dyne ~ λ echo '{"id": "123"}' | http POST "https://push.example.com/message?token=Aaoeuoeueou"
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 143
Content-Type: application/json
Date: Wed, 11 Nov 2020 19:05:24 GMT
Server: nginx

{
    "error": "Bad Request",
    "errorCode": 400,
    "errorDescription": "json: cannot unmarshal string into Go struct field MessageExternal.id of type uint"
}
```
Thus, the software you're using for sending the push notification probably adds a body like this which is not allowed.

**Comment by mcnaveen** [comment]
Solved by Setting like this...

![image](https://user-images.githubusercontent.com/8493007/98861723-c212d400-248b-11eb-9c4d-3a6fd5f77f96.png)
