### ISSUE TITLE
How can I install gotify in heroku or vercel?

### ISSUE THREAD

**Issue by mcnaveen** [gotify/server#368]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I need help/guide for setting up gotify in Heroku or vercel
I checked the documentation and it doesn't contain any information regarding this.

**Comment by jmattheis** [comment]
You probably have to write a buildscript that works with heroku or execute the binary directly. I have no experience with Heroku, so I can't help.

**Comment by jmattheis** [comment]
Here is a third-party tutorial on how to deploy to heroku https://dev.to/sophiabrandt/free-pushbullet-alternative-with-gotify-on-heroku-1ilc
