### ISSUE TITLE
disable the authentication

### ISSUE THREAD

**Issue by Famku** [gotify/server#369]
**Have you read the documentation?**
- [*] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [*] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

Hi, is it possible to disable the authentication or set the login with the url?

I just want to use it locally on a signage screen.

**Comment by jmattheis** [comment]
This is not possible. You can login and then the user should stay logged in.
