### ISSUE TITLE
running gotigy behind apache server from binary - how to add custom port to config or config file it self?

### ISSUE THREAD

**Issue by georgesuba** [gotify/server#373]
Hi there, thanks for gotify! 

its great notification 'app' out there. I do implement this into my fail2ban and also to ssh logins etc.. I am in middle of writing my docs in .md and I am hope it might get some usage out there (if I could contribute to your docs).. anyway I use this in past lets say 6 months on separate server and since I've updated my hdd to 120TBs I would like to host it my self on my own from home where I run virtualmin etc and would like to access gotify via port 80 - however binary file refuses to run on port 80 as apache sits there. is there any way to run command with custom yaml config file? Please enlighten me. I will figure out from there how to serve lets encrypt from behind its self-proxy ;)

(basically I would like to run the binary on 8888 or something like that)

Thank you very much once again!

**Comment by georgesuba** [comment]
Hi, sorry for bothering you. I had obviously one of those days, when solution was right on front of me, just did not used my brain as I should. All working :+1: 

Thank you very much again!

**Comment by jmattheis** [comment]
No problem. In case someone else encounters this. You can set the port via .yml or environment variable see https://gotify.net/docs/config
