### ISSUE TITLE
Update Dockerhub Image frequently

### ISSUE THREAD

**Issue by worldworm** [gotify/server#378]
Hi,
this Docker image in Dockerhub with the "latest" tag is now over 3 months old.

Please run your build process/pipeline regularly even without new commits in this repo to get regular security updates of the base images.
fyi: Your base image is also a bit older: https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/issues/45

Thanks!

**Comment by jmattheis** [comment]
Hi @worldworm

thanks for your issue. Yeah, gotify should probably change the base docker image to something that gets updates more frequently.

**Comment by jmattheis** [comment]
with v2.0.21 a debian image is used as base.
