### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by polizz** [gotify/server#381]
**Have you read the documentation?**
- [ x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm trying to figure out next steps of troubleshooting why my volume mounts in azure are not working. I'm seeing the base files being created on startup, but I see this db panic message. The files left are of zero size. I've recreated my shares several times. I've been looking through the code and I do not see any db.AutoMigrate call defined anywhere in that file or in the dependencies, so I'm kind of at a loss of what it's trying to do on line 53 that fails.

**Any errors, logs, or other information that might help us identify your problem**
<details><summary>container startup output</summary><br><pre>

Starting Gotify version 2.0.21@2021-01-06-15:38:32

[35m(/proj/database/database.go:53)[0m 
[33m[2021-01-13 18:59:33][0m [31;1m database is locked [0m
</pre></details>

<details><summary>shared contents after startup</summary><br>
![gotify-share](https://user-images.githubusercontent.com/10888433/104497804-84701b80-55a0-11eb-898e-579c738bea0f.png)
</details>

The container runs fine without my volume.

UPDATE:
My config export from the azure definition looks like this. This remains the same between it working without a volume mount and when it does not work with a volume mount.

GOTIFY_SERVER_SSL_ENABLED
true
GOTIFY_SERVER_SSL_PORT
443
GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED
true
GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS
true
GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE
certs
GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS
- ...
GOTIFY_DEFAULTUSER_NAME
...
GOTIFY_DEFAULTUSER_PASS
...
GOTIFY_SERVER_SSL_REDIRECTTOHTTPS
true

Startup routine is based upon whatever is in the dockerhub definition for gotify/server. That is also the same between successful and unsuccessful startups.

**Comment by jmattheis** [comment]
How do you start gotify, please also post your config.

**Comment by polizz** [comment]
Thanks, updated above ☝️

**Comment by polizz** [comment]
So after a few more hours of research I think I've solved it. There are large incompatibilities with sqlite locking and Azure file shares. I found some other [issues](https://github.com/grafana/grafana/issues/16638#issuecomment-498811755), and duplicated their workaround. I was able to create a manual db file with the proper journal pragma and gotify came online properly.

This was accomplished via the command: ```sqlite3 gotify.db "VACUUM;'pragma journal_mode=wal;'"``` then uploading that file to the expected location and then using the DSN of ```file:data/gotify.db?_journal=WAL``` for the **GOTIFY_DATABASE_CONNECTION** env.

Thank you very much for producing this app, it is working quite well for my intended use.

Btw, it would be nice to have an additional flag to put let's encrypt in staging mode during testing.

Related to that, the HEALTHCHECK parameter currently in the dockerfile is hard coded to check localhost, which for my SSL-only setup, always fails: ```2021/01/14 01:12:02 http: TLS handshake error from 10.240.255.55:64687: EOF``` (I run a .dev domain). I'm not sure how you can parameterize that, but it currently is just churning and would require a custom dockerfile to stop it.

**Comment by jmattheis** [comment]
Okay, I think I'll close this as this is an issue related to the environment. Gotify can't really do much here.
