### ISSUE TITLE
One sender to many recievers app / model

### ISSUE THREAD

**Issue by Jan-NiklasB** [gotify/server#382]
**Is your feature request related to a problem? Please describe.**
Well, more or less.
I thought about requesting support for gotify in Rocket.Chat as push gateway, but for it to work
there must be an option to create an app, which is feed by one or more servers and sends the push to
multiple users / clients.

**Describe the solution you'd like**
An option to create a app (as admin), which has an app-token as already implemented, 
but also the option to put in a list of valid clients.
So if the server sends a request to the gotify gateway, it delivers the app-token and one or many destination-IDs.
So in fact, an option to create like a global app, which can message every user, and also an option for users to
subscribe to this app (like registering an phone / client with this app).

**Describe alternatives you've considered**
For this functionalíty there is IMO no other solution.

**Additional context**
Would be a nice feature to replace the need of proprietary services like google push services for open-source apps
and also would increase the overall security of the messengers by not providing potentially confidential information
 to the google push gateway.
 
 Feel free to ask if something is not clearly enough described.
 
 Anyway thanks already for creating this project!

**Comment by jmattheis** [comment]
See https://github.com/gotify/android/issues/45 and https://github.com/gotify/contrib/issues/5. You could use this plugin to have the wanted functionality https://github.com/eternal-flame-AD/gotify-broadcast
