### ISSUE TITLE
2.0.21 via Docker fails to initialize on arm64v8

### ISSUE THREAD

**Issue by shnizmuffin** [gotify/server#386]
**Can the issue be reproduced with the latest available release? (y/n)**

Yes.

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
  gotify:
    image: gotify/server:latest
    container_name: gotify
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'xxxxx'
      TZ: 'America/New_York'
    volumes:
      - ./gotify/data:/app/data
    ports:
      - 8282:80
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

I don't think this is the issue, but i'll include my configuration anyway.

```
    server {
        listen 443 ssl;
        server_name gotify.xxxxx.xxx;
        server_tokens off;

        ssl_certificate /etc/letsencrypt/live/gotify.xxxxx.xxx/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/gotify.xxxxx.xxx/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location / {
            proxy_pass http://xxx.xxx.x.xx:8282;
            proxy_http_version 1.1;

            # Ensuring it can use websockets
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto http;
            proxy_redirect     http:// $scheme://;

            # The proxy must preserve the host because gotify verifies the host with the origin
            # for WebSocket connections
            proxy_set_header   Host $http_host;

            # These sets the timeout so that the websocket can stay alive
            proxy_connect_timeout   7m;
            proxy_send_timeout      7m;
            proxy_read_timeout      7m;
        }
    }
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

`sudo docker-compose up -d`

**What did you expect to see?**

A gotify container running out of Docker.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

Gotify fails to initialize with an error message in the logs:

`standard_init_linux.go:211: exec user process caused "exec format error"`

I also tried versions 20.0.20 to 20.0.18. I have a sneaking suspicion that the image pulled down from Docker Hub is not the correct image for my architecture.

**Comment by jmattheis** [comment]
Yeah, only amd64 and arm7 are currently supported.

**Comment by shnizmuffin** [comment]
via Docker or at all?

**Comment by jmattheis** [comment]
It's not supported on our docker images. You can find a pre-built binary on https://github.com/gotify/server/releases/tag/v2.0.21 (linux-arm64).

**Comment by shnizmuffin** [comment]
Thanks for the clarification!
