### ISSUE TITLE
yaml.v3?

### ISSUE THREAD

**Issue by siredwin** [gotify/server#390]
I want to use my expertise to write more professional plugins for Gotify.
To do this right, I will need to have comments on the plugin config scheme for users.

I think this needs golang yaml v3 library and the ability to represent all nodes internally as `yaml.Node` or [`]yaml.Node`.

Are you planning to do this soon?
If not, please point me to the right place to start working on a contribution.
Thanks a lot for this great library

**Comment by jmattheis** [comment]
Nope, this is not planned. The version inside go.mod have to be increased and the import paths from the yaml package have to be adjusted (to v3).

**Comment by siredwin** [comment]
Ok. I will do it.
