### ISSUE TITLE
Changing port on windows and running on background

### ISSUE THREAD

**Issue by nandobarreto** [gotify/server#391]
Hey!
I'm trying to run gotify on the background of my pc (without the black window open), for this I tried 2 things:
1- run as a service
2 add on my task scheduler

both worked as intended, but it ignore the port change I made on the file config.yml is ignored (only runs on the port 80)
If I open regularly (prompt or just clicking) it'll use the port configuration.
There is anyway to do what I want?

btw Windows 10 here.

**Comment by jmattheis** [comment]
Try to set the workdir of the service to the folder containing the config file, or use environment variables.

**Comment by nandobarreto** [comment]
I manage to solve the problem, I put the config file on windows/system32 folder.
For some reason, when the taskmanager start the file, the app work if it is on this folder.
