### ISSUE TITLE
Is it possible to run gotify in subdomain and custom port like gotify.domain.com:8911?

### ISSUE THREAD

**Issue by arafatx** [gotify/server#398]
Sorry this is not an issue or bug but more on question / suggestion. I just found out about gotify today and this is an awesome project. My question is, is it possible to run gotify server as subdomain including a custom port like this:
 
gotify.mypublicdomain.com:81123

Actually I have a Directadmin installed on my system, by default, if I install gotify on top of Directadmin, it will also listen to my hostname on port 80 like this which I don't want:

server.mydomainserver.com

I read from one issue that static reference might be broken if I use subfolder or maybe using subdomain might have problem too? Any experience to share? If subdomain or subfolder are not recommended, then is it possible to change only listening port to 81123? I haven't seen any examples for the configuration how to change port either. I'm using nginx_apache (reverse proxy). Maybe someone could share a little best practice config to change the gotify port for nginx_apache reverse proxy? Thanks

**Comment by jmattheis** [comment]
Yes this should be perfectly fine. You can change the port via config -> https://gotify.net/docs/config

81123 is not a valid port, choose one between 1 and 65535

**Comment by Literorrery** [comment]
I can confirm I have this running on a custom port as a virtual host.
