### ISSUE TITLE
Question: How do I trigger stuff to happen on message recieve?

### ISSUE THREAD

**Issue by levaritie** [gotify/server#401]
I dont know GO wich doesnt help, BUT I have been using your software for a while its nice.
I would like to know if its possible to trigger a script to run when a notification is recieved with a specific tag.
the Senario is recieve a url link, the server curl's it.
There is a webserver that sends back the URL of a uploaded file that it gets to the users gotify token, wich I kinda wanted to use to automaticly download said file on a diffrent machine. 

I have bee looking throughe the plugin docs but it doesnt state that looking at the message content is possible.
seeing username, last use time etc is possible. so I was wondering if this is a option at all or is this a large modification that needs to happen?

Thanks for reading my question

**Comment by jmattheis** [comment]
Gotify exposes a websocket endpoint which you can use to get the stream of newly created messages, see f.ex. https://github.com/gotify/server/issues/255 

Plugin support for this currently doesn't exist, but there's an issue for it https://github.com/gotify/plugin-api/issues/3

**Comment by levaritie** [comment]
I got something something working, thanks for the refernces! 
that #255 was a good idea. though I do agree as stated [gotify/plugin-api#3](https://github.com/gotify/plugin-api/issues/3) in  it would be nice if it was possible to interact with the recieved message directly through the api, the android client can do this, sort of. 
Because you can add tags in the json file like action::someaction forexample, wich would be nice if you can build something around that wich doesnt require a diffrent infrastructure to be build, but at the same time the argument could be made that its just nice to have.

Thank you ^^

**Comment by jmattheis** [comment]
Alright, I'm closing this then, as your problem is fixed, and the plugin-api covers the rest (:.
