### ISSUE TITLE
receive notifications inside/outside home network

### ISSUE THREAD

**Issue by Ylawy** [gotify/server#404]
Hi all,

I'm using the latest Gotify version 2.0.21 behind Nginx proxy manager, and it works fine so far. However, I'm having a problem where I receive notifications only when I switch to a different network. Let's say I should receive a notification when my phone is connected to my home network, I will only see it once my phone connects to my mobile carrier for example.
I went to the chat and I was advised to check the env variables as I run Gotify in docker. I did and have included the following env hoping it would solve my problem but it didn't:
GOTIFY_SERVER_KEEPALIVEPERIODSECONDS | 0
GOTIFY_SERVER_SSL_ENABLED | false
GOTIFY_SERVER_SSL_REDIRECTTOHTTPS | true
GOTIFY_SERVER_STREAM_PINGPERIODSECONDS | 45

I read about websockets as I have the suspicion my phone loses the connection somehow but I couldn't find the fix to my problem.
Does anybody have a tip on how to solve this problem? What am I missing?

Android logs:
https://pastebin.com/6E27EyT1
Server logs:
https://pastebin.com/W3mkVFUD

Thank you!

**Comment by jmattheis** [comment]
Please add logs from gotify/server and gotify/android.

**Comment by Ylawy** [comment]
thanks for your response. just edited my first comment with logs included.

**Comment by jmattheis** [comment]
Do you use a reverse proxy?

**Comment by jmattheis** [comment]
This is likely related to https://github.com/gotify/android/issues/162 as the logs contain a lot "Network not connected".

**Comment by Ylawy** [comment]
yes, Nginx proxy manager as I assumed its necessary to receive message outside my home network.

**Comment by jmattheis** [comment]
I'll close this in favor of https://github.com/gotify/android/issues/162
