### ISSUE TITLE
Icons in sidebar?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [gotify/server#405]
- **Is your feature request related to a problem? Please describe.**

I like to  be able to identify items at a quick glance, rather than always have to read.

- **Describe the solution you'd like**

Icons in sidebar would do the trick. The same icons that the user adds, added to the left of the text.

Right now it's just plain ol' boring, text.  :)

- **Additional context**

Icons being the same size as the ones in for example, Organizr would  be good. Bonus points if  the sidebar can auto-close/expand the same way Organizr does as well.

**Comment by mateuscelio** [comment]
@jmattheis, can I take this issue?

**Comment by jmattheis** [comment]
@mateuscelio sure.
