### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by alexpcooper** [gotify/server#408]
**Is your feature request related to a problem? Please describe.**

Not related to a problem but, as a feature request, support for emoji characters would be really useful.

Messages involving emojis currently cause a 500 error from the server. if you use unicode (eg. "\U0001f47f", "U+1F600", etc.), HTML emoji (eg. "&#128512;" - not a surprise as the documentation said it wouldn't work, but I thought I'd try it anyway) then the values are printed our directly in the notification as they're sent. This is whether you use plain text or markdown.

Messages being sent via the Android app also fail when you include an emoji character and again print out the unicode / HTML version when you use those.

As far as I've so far been able to ascertain, there's no way to push an emoji into either the title or body of a notification.

**Describe the solution you'd like**

Just some sort of support so that notifications can include them. The [GitHub Flavored Markdown](https://github.github.com/gfm/) doesn't appear to offer it. I don't know what would be involved in providing support.

**Describe alternatives you've considered**

As described above.

**Additional context**

**Comment by jmattheis** [comment]
You can paste emoji directly into the message body.
```
jm@dyne ~/src/playground/gotify λ cat msg.json
{
    "message": "Hello 😀"
}
jm@dyne ~/src/playground/gotify λ cat msg.json| http POST ":8080/message?token=AjqsNwNNor7kw9N"
{
    "appid": 1,
    "date": "2021-04-19T17:17:15.045747318+02:00",
    "id": 49,
    "message": "Hello 😀",
    "priority": 0,
    "title": "aoeu"
}
```
![image](https://user-images.githubusercontent.com/14895212/115260642-7a6f3300-a122-11eb-9ee8-7e99a1b2468e.png)
