### ISSUE TITLE
Can post but can't get

### ISSUE THREAD

**Issue by Narcolapser** [gotify/server#409]
**Can the issue be reproduced with the latest available release? (y/n)**

Yes, I am running version 2.0.22@2021-04-16-18:16:19

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

I am using Ansible to configure the container, the yaml can be found [here](https://github.com/davestephens/ansible-nas/blob/master/roles/gotify/tasks/main.yml)
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
- [x] Treafik
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

Also using Ansible for this. 
[yaml](https://github.com/davestephens/ansible-nas/blob/master/roles/traefik/tasks/main.yml)
[toml](https://github.com/davestephens/ansible-nas/blob/master/roles/traefik/templates/traefik.toml)

</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [x] 3rd-party API call (Please include your code)

**What did you do?**

    curl "https://gotify.redacted.com/message?token=redacted" -F "title=Test" -F "message=tutorial"
    curl -X GET "https://gotify.redacted.com/message?token=redacted"

**What did you expect to see?**

first curl:

    {"id":19,"appid":3,"message":"tutorial","title":"Test","priority":0,"date":"2021-04-28T16:12:19.938555337Z"}

second curl:

    {"messages": [{"id":19,"appid":3,"message":"tutorial","title":"Test","priority":0,"date":"2021-04-28T16:12:19.938555337Z"}],"paging": "pagination stuff"}

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

first curl:

    {"id":19,"appid":3,"message":"tutorial","title":"Test","priority":0,"date":"2021-04-28T16:12:19.938555337Z"}

second curl:

    {"error":"Unauthorized","errorCode":401,"errorDescription":"you need to provide a valid access token or user credentials to access this api"}

I have also tried in python:

``` 
import requests

token = 'redacted'

headers = {'X-Gotify-Key':token}
url = 'https://gotify.redacted.com'
endpoint = '/message'
body = {"message": "Notification made with requests","priority": 2,"title": "Reqs!"}
r = requests.post(url+endpoint,data=body,headers=headers)
r = requests.get(url+endpoint, headers=headers)

```

the first request gets 201, the second gets 401. in both cases the request is identical say HTTP Method and payload. Neither of those things should affect authentication. This should be super straight forward so I'm not sure what I am doing wrong.

**Comment by jmattheis** [comment]
> A client is a device or application that can manage clients, messages and applications. However a client is not allowed to send messages.
> 
> An application is a device or application that only can send messages.

https://gotify.net/docs/

You can only send messages with an application token and can only read them with a client token.

**Comment by Narcolapser** [comment]
ooh. I understand now. Thank you for the clarification. I updated my python script and it works now.
