### ISSUE TITLE
Write log to physical file in container

### ISSUE THREAD

**Issue by ich777** [gotify/server#411]
Hi first of all thank you for Gotify!

**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [X] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm running Gotify in Docker on Unraid and use nginx with fail2ban integrated (SWAG from Linuxserver.io) in another container for reverse proxy.
My question is how can I get the log files from the Gotify container to make a bind mount in the nginx container to read the logs from Gotify for Fail2Ban?
Is there a option to write the log to a file that I'm missing?
What would be the best practice to do this?

Best,
Christoph

**Comment by jmattheis** [comment]
You can redirect the log output of the gotify binary inside docker.
```
$ touch gotify.log
$ docker run --rm -p 12345:80 -v $PWD/gotify.log:/app/gotify.log --entrypoint '' gotify/server:2.0.22 /bin/bash -c '/app/gotify-app | tee /app/gotify.log'
Starting Gotify version 2.0.22@2021-04-16-18:16:19
Started Listening for plain HTTP connection on :80

$ cat gotify.log
Starting Gotify version 2.0.22@2021-04-16-18:16:19
Started Listening for plain HTTP connection on :80

```

**Comment by ich777** [comment]
@jmattheis Thank you for the response. :)

Would it be not possible to integrate a Variable that does this automatically or at least create the log if it's set to true, the main reason because I'm asking is on Unraid you can't integrate this command easily within the so called "Docker Template Page" (something like Portainer but a little more slimmed down).

Again thank you for Gotify!

**Comment by najtin** [comment]
@ich777 you can create your own docker image of gotify. Something along the lines of
```
FROM gotify/server:2.0.22
ENTRYPOINT /bin/bash -c '/app/gotify-app | tee /app/gotify.log'
```

**Comment by ich777** [comment]
@najtin I know, I first thought about that but I always first ask the developer from the application itself if it is possible to integrate that directly in the "original" container with a variable or somehow... because I also like to use the "original" container instead of some third party container. :)

**Comment by jmattheis** [comment]
Adding log file support to gotify is kinda difficult, as it currently uses stdout println and not some kind of logging library.

**Comment by ich777** [comment]
@jmattheis Thank you for the response, than I have to customize the container a bit to fit my needs or at least the needs for Unraid. :)
