### ISSUE TITLE
Unable to setup SSL with Gotify

### ISSUE THREAD

**Issue by golyalpha** [gotify/server#412]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm connecting to Gotify with Haproxy configured for SSL passthrough. Have successfully setup multiple applications this way, and this is the first one I am having issues with.
Because I'm using SSL passthrough, and there is no frontend handling SSL termination for Gotify, I have enabled SSL within Gotify itself.
This is my startup command:
```
docker run -p 127.0.0.1:3000:80 -p 127.0.0.1:30443:443 -v /var/gotify/data:/home/rock64/gotify --restart always -d --name gotify \
  -e GOTIFY_SERVER_SSL_ENABLED=true \
  -e GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=true \
  -e GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=true \
  -e GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS='- my.domain.tld' \
  -e GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=false \
  gotify/server-arm64
```
Over HTTP, everything works fine, but fails when I try accessing it over HTTPS. (note: I have the correct domain name in the LETSENCRYPT_HOSTS envar)

**Any errors, logs, or other information that might help us identify your problem**
This is the error message from logs:
```
2021/05/15 09:19:52 http: TLS handshake error from 172.17.0.1:44500: Get "https://acme-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority
```
Subsequent HTTPS requests result in:
```
2021/05/15 09:28:41 http: TLS handshake error from 172.17.0.1:47730: acme/autocert: missing certificate
```

**Comment by jmattheis** [comment]
Gotify must be served on port 80 for letsencrypt to work.

> The HTTP-01 challenge can only be done on port 80. Allowing clients to specify arbitrary ports would make the challenge less secure, and so it is not allowed by the ACME standard.

https://letsencrypt.org/docs/challenge-types/#http-01-challenge

**Comment by golyalpha** [comment]
It is. The container is bound to 3000, but it's passed through Haproxy, which is bound to port 80

**Comment by golyalpha** [comment]
Gotify internally thinks it's on port 80, and it's externally available on port 80, the only place where you'd be able to use port 3000 to interact with Gotify is localhost.

**Comment by jmattheis** [comment]
Could you try manually adding the ca-certificates package:
```
docker run -p 127.0.0.1:3000:80 -p 127.0.0.1:30443:443 -v /var/gotify/data:/home/rock64/gotify --restart always -d --name gotify \
  -e GOTIFY_SERVER_SSL_ENABLED=true \
  -e GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=true \
  -e GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=true \
  -e GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS='- my.domain.tld' \
  -e GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=false \
  --entrypoint '' \
  gotify/server-arm64 sh -c "apt update && apt install -y ca-certificates && /app/gotify-app"
```

**Comment by golyalpha** [comment]
Okay, yep, the package wasn't installed. Installing it fixed the issue.

**Comment by GHRoss** [comment]
@golyalpha I'm interested in configuring Gotify with SSL. Is there any chance you have a write up of your config?

**Comment by golyalpha** [comment]
That depends on what's your frontend proxy. Mine was HAProxy - and I'm more comfortable having that running in SSL Passthrough mode. For that, my set up looks something like this:
```
frontend http
        bind :::80 v4v6
        use_backend gitea if { req.hdr('Host') -i gitea.example.com }
        use_backend gotify if { req.hdr('Host') -i gotify.example.com }
        default_backend lancache

frontend https
        bind :::443 v4v6
        option tcplog
        mode tcp
        tcp-request inspect-delay 5s
        tcp-request content accept if { req_ssl_hello_type 1 }
        use_backend gitea-ssl if { req.ssl_sni -i gitea.example.com }
        use_backend gotify-ssl if { req.ssl_sni -i gotify.example.com }
        default_backend lancache-ssl

backend gitea
        server master gitea:80

backend gitea-ssl
        mode tcp
        server master gitea:443 check

backend gotify
        server master gotify:3000

backend gotify-ssl
        mode tcp
        server master gotify:3443 check

backend lancache
        server master lancache:80

backend lancache-ssl
        mode tcp
        server master lancache:443 check
```

Note that the names in the backend sections (gotify/lanchace/gitea) should either be the server IPs, or should actually resolve to IPs that point to the relevant servers.

Also, if you're starting from scratch (as I assume you are), you should seriously consider if you actually need a frontend proxy. I use it, because I'm multiplexing multiple different services on a single publicly accessible IPv4, and having a frontend proxy allows me to direct connections coming in on that IP to the correct destinations.

If you're trying to run just Gotify, it might be worth it using the command as written by @jmattheis, and changing the ports to 80 and 443 (`-p 80:80 -p 443:443`)

If you really need a frontend proxy, I'd nowadays opt to go with nginx, as the configuration files are slightly more readable, and (more importantly) properly supported by `certbot`

**Comment by GHRoss** [comment]
> That depends on what's your frontend proxy. Mine was HAProxy - and I'm more comfortable having that running in SSL Passthrough mode. For that, my set up looks something like this:
> 
> ```
> frontend http
>         bind :::80 v4v6
>         use_backend gitea if { req.hdr('Host') -i gitea.example.com }
>         use_backend gotify if { req.hdr('Host') -i gotify.example.com }
>         default_backend lancache
> 
> frontend https
>         bind :::443 v4v6
>         option tcplog
>         mode tcp
>         tcp-request inspect-delay 5s
>         tcp-request content accept if { req_ssl_hello_type 1 }
>         use_backend gitea-ssl if { req.ssl_sni -i gitea.example.com }
>         use_backend gotify-ssl if { req.ssl_sni -i gotify.example.com }
>         default_backend lancache-ssl
> 
> backend gitea
>         server master gitea:80
> 
> backend gitea-ssl
>         mode tcp
>         server master gitea:443 check
> 
> backend gotify
>         server master gotify:3000
> 
> backend gotify-ssl
>         mode tcp
>         server master gotify:3443 check
> 
> backend lancache
>         server master lancache:80
> 
> backend lancache-ssl
>         mode tcp
>         server master lancache:443 check
> ```
> 
> Note that the names in the backend sections (gotify/lanchace/gitea) should either be the server IPs, or should actually resolve to IPs that point to the relevant servers.
> 
> Also, if you're starting from scratch (as I assume you are), you should seriously consider if you actually need a frontend proxy. I use it, because I'm multiplexing multiple different services on a single publicly accessible IPv4, and having a frontend proxy allows me to direct connections coming in on that IP to the correct destinations.
> 
> If you're trying to run just Gotify, it might be worth it using the command as written by @jmattheis, and changing the ports to 80 and 443 (`-p 80:80 -p 443:443`)
> 
> If you really need a frontend proxy, I'd nowadays opt to go with nginx, as the configuration files are slightly more readable, and (more importantly) properly supported by `certbot`

Wow, thanks for the quick reply!

Yeah, I won't be accessing this externally... So you reckon (`-p 80:80 -p 443:443`) with an SSL cert will do the trick?

**Comment by golyalpha** [comment]
If you're running the server on a publicly accessible IP, just replace the port maps from the mentioned command with those. The certbot integrated in Gotify will then get the cert on it's own.

**Comment by GHRoss** [comment]
> If you're running the server on a publicly accessible IP, just replace the port maps from the mentioned command with those. The certbot integrated in Gotify will then get the cert on it's own.

I think I'll have to sort the cert out manually or via some automation, thank you for your help!
