### ISSUE TITLE
Rocketchat integration

### ISSUE THREAD

**Issue by githubdeb** [gotify/server#413]
Hi Mattheis,

I'm working with Gotify as an alternative to Google and Apple notification services.
I use Rocketchat and Gotify for notifications. I think the Gotify server works well. However, one thing that I would need is to be able to interact with the server with more data at once. 
Are you considering on adding an option to import from a JSON or TXT file users and applications? If not, can we chat a liitle bit about this?

In my case, I want for every Rocketchat user to automatically create a user and and application in Gotify. After that I want to be able to extract the created tokens and use them with Rocketchat.
If you think this is not the place to talk about this topic, we can do a zoom meeting. Let me know what best works for you and I'll send you and email in private.

Thank you

Luke

**Comment by jmattheis** [comment]
Hi,

> Are you considering on adding an option to import from a JSON or TXT file users and applications? If not, can we chat a liitle bit about this?

No, but you can use the json api -> https://gotify.net/api-docs
