### ISSUE TITLE
Windows Defender and Virustotal False Positives

### ISSUE THREAD

**Issue by quiksilver2** [gotify/server#414]
Here ist the Virustotal link
eGambit Unsafe.AI_Score_100%
https://www.virustotal.com/gui/file/7385469c2b3ba0b2e7873d52ebb635405f0d31e885906d028c2d58d7b0ae22d9/detection
Windows Defender is alarming when opening exe.

**Comment by jmattheis** [comment]
Nothing I can do about this, it's most likely a false positive.
