### ISSUE TITLE
[Documentation] Websocket timeout for Apache reverse proxy probably wrong?

### ISSUE THREAD

**Issue by wischi-chr** [gotify/server#415]
**Setup**
- [x] Docker
- [x] Windows machine
- [x] Apache
- [x] WebUI

**What did you do?**
I set up gotify with docker (docker-compose) and apache as a reverse proxy according to the documentation
- Docker compose based on that: https://gotify.net/docs/install
- Apache vhost config based on that: https://gotify.net/docs/apache

It "almost" works, but the WebUI does show the following error every few seconds:
![image](https://user-images.githubusercontent.com/2495113/121813420-3c971280-cc6c-11eb-97c4-fe5af53e6f71.png)
The gotify log shows:
`gotify_1  | WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF`

**Workaround / Solution?**
Chrome Dev Tools showed that the websocket stream was closed after 5 seconds (the amount that was set according to the documentation) in the nginx reverse proxy configuration (https://gotify.net/docs/nginx) on the other hand I saw the following section:

```
# These sets the timeout so that the websocket can stay alive
proxy_connect_timeout   7m;
proxy_send_timeout      7m;
proxy_read_timeout      7m;
```

I'm not a nginx user myself but I assume the `7m` means seven minutes, so I changed my apache configuration to a timeout of seven minutes as well (420 seconds):
```
ProxyPass "/stream" ws://127.0.0.1:4365/stream retry=0 timeout=420
```

Now it looks like everything is working as expected. This should be changed (probably a copy-paste error?) in the documentation, or did I miss something else?

**Comment by jmattheis** [comment]
Good catch, | fixed the documentation. I can swear that this did work some time, but maybe I'm wrong (:. A better timeout would be 60s as the WebSocket sends pings every 45 seconds.
