### ISSUE TITLE
No basic auth for web frontend?

### ISSUE THREAD

**Issue by rucksman** [gotify/server#416]
I am new to Gotify and try to set it up in a docker container behind a reverse proxy (combination of https://hub.docker.com/r/jwilder/nginx-proxy and https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion). I want to protect the web frontend with basic auth.

The Gotify container comes up fine, the proxy asks for username and password as expected. After entering both I am greeted by the Gotify login screen. When using Web Dev tools in the browser, I can already see the first problem:
`GET https://gotify.mydomain.com/manifest.json 401`

More obvious problems occur after entering gotify credentials: I cannot log in because the basic auth window is constantly asking for username and password, and no matter how often I enter username and password, the basic auth windows does not go away.

What am I missing here?

Looking into the proxy logs I can see this:
`user "admin" was not found in "/etc/nginx/htpasswd/gotify.mydomain.com"`

"admin" is of course the username of the gotify user and not the username for basic auth. So why are both usernames mixed up?

**Comment by najtin** [comment]
Gotify itself uses BasicAuth. https://github.com/gotify/server/blob/9abe803cf89e9a5d9fc37026544fa3b5e905eedd/auth/authentication.go#L100

Since you already set a basic auth user and password when you first visit the proxy and you are on the same domain, the same basic-auth credentials of your proxy will be used by gotify.Thus, you must not use basic auth on your proxy (or have the same credentials as in gotify).

**Comment by najtin** [comment]
When you then try to log into gotify, you overwrite the basic auth credentials of the proxy, and the proxy wont let your request through and instead asks for your username and password.

**Comment by rucksman** [comment]
I see. Additional question: Out of curiosity I already tried to use the same credentials which worked fine for the web frontend. But how would I enter the url into the Android client? I tried https://username:password@gotify.mydomain.com, but this did not work (there was an error message but it was too long to read on my smartphone).

**Comment by najtin** [comment]
The error message would be very useful. I recommend to rename the issue to `additional layer of basic auth on reverse proxy` or something alike.

**Comment by rucksman** [comment]
Error message is:
Request to 'https://username:password@gotify.mydomain.com/version' failed with status code 401

**Comment by jmattheis** [comment]
Seems like the http client the android app uses doesn't support defining basic auth with https://username:password@gotify.mydomain.com

I'm closing this as gotify already uses basic auth itself, adding another service before gotify that also handles basic auth probably always leads to some weird errors :P.

**Comment by winny-** [comment]
Ran into this surprise - I read in the docs gotify sets up the default username and password, therefore should not be exposed to the web.  So I decided to set up nginx with basic auth in front.  Nginx happily authenticated my basic auth credential, but gotify always kicked me back to the login view.

This took maybe an hour longer than it should have to figure out oh yeah, gotify does something kind of surprising out of the box... uses basic auth... as an application server.

**Comment by jmattheis** [comment]
Gotify exposes an HTTP API, and I'd say it's common for such APIs to use basic auth.

**Comment by winny-** [comment]
Maybe the outcome could be to document how web ui authentication happens?  I did a quick search, didn't find discussion of using basic auth besides as an "alternative way to authenticate api clients".

![Screenshot_20230526_010744](https://github.com/gotify/server/assets/3893828/a5c4750f-0950-4487-ae31-c22cfb8c0595)

![Screenshot_20230526_011027](https://github.com/gotify/server/assets/3893828/748e766c-4a23-4a14-a98e-7825ac774a7f)

**Comment by winny-** [comment]
Just curious, how do you all set up gotify on a public internet connection if basic auth isn't usable to protect the install?

**Comment by rucksman** [comment]
Just for setup? Well, chances are very slim that somebody else will meet the small moment between starting the gotify container and yourself logging in. So I do not consider this as a problem. And you would certainly notice that.

For productive operation either live with it and take other precautions (fail2ban etc.) or try to put Authelia in front of it. I personally did not test the Authelia option. I have to say that I do not have any problem until now with exposing the Gotify frontend to the internet. Of course fail2ban is banning the bad guys for a lifetime. but surprisingly enough these are not too many.

**Comment by SweBarre** [comment]
You can also create a random password to be used for the default `admin` user on database creation.
https://gotify.net/docs/config

**Comment by winny-** [comment]
> You can also create a random password to be used for the default `admin` user on database creation. https://gotify.net/docs/config

That makes sense, thank you for helping me understand the docs better.

I do not think security through obscurity is a good approach @rucksman but thanks.

Now the next person who google's this will have a solution :).

**Comment by evlewt** [comment]
Hi. First of all thanks for this great application!

I would really like the Android application to support an additional basic authentication of a reverse proxy.
Most people may not see this as a requirement, but without this possibility you have to rely on the implementation of Gotify. I am not saying this is bad but a lot of CVEs have not been coded  intentionally. As Gotify outputs the Version number in the "unsecured" login page it would be very easy to identify vulnerable instances.
Yes, keep your applications up to date. But using an additional authentication layer can prevent even the shortest time of vulnerability.

**Comment by jmattheis** [comment]
TLS client verification (requested in https://github.com/gotify/android/issues/85) or using a VPN seems like a better solution than the extra basic auth layer.
