### ISSUE TITLE
About gotify application I have some question.

### ISSUE THREAD

**Issue by frocelu** [gotify/server#418]
Sorry about my poor English
What is the function "create application" used for?
When I connect gotify using the route "/stream" with specific client Token, I just get all push messages from all applications of this client.
Can I get push message of a specific application? Like use the route with parameter such as "/stream?token=<app token>"
Or I must filter messages in my client?

**Comment by jmattheis** [comment]
Hey, /stream will return messages from all clients, it is not possible to filter these on server side, you've to do this on client side.
