### ISSUE TITLE
[REST API] /message since parameter is counter intuitive

### ISSUE THREAD

**Issue by desbma** [gotify/server#421]
The `/message` route for the REST API has a `since` parameter, which is documented as:

> return all messages with an ID less than this value

https://gotify.net/api-docs#/message/getMessages

It works as documented, however I see two issues with the naming and behavior:
* its called `since`, so it should return messages with an ID strictly **superior** to the given value
* I think fetching messages after a given ID is a common use case, and the API does not offer that currently, so maybe another parameter should be added (maybe named `after` or `following` if maintaining compatibility with the current naming is required)

**Comment by jmattheis** [comment]
> its called since, so it should return messages with an ID strictly superior to the given value

Yeah, it's ambiguous, in the context that the api returns messages in descending order, "since" kinda makes sense.

I'd like a more expressive name, but it would break the api which I try to prevent.

> I think fetching messages after a given ID is a common use case

https://github.com/gotify/server/issues/329

**Comment by desbma** [comment]
I'm closing since you can't change the misleading wording, and there is already an issue for the second point.
