### ISSUE TITLE
File attachment

### ISSUE THREAD

**Issue by vvrein** [gotify/server#423]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a feature of file attachment. f.e. to attach some log file to notification.

**Describe the solution you'd like**
???
maybe this:
```bash
$ curl "https://push.example.de/message?token=<apptoken>" -F "title=my title" -F "message=my message" -F "priority=5" -T ./error.log
```

**Describe alternatives you've considered**
Attach whole log to notification's body.

pros:
  - simple flow, no modification needed

cons:
  - large, not formatted messages
  - no possibility to attach binary files, such as images

**Comment by jmattheis** [comment]
Hey @vvrein, this could be useful, but I try to keep gotify as simple as possible. I originally designed gotify for small alerts, thus, I rather not add this to gotify.

**Comment by vvrein** [comment]
Ok, thank you for feedback  :)

**Comment by monanto** [comment]
But at least should support image attachment
