### ISSUE TITLE
How do I change the username and password via command line not web UI?

### ISSUE THREAD

**Issue by arafatx** [gotify/server#425]
I'm creating a bash script to install gotify and change the default username and password automatically setup config file and with one time run, I will have fully working gotify server. Based on this documentation:

`https://gotify.net/docs/first-login`

It said that I can do this on the web UI but is there a way to do this without login into web UI ?

**Comment by jmattheis** [comment]
You can use the update current user password api, that is used inside the UI. https://gotify.net/api-docs#/user/updateCurrentUser
```
curl -X POST --header "Content-Type: application/json" --data '{"pass": "new_pass"}' -u admin:admin 'localhost:8080/current/user/password'
```
But the better way, would be to override the default user / pass via the configuration -> https://gotify.net/docs/config

**Comment by arafatx** [comment]
Thank you so much.
