### ISSUE TITLE
Creating a user can be done using a client token, but how can I create an application for that user?

### ISSUE THREAD

**Issue by Stitch10925** [gotify/server#426]
I have a tiny family website and would like to send a notification if the site is updated.

Since Gotify has no multicast support, I thought I would simply create the users, iterate through them, and send individual messages. So, to test this, I create a clientToken on my admin account. Using this token I am now able to create users on the fly, great, that's step one. However, how do I now create an application for each user so that I can send e message to their application?

There is no way for me to log in as the user since I do not have an application nor client token. The API also does not allow me to specify for which user to create an application. Do I really need to use basic authentication in this case to log in as the user before I can proceed?

**Comment by jmattheis** [comment]
You can create the application with basic authentication:
```
$ curl -H 'Content-type: application/json' --data-raw '{"name": "my app"}' -u admin:admin -X POST 'http://localhost:8080/application'
{"id":1,"token":"ArrWFngib2fU9_X","name":"my app","description":"","internal":false,"image":"static/defaultapp.png"}%
```
