### ISSUE TITLE
log file for fail2ban

### ISSUE THREAD

**Issue by takov751** [gotify/server#427]
Greetings. I couldn't find any proper way to get the logs into a separated file to set fail2ban on it, just in case. Is there a built in function for piping the logs to a file?

**Comment by jmattheis** [comment]
No, there is no built-in way, but you can pipe the output into a file and optionally use `tee`, if you still want stdout log.

**Comment by takov751** [comment]
Thank you for the quick answer. Yes, certainly I could do that, but it would be a great feature to for example given environmental variable would create a log file. Which later on could be used with static path, not running a `docker logs -f | tee` in the background.

**Comment by jmattheis** [comment]
If you're using docker, you can change the entry point like described in here https://github.com/gotify/server/issues/411#issuecomment-834117236

**Comment by takov751** [comment]
Thank you I did forgot about that. Much appreciated
