### ISSUE TITLE
JS subscribe over WS integration

### ISSUE THREAD

**Issue by artyomLisovskij** [gotify/server#430]
Can't find subscribe example for gotify. It's absolutely clear how to push and install gotify, all I want - subscribe to channel events in JS over WS. Can somebody provide an example?

**Comment by jmattheis** [comment]
the websocket ist listening on /stream.
```javascript
const ws = new WebSocket('wss://yourdomain.de/stream?token=Cxxxxxxxxxxxx');
ws.onerror = (e) => console.log('something went wrong', e);
ws.onclose = () => console.log('closed');
ws.onmessage = (e) => {
    const message = JSON.parse(e.data);
    console.log(message);
};
```
(the token must be a client token)

`message` has the structure as defined in https://gotify.net/api-docs#/message/streamMessages

**Comment by artyomLisovskij** [comment]
ty, posted example with docker-compose, python pusher, nginx with proxy of ws and simple html/js
https://github.com/artyomLisovskij/gotify-python-js-example
