### ISSUE TITLE
Problems with stream/websocket

### ISSUE THREAD

**Issue by rucksman** [gotify/server#432]
I use gotify together with Node-RED. Sending messages is no problem.

Now I wanted to see if I can use also incoming messages (sent for example from my Android smartphone). The API says that I can use "/stream". So I tried to set this up in Node-RED.

I took a "websocket in" node and entered the URL "wss://gotify.myserver.tld/stream?token=thisismytoken". First thing which leaves me irritated is that I am asked for a TLS configuration for this websocket client node. As I do not use self signed or local certificates (I use Letsencrypt on my gotify server) I left this blank. After deploying I get an error "Connection closed". Then I wanted to check whether it works in general and entered "https://gotify.myserver.tld/stream?token=thisismytoken" into a browser. The error I get: `{"error":"Unauthorized","errorCode":401,"errorDescription":"you need to provide a valid access token or user credentials to access this api"}`

What am I doing wrong? What would I have to do to receive messages in Node-RED via the endpoint "/stream"?

**Comment by jmattheis** [comment]
Hey, I've no experience with node-red but it is most likely related to node-red or the configuration as the /stream endpoint is used by the ui and android app. Make sure you are using a client token, these always start with a `C`.

**Comment by rucksman** [comment]
OK, so I created a new client token and tried a call to the endpoint as it is shown in the API documentation:
`curl -X GET "https://gotify.myserver.tld/stream?token=thisismyclienttoken"  -H  "accept: application/json"`
But this does not work either:
`Bad Request
{"error":"Bad Request","errorCode":400,"errorDescription":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}`

I am using gotify in a docker container behind a  nginx proxy by the way.

**Comment by rucksman** [comment]
Don't know what the problem was, but without exactly knowing why, it suddenly works in Node-RED.

**Comment by jmattheis** [comment]
> But this does not work either:
Bad Request {"error":"Bad Request","errorCode":400,"errorDescription":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}

You cannot use a web socket endpoint with just HTTP. That's what the error message is describing.

If everything is working, I'll close this issue.
