### ISSUE TITLE
No login from laptop browser possible

### ISSUE THREAD

**Issue by rucksman** [gotify/server#434]
My Gotify server (on docker) is running smoothly since quite some time. Also the Android app works fine.

All of a sudden I cannot log into Gotify from my laptop browser: "Login failed". I am very sure that I use the correct password and username. The app still works fine, but I cannot connect from any PC with any browser.

What could have gone wrong?

**Comment by rucksman** [comment]
Obviously the error message is misleading. Investigating the error a bit further, developer tools in the browser reveal the following (please take into account that I use Node-Red in parallel as mentioned [here](https://github.com/gotify/server/issues/432)):
```
POST XHR https://gotify.myserver.tld/client [HTTP/2.0 200 OK 331ms]
GET XHR https://gotify.myserver.tld/current/user [HTTP/2.0 200 OK 36ms]
GET https://gotify.myserver.tld/stream [HTTP/1.1 403 Forbidden 113ms]
GET XHR https://gotify.myserver.tld/application [HTTP/2.0 200 OK 42ms]
Firefox kann keine Verbindung zu dem Server unter wss://gotify.myserver.tld/stream?token=mytoken aufbauen.
WebSocket connection errored error { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 497598.69889999996, cancelBubble: false, originalTarget: WebSocket }  WebSocketStore.ts:27:12
GET XHR https://gotify.myserver.tld/current/user
```

So username and password are correct, but something goes wrong with the websocket (see the 403 when calling the endpoint /stream).

For some reason Chrome is already stopping after step 1 (POST XHR https://gotify.myserver.tld/client) with 403, only Firefox is able to go some steps further. Both browsers have all cookies and temp data cleared befor testing.

**Comment by jmattheis** [comment]
Show gotiyf/server log and paste your reverse proxy configuration if you are using one.

**Comment by rucksman** [comment]
I am really sorry for bothering you, but the mistake was of course on my side. You gave me the hint with "reverse proxy configuration". I added some lines to the proxy configuration for my Gotify vhost according to the Nginx documentation (https://nginx.org/en/docs/http/websocket.html) in order to make it work with Node-Red:
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
```

After removing these lines and restarting the container, Gotify works as expected. Now I have to see how I can get Node-Red to work with Gotify withput these line, but this should be of course not your problem. Sorry again ...

**Comment by jmattheis** [comment]
No problems, I'll close this issue then.
