### ISSUE TITLE
UNIQUE constraint failed: plugin_confs.token 

### ISSUE THREAD

**Issue by siredwin** [gotify/server#436]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [x] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

I am trying to run a custom plugin and I keep running into this error. Initially, I thought it was me but I removed any mention of Token and I was still getting the error. This only happens when I try to run any plugin. The server by itself is ok. I am using SQLite3

**What did you expect to see?**
I expect to see the server starting without errors. 

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

No plugin is available.

`(/home/x/Desktop/Zerver-Gotify/server/database/plugin.go:77)   `   
`[2021-09-24 09:18:55]  UNIQUE constraint failed: plugin_confs.token `
`Started Listening for plain HTTP connection on :8000`

**Comment by jmattheis** [comment]
Could you share your SQLite db + your plugin source code?

**Comment by siredwin** [comment]
I am having issues setting up the plugin build environments. I will post this as soon as I can test the other databases too.

**Comment by siredwin** [comment]
This error was caused because I still had a database running when I started a new gotify container. It was cleared by deleting the old database.
