### ISSUE TITLE
Wider message box

### ISSUE THREAD

**Issue by methatronc** [gotify/server#439]
Hello,

As I sometimes receive quite long requests on gotify it would be great if the messages could be widened.
Ideally, the message box would adapt to the width of the screen and use all available space.
Instead of this :
![image](https://user-images.githubusercontent.com/58328740/135428277-24689732-2e32-4f61-b219-8778a4a9b36d.png)
It would be awesome if we could get someting like this :
![image](https://user-images.githubusercontent.com/58328740/135428589-3d7efb51-e797-4337-953c-5c033b0481fe.png)
Thanks a lot for your work ! :)

**Comment by jmattheis** [comment]
This is by design. See f.ex https://ux.stackexchange.com/questions/3618/ideal-column-width-for-paragraphs-online

**Comment by methatronc** [comment]
I understand that you intended it, but if I wanted to change it, knowing that I am not fluent in Go, what would I need to change in the source if that is not too much trouble to ask ?

**Comment by jmattheis** [comment]
`maxWidth` in here:

https://github.com/gotify/server/blob/8affeced49f40a00ab4bd3a9d34a222ce8600ed4/ui/src/common/DefaultPage.tsx#L11-L12

**Comment by methatronc** [comment]
Thank you for your kind help, have a great day :)

**Comment by smjure** [comment]
Was looking for this too, still lot's of unused space. Would be nice to give e.g. 2 options, i.e. (1) default as is and (2) wide one.

![Image](https://github.com/user-attachments/assets/c01f3792-510e-4607-8338-31018e5a9e18)

**Comment by jmattheis** [comment]
@smjure see https://github.com/gotify/server/issues/744
