### ISSUE TITLE
Help setting up push notifications for Mastodon...

### ISSUE THREAD

**Issue by fcwoknhenuxdfiyv** [gotify/server#449]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I have set up a new Mastodon instance along with a Gotify server. I followed the instructions for setting up push notifications on the Fedilab wiki but I don't receive anything. I suspect that I need to point my Mastodon instance at the Gotify server but I can't find any documentation on how to do that.

**Comment by jmattheis** [comment]
Hey, I don't really know. There is no official support for this on the gotify side, thus, you should create an issue where you've found the tutorial on how to setup gotify with mastodon.
