### ISSUE TITLE
Auto-create a self-signed SSL certificate

### ISSUE THREAD

**Issue by archer007** [gotify/server#457]
**Is your feature request related to a problem? Please describe.**
I would like to be able to easily use SSL without having to set up LetsEncrypt (open ports or reverse proxy)

**Describe the solution you'd like**
I would like a self-signed cert to be automatically generated when SSL is enabled, LetsEncrypt not enabled, and path to cert not set

**Describe alternatives you've considered**
Other possible configurations (external SSL cert generation then import, LetsEncrypt) appear to be supported already

**Additional context**
This makes testing how Gotify works with SSL easier for people who don't want to sink time into a full SSL cert generation or LetsEncrypt setup, or lets them keep a self-signed cert if they want

**Comment by jmattheis** [comment]
Hey, creating self-signed certificates is just one command and there are already utilities that locally trust this certificate like https://github.com/FiloSottile/mkcert. I try to keep gotify simple, and I don't think this is useful to many users.
