### ISSUE TITLE
Flag to remove software version 

### ISSUE THREAD

**Issue by fbonalair** [gotify/server#458]
Is it possible to have a flag in the configuration or environment variable to remove the display of gotify version in the web UI of the serveur?

On a test serveur it is really handy to have the version. Though, on exposed environment I consider this as a security risk: if you're not up to date, it's a easy way for ill intent people to know your vulnerability.

**Comment by jmattheis** [comment]
See https://github.com/gotify/server/issues/292

**Comment by fbonalair** [comment]
Thank you
