### ISSUE TITLE
Connect Web App with WebSockets

### ISSUE THREAD

**Issue by AryanshMahato** [gotify/server#460]
Is there any way to connect to the server with websockets, I want to feed my application notifications from Gotify which will be created by our microservices.

Like if user is verified, User service will create a message(With REST). I want to connect my Web App(React.js) with Gotify Server with Socket so that user can see their account being verified.

Thanks in advance

**Comment by jmattheis** [comment]
Sure thing. You can do the same the web ui does. https://github.com/gotify/server/blob/master/ui/src/message/WebSocketStore.ts You can also have a look at the applications listed on https://github.com/gotify/contrib#tools--applications some also open a connection to the /stream endpoint.
