### ISSUE TITLE
two factor authentication for weblogin

### ISSUE THREAD

**Issue by elkas88** [gotify/server#461]
**Is your feature request related to a problem? Please describe.**
No, but security related. For a public facing application it would be nice to have the possibility to activate 2FA for users.

**Describe the solution you'd like**
A solution to be able to use the Google Authenticator, Microsoft Authenticator or any similar app which can scan a QR code and generate a time based code for the second factor.

**Additional context**
Another slider button in the "Edit user" dialog "enable 2fa" which when it's turned on generates the QR code and shows them between the button and the save button.

**Comment by jmattheis** [comment]
Yes, sounds like a good feature, but I think it rather should be outsourced via an external auth service #433, this way this doesn't have to be implemented inside gotify.

**Comment by JaneX8** [comment]
I would still like to see a simple TOTP implementation. I have a simple proxy in front with TLS termination and IP allowlisting but I still would want simple TOTP per app rather then implementing a full auth proxy.

To keep it simple and prevent things like this: https://github.com/gotify/android/issues/232.

**Comment by eternal-flame-AD** [comment]
I agree in 2025 this should be reconsidered, basic TOTP support should be built in. I will talk to Jannis in private about some roadmap meta discussions but currently can't commit to any timeline sorry.
