### ISSUE TITLE
Webui: markdown messages have visible whitespace

### ISSUE THREAD

**Issue by eikek** [gotify/server#463]
**Can the issue be reproduced with the latest available release? (y/n)**

I'm using 2.1.0 currently. But I think it still applies.

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x] Linux machine
- [ ] Windows machine

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

I send a message via a http client from my application using this structure:
```json
{ "title": "something",
  "message": "# some markdown …",
  "extras": { 
   "client::display": {
     "contentType":"text/markdown"
    }
  }
}
```
The markdown is correctly converted into HTML, but the CSS applied to it makes the white space "visible" via `white-space: pre-wrap`.

**What did you expect to see?**

I expected that whitespace is ignored when rendering markdown/html content.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

The whitespace makes the message look ugly when using lists or such elements. Here is a video:

https://user-images.githubusercontent.com/701128/149024889-31a60865-f8e8-4495-9000-213ca0889332.mp4

Hope that makes sense and I didn't miss something. Thank you so much for sharing gotify!

**Comment by jmattheis** [comment]
Good catch, this broke sometime I guess. In https://github.com/gotify/server/pull/180#issuecomment-477736997 it worked but with the current version it's buggy.

**Comment by eikek** [comment]
Awesome, thank you so much! ❤️
