### ISSUE TITLE
Consider using goreleaser to improve releases and build images

### ISSUE THREAD

**Issue by onedr0p** [gotify/server#464]
**Is your feature request related to a problem? Please describe.**

https://github.com/goreleaser/goreleaser

This is a very valuable tool for releasing Go projects, it's a single configuration file that is used to create Releases, Artifacts, Docker images and it can be used with github actions.

To get an idea, here's a few projects that use it, notice the releases page and he .goreleaser files in the root of the repos.

- https://github.com/maxmind/geoipupdate
- https://github.com/twpayne/chezmoi
- https://github.com/sachaos/viddy

**Comment by jmattheis** [comment]
I use goreleaser in [other projects](https://github.com/screego/server) but in Gotifys case, this wouldn't improve the build process. Gotify uses CGO and therefore requires a cross-compiler when compiling for different operating systems. Sure, there is probably a way to make this work with goreleaser, but it is most likely similar to what gotify already does, and thus, only adds extra complexity.
