### ISSUE TITLE
Delete All Button confirmation

### ISSUE THREAD

**Issue by okuzlu** [gotify/server#470]
**Describe the solution you'd like**
I clicked by mistake on the button "Delete all" where I wanted to hit the refresh Button. A confirmation or undo feature would be helpful before all messages are deleted.

**Comment by jmattheis** [comment]
I'm open to accept PRs for this.

**Comment by ritikBhandari** [comment]
So we want a modal dialogue sort of thing that warns the user before deleting the things right?

**Comment by jmattheis** [comment]
@ritikBhandari Yes, it should be similar to the "delete confirmation dialog" for applications. 
![image](https://user-images.githubusercontent.com/14895212/167678868-8f48bc6a-98e6-4dc0-823a-53d8c4957e82.png). The confirm dialog can be used https://github.com/gotify/server/blob/master/ui/src/common/ConfirmDialog.tsx

Adding this feature will break the e2e tests, in there the dialog has to be confirmed. see f.ex https://github.com/gotify/server/blob/master/ui/src/tests/message.test.ts#L221

**Comment by ritikBhandari** [comment]
Can I take up this issue?

**Comment by jmattheis** [comment]
@ritikBhandari yes
