### ISSUE TITLE
Channels/Topics wanted

### ISSUE THREAD

**Issue by trollkarlen** [gotify/server#472]
I want to be able to send messages on topics/channels so they get under its own "chat" in the frontends.
I use this for pushing messages from systems reporting issues/errors and then its good to handle the different systems in separate places so they are not mixed.

Maybe this is what the extras is for and the applications have to handle this ?
This seems like its difficult to coordinate between the apps if its not standardised ?

**Comment by jmattheis** [comment]
https://github.com/eternal-flame-AD/gotify-broadcast probably fits your description but Gotify doesn't support this natively as it would require a big rewrite, because it doesn't fit into the database schema.
