### ISSUE TITLE
Creating users and applications in mass

### ISSUE THREAD

**Issue by noammilner** [gotify/server#474]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [X] Linux native platform
- [ ] Windows native platform

Hello everyone, is there a way to mass create users & applications rather than doing it one after one?
I tried looking the solution online but couldn't find anything.
Gotify is installed on Ubuntu.

**Comment by BroderPeters** [comment]
Have not used gotify yet, but maybe you can use this API method in a script or something: https://gotify.github.io/api-docs/#/user/createUser

**Comment by noammilner** [comment]
Yup, that's a great solution.
