### ISSUE TITLE
Large push message causes the gotify web interface to not load messages

### ISSUE THREAD

**Issue by DecWebb** [gotify/server#475]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
One of my scripts outputs a push message to gotify, is formatted with markdown, it basically output full file paths which have moved, approximately 7000 lines. I moved alot of files which has caused the web interface to load the main interface but no messages 

Is there a way to send a command to delete all messages via command line?

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>docker compose</summary><br><pre>

  gotify:
    image: gotify/server
    container_name: gotify
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /opt/appdata/gotify-data:/app/data
    ports:
      - 8522:80
    restart: unless-stopped

</pre></details>

Appreciate any help

**Comment by SweBarre** [comment]
> Is there a way to send a command to delete all messages via command line?

You can use curl to delete **all** messages,
`curl -X DELETE https://<username>:<password>@<ip or dns name>/message`
so if your username is decwebb, pasword is 123456 and the gotify server is on dnsname gotify.domain.lan the command would be
`curl -X DELETE https://decwebb:123456@gotify.domain.lan/message`

**Comment by DecWebb** [comment]
That has fixed it, thanks for the help!
