### ISSUE TITLE
Customizable URL Base

### ISSUE THREAD

**Issue by drashna** [gotify/server#476]
**Is your feature request related to a problem? Please describe.**
Ability to set URL base (eg "/gotify") to allow for easier reverse proxying for web servers that aren't as easy to configure (See: IIS)

**Describe the solution you'd like**
Add support for customizing the url base. 

**Describe alternatives you've considered**

Entrenched into Windows and IIS, so not really.

**Comment by jmattheis** [comment]
I like to keep gotify simple, and as it should be possible to use gotify with IIS already I'll close this issue.

**Comment by drashna** [comment]
"should be" and "are" are two different things.  And I've always had issues with IIS' url rewriting if it uses a different subdirectory.  

Though, I will be the first to admit that i'm not an expert. 

That said, I'd greatly appreciate any assistance that can be provided to help get this running (eg, with IIS).

**Comment by jmattheis** [comment]
Have you tried something like https://grafana.com/tutorials/iis/ (only the iis config)

**Comment by drashna** [comment]
Yes.  Not their tutorial specifically, but I've been using IIS as a reverse proxy for ... quite a while.  Including for projects such as Emby, which require a more complicated setup.  

But if you notice, the grafana example shows a root dir path config, because sometimes that's needed for everything to work. Hence this request.
