### ISSUE TITLE
Ability to disable ui endpoints

### ISSUE THREAD

**Issue by wvalk** [gotify/server#478]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to disable the ui endpoints with a config property

**Describe the solution you'd like**
check the config for a "Ui enable" property before registering the ui endpoints.

**Comment by jmattheis** [comment]
What's your use-case?

**Comment by wvalk** [comment]
I want to use gotify as a true backend for sending notifications. 
Already have an existing work proccess within an organisation to send notifications with an extisting front end.

**Comment by jmattheis** [comment]
I don't think this is worth to implement, as having the ui doesn't create problems, you can also hide the ui via a reverse proxy.
