### ISSUE TITLE
Open a particular application with some metadata & having authy API compatibility

### ISSUE THREAD

**Issue by alexanderadam** [gotify/server#482]
I'm not quite sure whether this is possible and whether the issue title explains properly what this is about.
The general idea is to improve usability for 2FA.

**Is your feature request related to a problem? Please describe.**

So for 2FA there's usually a separate app and once users are prompted to type their second factor they might have to unlock their mobile phone, open the authenticator app, search the platform and then they can actually start to type or copy the code.
The company Twilio created a smart solution for making this workflow easier: [_Authy_](https://authy.com/).
[Authy's workflow goes as follows](https://authy.com/blog/authy-onetouch-simply-strong-security/):

> the application calls Authy when it wants 2FA assurance. Using Apple or Google, Authy sends a push notification to the user’s device, which improves the user’s experience by leading the user to the mobile app. This push notification does NOT contain the transaction details.

This workflow sounds great and clearly removes friction. But it relies on a proprietary uncontrollable service. Such as most push notification infrastructure besides gotify.
And this workflow obviously relies on push infrastructure anyway.

Therefore it would be nice to have a free solution to improve people's security.

**Describe the solution you'd like**

Without knowing any details about Android development I would guess that it would need these things:

1. The server must have an integration possibility so that services and applications can actually provoke this. The best way would probably to mimic [the Authy API](https://www.twilio.com/docs/authy/api#api-base-url), since other developers only would have to give the config option to change the API URL then.
2. a Gotify compatible Android app should have a possibility to open a particular entry from an MFA app (_maybe it would be good to discuss that with the folks from FOSS OTP projects, such as [andTOP](https://github.com/andOTP/andOTP), [FreeOTP+](https://github.com/helloworld1/FreeOTPPlus) and [Aegis](https://github.com/beemdevelopment/Aegis)_). I'm not quite sure how video players declare that they are capable of opening videos or certain URLs. Maybe something similar would work here too (_i.e. there's already something to create a new entry in an OTP app with `otpauth://totp/some_email_provider` — see also [andOTP PR 393](https://github.com/andOTP/andOTP/pull/393)_).

**Additional context**

I'm fully aware that this is a lot to ask but improving security and its usability for people believing in free software is a probably  worth a try.

**PS:** Thank you so much for gotify :raised_hands:

**Comment by jmattheis** [comment]
I try to keep gotify as simple as possible, so I don't think this is in scope to natively support this in gotify. You could already send a push notification with a link inside which proves you own your second factor, tho you need a separate service that allows to create such tokens/urls.

**Comment by alexanderadam** [comment]
Okay, so this means this issue should be closed since it won't be implemented?
