### ISSUE TITLE
Make default images configurable by app

### ISSUE THREAD

**Issue by fdw** [gotify/server#483]
**Is your feature request related to a problem? Please describe.**
If I get a lot of notifications from different apps, they all look similar thanks to the same default image being used.

**Describe the solution you'd like**
If notification from different apps would use different default images (maybe just a different color), that would help parsing the messages.

**Describe alternatives you've considered**
I can already filter by using the sidebar. But then, the default image is useless as it doesn't add any information to the notification.

**Comment by jmattheis** [comment]
You can upload a custom image for each application.
![image](https://user-images.githubusercontent.com/14895212/167295607-5c4758ba-e81e-46bf-8385-9bd8dc34941d.png)

**Comment by fdw** [comment]
Awesome, thank you! 🙂
I had never really understood that button...
