### ISSUE TITLE
Add a search bar/filter for notifications

### ISSUE THREAD

**Issue by fdw** [gotify/server#484]
**Is your feature request related to a problem? Please describe.**
I get a lot of similar notifications. If I'm searching whether something specific happened (or to find related notifications), I need to read all of them carefully, which is not as easy as it could be.

**Describe the solution you'd like**
A small filter bar in the web UI that makes not matching notifications invisible would help a lot to find specific notifications.

**Describe alternatives you've considered**
I can't find any, sorry.

**Comment by jmattheis** [comment]
duplicate #236

**Comment by fdw** [comment]
Sorry! I did look through the open issues, but somehow I missed that
