### ISSUE TITLE
`server.port` from `config.yml` is ignored

### ISSUE THREAD

**Issue by huuff** [gotify/server#485]
**Can the issue be reproduced with the latest available release? (y/n)**
y

**Which one is the environment gotify server is running in?**
- [ x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Create a `config.yml` such as:

```yaml
server:
  port: 8080
```

Run the application with `docker run --rm -v $PWD/config.yml:/etc/gotify/config.yml gotify/server`

**What did you expect to see?**
```
Started Listening for plain HTTP connection on :8080
```

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
```
Started Listening for plain HTTP connection on :80
```

**Comment by jmattheis** [comment]
Env variables take precedent over the config.yml, in the Dockerfile GOTIFY_SERVER_PORT is set. https://github.com/gotify/server/blob/master/docker/Dockerfile#L2

```
$ docker run --rm -e GOTIFY_SERVER_PORT=8080 gotify/server:latest
Starting Gotify version 2.1.4@2022-01-12-18:16:17
Started Listening for plain HTTP connection on :8080
```

**Comment by huuff** [comment]
Okay, so the solution is to just remove the env var...

```
docker run --rm -v $PWD/config.yml:/etc/gotify/config.yml -e GOTIFY_SERVER_PORT="" gotify/server
```

Thanks for the quick response
