### ISSUE TITLE
problem with all aps refresh

### ISSUE THREAD

**Issue by lukjod** [gotify/server#486]
**Can the issue be reproduced with the latest available release? (y/n)**

Yes

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

Yours server gotify1 as test env

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ x] WebUI
- [ ] gotify-cli
- [ x] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

**What did you expect to see?**

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
When i try to refresh all apps tab i can't see any message but if I choose to refresh separate apps it working well
![Screenshot_20220519-070035_Gotify](https://user-images.githubusercontent.com/1781446/169211707-1efc6a7f-527a-45d4-bc78-64d6107b4387.jpg)
![Screenshot_20220519-070101_Gotify](https://user-images.githubusercontent.com/1781446/169211711-02e17ac0-7655-4181-bd2a-b48649541931.jpg)

**Comment by jmattheis** [comment]
Could you attach the logs of gotify/android?

**Comment by jmattheis** [comment]
Could you add the gotify/server logs? Looks like the app cannot connect to it or it somehow fails.

**Comment by lukjod** [comment]
> Could you add the gotify/server logs? Looks like the app cannot connect to it or it somehow fails.

I use Yours https://gotify1.unifiedpush.org/
Can I get logs from there?

**Comment by jmattheis** [comment]
Unified pushed is unaffiliated with gotify. Looks like connection errors, but they seem to origin from the server.

**Comment by lukjod** [comment]
> Unified pushed is unaffiliated with gotify. Looks like connection errors, but they seem to originate from the server.

Ok will try to setup my owner docker gotify server on qnap x64 and see if it help

**Comment by lukjod** [comment]
all ok with my own server so it was server based issue
