### ISSUE TITLE
Add emoji markup 

### ISSUE THREAD

**Issue by JulianKropp** [gotify/server#488]
At the moment emojis aren´t displayed. Even if I use the text/markdown setting.
For cooler customization, it would be nice to add emojis to gotify push messages.

Here is a list of markdown emojis: https://gist.github.com/rxaviers/7360908

**Comment by JulianKropp** [comment]
Ah I didn't know. But still it would be nice to use emoji markup. Like discord does. That would simplify some situations.

For example:
I'm using crowdsec to protect my server. Every time someone does something he isn't supposed to I get a notification with the IP address and the country code. So this country code can be used to easily create a flag like this: `:flag_gb:` -> :flag_gb:

**Comment by jmattheis** [comment]
You can do the same with unicode flags. https://dev.to/jorik/country-code-to-flag-emoji-a21
I'm closing this, because I don't think this is worth the development / maintenance effort.
