### ISSUE TITLE
Combined version and health call in API

### ISSUE THREAD

**Issue by JapCLoN** [gotify/server#493]
**Describe the solution you'd like**
Combined version and health call in API. Right now doing 2 calls to get both info, which is 1 to many imo. Would you consider adding either to any of them, maybe by including a flag to get it included.

Always trying to cut down on calls in this one that could easily be cutted down.

**Comment by jmattheis** [comment]
Hey, I don't think this is worth the dev effort. Both calls aren't expensive, so doing two calls shouldn't cause any problems.
