### ISSUE TITLE
Websocket connection issue, only on client

### ISSUE THREAD

**Issue by Eviepayne** [gotify/server#496]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
sudo docker run \
    -p 52526:80 \
    -v /share/Docker/gotify:/app/data \
    gotify/server
```
</details>

**Do you have a reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presence of a reverse proxy)**
- [ ] None
- [ ] Nginx
- [x] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>
I had to use <Location> because I have a few sub directories I use reverse proxies for.

```
<IfModule mod_ssl.c>
<VirtualHost *:443>

    ServerName # redacted #

    ServerAdmin # redacted # 
    DocumentRoot # redacted #

    # SSL certs

    # redacted #
    
    ProxyPreserveHost on
    Keepalive on

<Location # redacted #>
    RequestHeader set X-Forwarded-Prefix # redacted #
    RequestHeader set X-Forwarded-Proto $scheme
    RequestHeader set Host # redacted #
    ProxyPass # redacted #
    ProxyPassReverse # redacted #
</Location>

<Location # redacted #>
    RequestHeader set X-Forwarded-Prefix # redacted #
    RequestHeader set X-Forwarded-Proto https
        ProxyPass # redacted #
        ProxyPassReverse # redacted #
    Require all granted
    Options none
</Location>

<Location /gotify/>
    ProxyPass http://10.0.0.15:52526/ retry=0 timeout=60
    ProxyPassReverse "http://10.0.0.15:52526/"
</Location>

<Location /gotify/stream/>
        ProxyPass ws://10.0.0.15:52526/stream retry=0 timeout=60
</Location>

    RewriteEngine  on
    
    RewriteCond %{HTTP:Upgrade} =websocket
    RewriteRule /gotify/stream(.*) ws://10.0.0.15:52526/stream$1 [P,L]

</VirtualHost>
</IfModule>
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
I refresh the page

**What did you expect to see?**
No errors in the dev console

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

In the client (Web UI) I see
`WebSocket connection to 'wss://# redacted #/gotify/stream?token=# redacted #' failed: `

On the server, there are no errors with the upgrade header. I resolved that, but the client still has issues.
![image](https://user-images.githubusercontent.com/59463208/178547199-73ffc455-45f0-41e3-8a15-fdd9169dc574.png)

**Comment by Eviepayne** [comment]
I tried that earlier but no avail.
I have the console log here:
[websocket1657653229816.log](https://github.com/gotify/server/files/9096146/websocket1657653229816.log)

**Comment by jmattheis** [comment]
For me, your config works. With what status code does the web socket request fail? Could you make a screenshot of your console, I think there is some info missing in the text log.

**Comment by Eviepayne** [comment]
Carefully redacted sensitive info.
![image](https://user-images.githubusercontent.com/59463208/178581694-a7227429-94d1-482f-92f0-82f1261d4e7e.png)
the event json:
![image](https://user-images.githubusercontent.com/59463208/178582095-ff7448b5-ad20-4b0b-a5d9-a17b09e3ccb1.png)

**Comment by jmattheis** [comment]
Could you try opening this in Firefox, chromium based browsers don't show the status code of failed websocket requests. Any log regarding the websocket requests inside gotify/server?
Could you try removing the Rewrite\* statements and using
```
    <Location /gotify/stream>
```
without the trailing slash.

**Comment by Eviepayne** [comment]
(After removing the rewrite rules and no trailing slash)
The firefox console:
![image](https://user-images.githubusercontent.com/59463208/178583552-81b5cb90-af5d-4faf-86c9-b0f0a3c12c90.png)
Gotify logs:
![image](https://user-images.githubusercontent.com/59463208/178583801-64984359-7f55-473a-af0f-cf88f96bec00.png)

**Comment by jmattheis** [comment]
This isn't a response from Gotify. Gotify will always return errors formatted as JSON with the header "Content-Type: application/json". Most likely, there is some Apache config interfering with the gotify one, or maybe the module mod_proxy_wstunnel isn't activated.

If you want further support on this, provide me a full config which allows me to reproduce the issue, preferably with docker.

**Comment by Eviepayne** [comment]
> mod_proxy_wstunnel isn't activated.

That was it. Thanks, I didn't notice that was off.
