### ISSUE TITLE
websocket connection problem

### ISSUE THREAD

**Issue by david6228** [gotify/server#499]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [ ] Linux machine
- [* ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [* ] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [* ] 3rd-party API call (Please include your code)

**What did you do?**
Server:  Gotify version 2.1.4   no reverse proxy
Client:   ActionScript 3 WebSocket Client
This is an AS3 implementation of a client library of the WebSocket protocol, as specified in the RFC6455 standard.
https://github.com/theturtle32/AS3WebSocket

Code:
var websocket:WebSocket = new WebSocket("ws://localhost:80/stream?token=CffZ9-MUntzNxGn", "*", "");
websocket.addEventListener(WebSocketEvent.CLOSED, handleWebSocketClosed);
websocket.addEventListener(WebSocketEvent.OPEN, handleWebSocketOpen);
websocket.addEventListener(WebSocketEvent.MESSAGE, handleWebSocketMessage);
websocket.addEventListener(WebSocketErrorEvent.CONNECTION_FAIL, handleConnectionFail);
websocket.connect();

function handleWebSocketOpen(event):void {
  	trace("Connected");
}

function handleWebSocketClosed(event):void {
  	trace("Disconnected");
}

function handleConnectionFail(event):void {
	statusDisplay.appendText("Connection Failure\n");
  	trace("Connection Failure: " + event.text);
}

function handleWebSocketMessage(event):void {
	//trace("handleWebSocketMessage "+event.message.utf8Data);
  	if (event.message.type === WebSocketMessage.TYPE_UTF8) {  
    		trace("a Got message: " + event.message.utf8Data);
		var r =com.adobe.serialization.json.JSON.decode(event.message.utf8Data);  trace(r[0]);

		//statusDisplay.text=event.message.utf8Data;
		//statusDisplay.text+=event.message.utf8Data;
  	}
  	else if (event.message.type === WebSocketMessage.TYPE_BINARY) {
    		//trace("Got binary message of length " + event.message.binaryData);
 	}
}

"ws://localhost:80/stream?token=CffZ9-MUntzNxGn"   notifier both successfully use javacript and perl client.

**What did you expect to see?**
Server :
Starting Gotify version 2.1.4@2022-01-12-18:16:17
[GIN] 2022/07/27 - 11:52:43 |[97;42m 200 [0m|      1.9531ms |       127.0.0.1
|[97;44m GET     [0m "/client"
[GIN] 2022/07/27 - 11:53:32 |[97;42m 200 [0m|       976.5µs |             ::1
|[97;44m GET     [0m "/stream?token=[masked]"
WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF

Client:
Connection Failure: The server can not respond in any of our requested protocols
Disconnected

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

**Comment by jmattheis** [comment]
> "ws://localhost:80/stream?token=CffZ9-MUntzNxGn" notifier both successfully use javacript and perl client.

What does this mean? Have you tried using a different language to connect to the websocket and there it works? Does the gotify ui work?

**Comment by david6228** [comment]
May be it's the protocol problem?
becasue ass3websocket only support Websocket RFC6455.

https://github.com/theturtle32/AS3WebSocket
ActionScript 3 WebSocket Client
This is an AS3 implementation of a client library of the WebSocket protocol, as specified in the RFC6455 standard.
Explanation
THIS CLIENT WILL NOT WORK with draft-75 or draft-76/-00 servers that are deployed on the internet. It is only for the most recent RFC6455 standard.

**Comment by jmattheis** [comment]
Dunno, the websocket library gotify uses also supports RFC6455, but this sounds like general coding support, so I'll close this as there is no issue with gotify.
