### ISSUE TITLE
Updated container images

### ISSUE THREAD

**Issue by SweBarre** [gotify/server#501]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [ ] Linux native platform
- [ ] Windows native platform
- [x] Kubernetes 

**Describe your problem**
According to the [documentation](https://gotify.net/docs/install) the latest version of gotify available as container image is version 2.1.4.
This is also confirmed as the latest version at [docker hub](https://hub.docker.com/r/gotify/server/tags?page=1) is 2.1.4

Are the other repositories available for gotify images or should I build them myself?

Thanks in advance

**Comment by jmattheis** [comment]
> Are the other repositories available for gotify images

you can use the github registry to download the gotify server images, see https://gotify.net/docs/install

there are no other docker images for gotify

> should I build them myself

Don't know what you are trying to archive, but you can do that too.
