### ISSUE TITLE
Single \n is ignored on web UI  and \\n results in "invalid character '\\n' in string literal".

### ISSUE THREAD

**Issue by nightcore500** [gotify/server#502]
**Can the issue be reproduced with the latest available release? (y)**

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x] Linux machine
- [ ] Windows machine

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [x] 3rd-party API call (Please include your code)

I use librenms to monitor some of my services and would like to use gotify for major alerts. I added another alert transport in librenms for this purpose. Configured as follows:
Transport type: API
API Method: POST
API URL: http://10.15.1.41/message
Options: token=XXXXXXXXX
headers: Content-Type=application/json
body: 
```
{
  "title" : "{{ $title }}",
  "message" : "{{ $msg }}",
  "priority" : 5,
  "extras" : {
    "client::display": {
      "contentType": "text/markdown"
    }
  }
}
```

If I now create a template which uses librenms to fill $msg and use new lines within the template this leads to a 400 "invalid character \\n in string literal". This results in the following json which is sent to gotify:
```
{ 
  "title": "Corerouter MAC Spoof erkannt ", 
  "message": "Host: srv-monitoring [10.15.1.61]
Status: critical
Zeitstempel: 2022-08-11 17:57:37", 
  "priority": 5, 
  "extras": { 
    "client::display": { 
      "contentType": "text/markdown" 
    } 
  } 
}
```

In addition, it is necessary if I do not use new lines within the template but work with \n that I have to specify \n twice per line so that a new line is really created on Web UI. With a single \n per line this is simply ignored. However, gotify's Android App correctly displays a single \n.

**Comment by jmattheis** [comment]
JSON does not support a literal line break, you need to use `\n`. The webapp and android app use different markdown specifications, see https://gotify.net/docs/msgextras#contenttype

**Comment by nightcore500** [comment]
Thank you for your reply. Okay, that explains the error message on a line break.
But the behavior with a single \n is not normal or? If I specify a single \n per line, I correctly see a line break in the app. In the web ui, however, not. There the text is simply displayed one after the other.

**Comment by jmattheis** [comment]
Yes, as said, the app webapp and android use different markdown specifications in GitHub flavored Markdown you need a double line break and in commonmark you need only one.
