### ISSUE TITLE
SSL cert timeout

### ISSUE THREAD

**Issue by polizz** [gotify/server#506]
**Have you read the documentation?**
- [x ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Android app this morning won't login. Web browser on same phone logs in fine as well as separate machine and reports that the current cert is valid until Nov. 2022.

**Any errors, logs, or other information that might help us identify your problem**

<details><summary>gotify client log</summary><br><pre>

at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:713)
	... 46 more
Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
</pre></details>

I've tried reinstalling the app as well clearing the cache.

**Comment by jmattheis** [comment]
This is probably something with your phone, maybe the time isn't synced, or something else related to the validation of the certificate.
