### ISSUE TITLE
Server 2.1.6 pre-build requires glibc >= 2.31 / Debian 10 (oldstable) not supported anymore

### ISSUE THREAD

**Issue by pm-pm** [gotify/server#509]
Hello,

thanks for the new Version. :-)

You should **emphasise** that Debian 10 (oldstable glibc 2.28) is not supported anymore with pre-build binaries.
Debian 11 is needed (glibc 2.31).

You only should make this more clear to user. ;-)

Thanks
pm-pm

**Comment by jmattheis** [comment]
Hey, I actually thought that debian buster would be EOL next month, but there will be LTS. So I'll release a new gotify version built with glibc 2.28.

**Comment by jmattheis** [comment]
2.28 is supported in the latest version. I don't think we have to list every distro that isn't supported anymore, because there are just too many.

**Comment by pm-pm** [comment]
Thank you for your understanding.
Surely we don't have to list every distribution, but Debian is quite important ;-)
