### ISSUE TITLE
Crashes on plugin usage

### ISSUE THREAD

**Issue by TheLastProject** [gotify/server#510]
First off, thank you for making Gotify, it's a great tool :)

Sadly, when using gotify-smtp 2.1.5 with Gotify 2.1.6 or 2.1.7, Gotify crashes on launch.

I have attached the Gotify 2.1.7 crash logs.

**Can the issue be reproduced with the latest available release? (y/n)**
Yes

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>
Portainer with following config for Gotify:

```
Image 	gotify/server:latest@sha256:f8b073a592b66eb1016ebd83ce019f1fb054b0ccf9fc77625cf4553d7bc39849
CMD 	
ENTRYPOINT 	./gotify-app
ENV 	
- GOTIFY_SERVER_PORT 	80
- PATH 	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy

**What did you do?**
Update Gotify beyond 2.1.5 without updating a plugin built for 2.1.5.

**What did you expect to see?**
Either Gotify exiting with a clear error message or running without the plugin enabled.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
Crash, see https://github.com/tystuyfzand/gotify-smtp/issues/6#issuecomment-1242976641

**Comment by jmattheis** [comment]
Gotify plugins are built for a specific version, so the plugin has to be rebuilt for gotify/server v2.1.7.

**Comment by TheLastProject** [comment]
Well, yes. That's what I already said in the issue.

My point is mostly that Gotify crashes very ungracefully without any useful info for end-users, making me spend hours hunting this down.

Even if the plugin isn't compatible, crashing without any clear explanation that it's plugin-related isn't the best fallback behaviour.

**Comment by TheLastProject** [comment]
I think that would be a nice improvement, as it'd point directly at the broken plugin.

I guess the whole crash log after that is necessary to know why it crashed.

So I guess I understand your "invalid" response now too :)

**Comment by jmattheis** [comment]
Yeah, normally it is possible to catch errors in go, but this specific error is fatal.
