### ISSUE TITLE
App Authentication.

### ISSUE THREAD

**Issue by zimbres** [gotify/server#512]
This is a nice and useful tool, I see two opportunities of improvement.

Pass the token in the query string exposes it on the network, so its not recommended.

Using the X-Gotify-Key in the header avoid its exposure, but several tools, Grafana for example, has predefined way to authenticate and it is using "Authorization" header.

Thanks.

**Comment by schoerg** [comment]
>Pass the token in the query string exposes it on the network, so its not recommended.

only if used unencrypted

**Comment by zimbres** [comment]
No sure, for example, in a proxy server, its possible to see any url called, even if is https.

**Comment by mateuscelio** [comment]
@jmattheis  I can implement this if it isn't in development yet. So the ideia is try to retrieve the token from  headers `Authorization` and `X-Gotify-Key` and from the query parameter as well, right?

**Comment by jmattheis** [comment]
@mateuscelio yes

**Comment by mateuscelio** [comment]
Ok, working on it
