### ISSUE TITLE
need to complete the example workflow

### ISSUE THREAD

**Issue by JustinWebDev** [gotify/server#514]
**Have you read the documentation?**
- [X ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [ ] Linux native platform
- [X ] Windows native platform

**Describe your problem**
The docs [intro](https://gotify.net/docs/) shows the model of app and client.  The [push msg page](https://gotify.net/docs/pushmsg) shows an example of how to send a msg, which I successfully did (I see it in the web UI).  However, none of the examples show how a client receives the msg.  Gotify server gets the message, but how does the client view the msg?

So, I do need an answer to this question, but the documentation also needs to describe and exemplify this.  Did I overlook this info?

**Comment by jmattheis** [comment]
The Android app & the WebUI already use the endpoint for getting instant updates when a new message is pushed. They open a websocket connection to [/stream](https://gotify.net/api-docs#/message/streamMessages). Related https://github.com/gotify/server/issues/255

The endpoint requires authentication with a client token.

**Comment by JustinWebDev** [comment]
I'm struggling with this.  I created an app and user using the webUI.  Any API call (even /stream) gives 401 because they all require authentication.  How do I authenticate?  I authenticated as a user in Swagger but the example URL (http://localhost/application) doesn't show the user applied.  Using the app token shows in the URL but still 401.

Let's say I have Gotify running, with an app and user defined.  The app has created messages.  What is the minimum info the client needs to read a message?

**Comment by jmattheis** [comment]
Show your code, I cannot work with "it doesn't work" without concrete explanation of what you are doing.
```
$ curl -d '{"name": "cool app"}' -H "content-type: application/json" -u admin:admin -X POST localhost:80/application
{"id":2,"token":"Auq23bqYcM65Oe0","name":"cool app","description":"","internal":false,"image":"static/defaultapp.png"}%
$ curl "http://localhost:80/message?token=Auq23bqYcM65Oe0" -F "message=my message"
{"id":1,"appid":2,"message":"my message","title":"cool app","priority":0,"date":"2022-10-06T07:20:13.904516428Z"}%
$ curl -u admin:admin "http://localhost:80/message"
{"paging":{"size":1,"since":0,"limit":100},"messages":[{"id":1,"appid":2,"message":"my message","title":"cool app","priority":0,"date":"2022-10-06T07:20:13.904516428Z"}]}%
$ curl -d '{"name": "cool client"}' -H "content-type: application/json" -u admin:admin -X POST localhost:80/client
{"id":2,"token":"Ch9AY8OqXPQ2OZe","name":"cool client"}%
jm@dyne ~ λ wscat -c "ws://localhost:80/stream?token=Ch9AY8OqXPQ2OZe"
Connected (press CTRL+C to quit)
< {"id":2,"appid":2,"message":"my message","title":"cool app","priority":0,"date":"2022-10-06T07:22:06.673960302Z"}
```

**Comment by JustinWebDev** [comment]
Thank you for the workflow calls - very helpful.  I did say a bit more than just 'it doesn't work'  ;-).  I did ask some specific questions, which your reply does show how to authenticate using curl.

I was just trying to use the documentation.  Examples ...

For message get message, Swagger shows these two calls should work:
`http://localhost/message?limit=100`
and
`curl -X 'GET' 'http://localhost/message?limit=100' -H 'accept: application/json' -H 'authorization: Basic YWRtaW46YWRtaW4='`
but neither do.
I even tried:
`http://admin:admin@localhost:80/message?limit=100`
but again get 401.

For message get /stream, Swagger shows:
`http://localhost/stream`
and
`curl -X 'GET' 'http://localhost/stream' -H 'accept: application/json' -H 'authorization: Basic YWRtaW46YWRtaW4='`
but those doesn't work, either.

Hopefully, tomorrow I'll have more time to try some more things.

**Comment by JustinWebDev** [comment]
I got some calls working.  It would be good to review the Swagger documentation, because the curl statements are not correct, and the authorization methods are not consistent (all methods don't work for all calls), and the responses don't seem to match actual.  And it would be nice to clarify for each call which person (client or app) or which token type applies.

 Thanks for the help.

**Comment by jmattheis** [comment]
@JustinWebDev Could you give some examples where the api documentation is not correct?

**Comment by JustinWebDev** [comment]
You didn't like the examples I gave in the previous msg?  ;-)  Actually, I have since found out that the Windows implementation of curl doesn't like the tick marks.  If I convert them to double quotes then the calls work.  Sorry about that. 

I didn't try every call or permutation, of course, but the stream call does not seem to be correct:
curl -X 'GET' \
  'http://localhost/stream' \
  -H 'accept: application/json' \
  -H 'authorization: Basic YWRtaW46YWRtaW4='
(We need a ws protocol call, correct?)

**Comment by jmattheis** [comment]
Okay, the openapi definition doesn't support web socket, so there isn't really a way to make this right. And the description of the endpoint already contains WebSocket so best we can do. 

For the other endpoints, it's most likely that you're using a wrong username/password, the UI and android app use the same api with a client generated with the api defitition.
