### ISSUE TITLE
Archive/Mark notifications as read

### ISSUE THREAD

**Issue by RichyHBM** [gotify/server#518]
**Is your feature request related to a problem? Please describe.**

Without a way to mark notifications as read there is no way to distinguish between viewed and non viewed notifications, leading me to have to delete notifications when I see them

**Describe the solution you'd like**

Some way to mark notifications as read/archived, this would require a new parameter to the /messages to indicate it should include archived messages when returning its list

**Describe alternatives you've considered**

**Additional context**

**Comment by jmattheis** [comment]
I created gotify mostly for messages with a short lifetime, so deleting is the encouraged action. Initially, this feature was tracked in #21, but it was closed because of the lack of community feedback.

**Comment by ChathuraJW** [comment]
https://github.com/gotify/server/issues/21#issuecomment-3053911960
