### ISSUE TITLE
Hello, everyone. I just know about Gotify. I can't send a notice when I request in the browser

### ISSUE THREAD

**Issue by agy2009** [gotify/server#520]
Browser request address:http://192.168.1.111:8083/message?token=<Ax2V.ufW0GYE3pT>" -F "title=my title" -F "message=my message" -F "priority=5"

The browser returns a message prompt:{"error":"Unauthorized","errorCode":401,"errorDescription":"you need to provide a valid access token or user credentials to access this api"}
Excuse me, where is the API? I have obtained Token in apps
I do not understand English. I use translation software to translate. Please forgive me if I do not understand

**Comment by jmattheis** [comment]
When you define the token inside the url, then you need to omit the symbols < and >
```
http://192.168.1.111:8083/message?token=Ax2V.ufW0GYE3pT
```

when you use the -F syntax you need to send the request via curl from a terminal or similar.
