### ISSUE TITLE
Raspberry Pi 1 (RPi1) (ARMv6) build

### ISSUE THREAD

**Issue by nkestrel** [gotify/server#522]
I'm making these RPi1 builds so I might as well share them here.

Gotify Server v2.1.6 built with go1.19.3 (bullseye).
UI built separately on PC with Ubuntu 22.10 due to Node.js lacking ARMv6 support.

[gotify-linux-arm-6_v2.1.6-c4e6386.zip](https://github.com/gotify/server/files/10002353/gotify-linux-arm-6_v2.1.6-c4e6386.zip)

**Comment by jmattheis** [comment]
I'll close this ticket as this is not really an issue with gotify.

**Comment by nkestrel** [comment]
Gotify Server v2.7.3 build for RPi1:

[gotify-linux-arm-6_v2.7.3-f77d404b.zip](https://github.com/user-attachments/files/23355356/gotify-linux-arm-6_v2.7.3-f77d404b.zip)

Building notes:
* Requires nodejs v20+, built with v22.20.0.
* Node.js lacks ARMv6 support so `yarn build` done on PC and then `ui` folder transfered to RPi (via compressed archive).
* Built with go1.25.2 on Raspberry Pi OS Lite (trixie).
* Swap file size needed to be increased to avoid build failures, the default is 427MB but the `ugorji/go/codec` package needed 680MB.

`/etc/rpi/swap.conf`:
````
[Main]
Mechanism=swapfile
[File]
FixedSizeMiB=1024
````
