### ISSUE TITLE
Port not changing when using docker

### ISSUE THREAD

**Issue by AIMBOT312** [gotify/server#523]
**Have you read the documentation?**
- [- ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [- ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
My docker command is this: `docker run -p 8008:8008 -v /var/gotify/data:/app/data gotify/server`

I have a config file at /var/gotify/data/config.yml and /etc/gotify/config.yml
Both specify   port: 8008 

Started Listening for plain HTTP connection on :80
Docker still runs on :80

**Comment by jmattheis** [comment]
https://github.com/gotify/server/issues/485
