### ISSUE TITLE
ERR_CONNECTION_REFUSED When trying to load website

### ISSUE THREAD

**Issue by AIMBOT312** [gotify/server#524]
**Have you read the documentation?**
- [- ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [-] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
My docker command:  docker run --rm -e GOTIFY_SERVER_PORT=8008 -v /var/gotify/data:/app/data gotify/server:latest
Started Listening for plain HTTP connection on :8008

When typing localip:8008 it gives the ERR_CONNECTION_REFUSED message. The firewall is disabled.

**Comment by ramberg** [comment]
You need to publish / expose the port; map it from docker / your container to a port on your host. You can read about docker networking in the following link, look for parameter p:
https://docs.docker.com/config/containers/container-networking/
