### ISSUE TITLE
redirecttohttps bug

### ISSUE THREAD

**Issue by binbooly** [gotify/server#528]
server:
  ssl:
    enabled: true
    redirecttohttps: true
    port: 8443 # the https port
    certfile: server.pem
    certkey: server.key
  cors:
    alloworigins:
      - ".*"
  stream:
    allowedorigins:
     - ".*"
  port: 80

[root@localhost gotify]# curl -vv http://18.183.147.9
* About to connect() to 18.183.147.9 port 80 (#0)
*   Trying 18.183.147.9...
* Connected to 18.183.147.9 (18.183.147.9) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 18.183.147.9
> Accept: */*
> 
< HTTP/1.1 302 Found
< Content-Type: text/html; charset=utf-8
< Location: https://18.183.147.9/
< Date: Wed, 30 Nov 2022 18:49:17 GMT
< Content-Length: 44
< 
<a href="https://18.183.147.9/">Found</a>.

* Connection #0 to host 18.183.147.9 left intact

**Comment by jmattheis** [comment]
Don't create new tickets for this, there is already one https://github.com/gotify/server/issues/519
