### ISSUE TITLE
Closed network, as a push gateway server

### ISSUE THREAD

**Issue by yoshida-git-ai** [gotify/server#531]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [x] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [x] Linux native platform
- [ ] Windows native platform

**Describe your problem**
simple question
Act as a server for push notifications?
Already on linux you can make messages appear in GUI with cURL (Use SQLite3)

what i want to do
I want to know how to set up as a push gateway server
The application is Rocketchat
Works when using FCM

However, we need a way to do push notifications on closed networks.

**Comment by jmattheis** [comment]
I don't understand what you are trying to achieve.

**Comment by yoshida-git-ai** [comment]
sorry for bad english

I want to create my own push notification system.
However, a closed internal network

**Comment by jmattheis** [comment]
You need to explain it in more detail and define what you mean with push notification system and closed internal network (closed in what way).

**Comment by yoshida-git-ai** [comment]
Push notification system and closed internal network

I've been using Rocketchat for 1 year on PC
completely internal network
(rigorous like a government agency)

recently distributed MDM-managed mobile devices
I build an android app
it works

Push notification works if you set FCM server key and project id

However, if the Internet is blocked by FW, push notifications will not work

Is it possible to make push notifications work like FCM using Gotify?
Need Apprise together?

I'm researching daily but need help

**Comment by jmattheis** [comment]
Well, gotify doesn't support anything related to rocketchat natively. Gotify does work without internet access. If you self-host rocket chat, then you can probably use something like https://github.com/immanuelfodor/rocketchat-push-gateway to do this. This is a third-party project, use at your own risk.

**Comment by yoshida-git-ai** [comment]
Thank you for your kindness

i build it and try push notification
