### ISSUE TITLE
What is the maximum number of connections?

### ISSUE THREAD

**Issue by MarcoChu-NSGuard** [gotify/server#532]
Hi!

I looked for the code, but I didn't see which side the maximum number of connections is on.
So I would like to ask the maximum number of connections?

PS.My English is not very good, if you feel strange, please forgive me

Thanks

**Comment by jmattheis** [comment]
There is no defined limit, and it depends on your hardware. The code isn't optimized for lots of connections, but I'd guess gotify easily can handle more than 1000 connections.

**Comment by MarcoChu-NSGuard** [comment]
> There is no defined limit, and it depends on your hardware. The code isn't optimized for lots of connections, but I'd guess gotify easily can handle more than 1000 connections.

Okay, I got it. thanks!
