### ISSUE TITLE
[Question] Firewall configuration and android application

### ISSUE THREAD

**Issue by orzechszek** [gotify/server#536]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [X] Docker
- [ ] Linux native platform
- [ ] Windows native platform

Hi

I have a gotify configured in a docker and OPNSense on a router.
I've added a port forwarding:
![image](https://user-images.githubusercontent.com/34706669/210260568-26d58d3e-4638-453f-b960-f6bc09f4eb52.png)
and rule was automatically created on WAN interface: 
![image](https://user-images.githubusercontent.com/34706669/210260670-062fbb93-edf9-4d7e-9aba-3afcbec8b50e.png)
but I'm still getting errors in android application:

`Caused` by: java.net.SocketTimeoutException. failed to connecto to /myWanIP (port appPort) from /myWanIp (port 37344)

I've noticed that port 37344 is generated - sometimes is different.
I'm having problem with connectivity - it takes few seconds, but the most irritating is pushing mesages. I have to try few times till it sends because "Oops something went wrong" appears. 
Can you provide what should be additionally configured in docker or firewall? Some additional ports has to be opened? Is there a possibility to reduce amount of generated ports? 
Thanks in advance.

**Comment by jmattheis** [comment]
Gotify only requires one or two ports, depending on if you've enabled ssl inside the gotify application.

Normally you have two different addresses in the error message
```
... failed to connect to /192.168.178.2 (port 8080) from /192.168.178.23 (port 48416) ...
````
In this case, `192.168.178.2` is the server where gotify/server is running on and `192.168.178.23` is the device connecting to gotify/server.

Are you sure that in your error message both ips are the same?

When your device connects to anything a port will be opened on the device, this is the one that changes from time to time and this is normal.

I don't know OPNSense, but you probably shouldn't create such a broad rules where nearly everything uses wildcards `*` as you don't need to map every port to the gotify_port. This potentially could break connections, but without further debugging, I can only guess.

Does the problem persists if you are in your local network and directly connect to the server that gotify is running on? (don't use the wan ip)

**Comment by orzechszek** [comment]
I'm sorry - You're right - from IP is android phone.
I'm using WAN IP, because I need it usually outside of my local network.
Because these source ports are generated I've decided to use a wildcard.

**Comment by jmattheis** [comment]
Does the problem persists if you are in your local network and directly connect to the server that gotify is running on? (don't use the wan ip)

**Comment by orzechszek** [comment]
Locally it's working fine. As I said - it seems a problem with firewall configuration..

**Comment by jmattheis** [comment]
Okay, then it's not a problem with gotify itself. I don't have such a system to reproduce this, maybe you can find help on a OPNSense forum or subreddit.
