### ISSUE TITLE
Resize and optimize uploaded image

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/server#538]
**Is your feature request related to a problem? Please describe.**
When an image is uploaded by a user for an application, no resizing or optimization is done. This can result in a user unintentionally uploading a logo of large dimensions, e.g. 2000 x 2000 pixels. This results in a large image in file size (near 100 KB) being transported over the network, taking up unneeded bandwidth. While a smaller image of 256 x 256 pixels can be near 5 KB.

**Describe the solution you'd like**
Each time an image is uploaded, run

    convert filename.jpg -resize "256>" filename.jpg

This will downscale the largest dimension (width and or height) of the image to 256 pixels. If the largest dimension is smaller than 256 pixels, no resizing is done.

For a PNG, also run

    optipng filename.png

This will decrease the PNG file in size without loosing image quality.

**Describe alternatives you've considered**
The user should/could be responsible for this, but that cannot be assumed, hence this feature request.

Alternatively, a shell script can be added to the documentation that does this e.g. daily via cron.

**Additional context**
The size of 256 pixels is just an example, perhaps 512 or 128 is better and needs to be investigated.

Resizing should only be done if the executable convert from the ImageMagick is found on the execution path. Similarly, optimizing when the executable optipng is found. Installation instructions should document e.g.

    sudo apt-get install imagemagick optipng

Alternative resizing and optimization tools could be supported too, when instead are available on the execution path.

**Comment by jmattheis** [comment]
Gotify should stay simple, feel free to run a cron job that optimizes all images in ./image but gotify shouldn't be responsible for this.

**Comment by PanderMusubi** [comment]
Understandable. I will make a PR for the server documentation under Miscellaneous with the script I made and all needed info.
