### ISSUE TITLE
Traefik issues with websockets

### ISSUE THREAD

**Issue by RealFascinated** [gotify/server#542]
**Can the issue be reproduced with the latest available release? (y/n)**
y

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
- [x] Traefik
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Installed gotify behind traefik

**What did you expect to see?**
New messages get sent

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
The websocket connection getting closed. 

https://cdn.fascinated.cc/xyMCyova.png

**Comment by RealFascinated** [comment]
I get this error in the console:

````WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF````

**Comment by jmattheis** [comment]
Does this error appear after some time or directly after opening the UI. Show the log and config of gotify/server. Show the configuration for traefik.
