### ISSUE TITLE
Gotify Webserver wont start on Windows

### ISSUE THREAD

**Issue by Sllikson** [gotify/server#545]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.

**You are setting up gotify in**
- [ ] Windows native platform

**Describe your problem**
I wanted to set-up gotify on my Windows VM (AMD EPYC 7702P),
i can start gotify, but the localhost isnt working. This is related to my Apache Webserver.
So i wanted to change the port for the gotify server.
I cant find the config.yml or something like this...

Also i cant change to port, because i cant finde the config file

**Any errors, logs, or other information that might help us identify your problem**
I put some screenshots down here...
![powershell](https://user-images.githubusercontent.com/94402313/215415988-d5adef1b-dddb-4de1-98e5-8fd77560e639.png)
![gotify](https://user-images.githubusercontent.com/94402313/215415991-183dab2e-355f-4b24-886b-3c4513c0ff33.png)
![files](https://user-images.githubusercontent.com/94402313/215415992-4b851f81-2ddb-44eb-ad25-33beb0bf54a0.png)

**Comment by jmattheis** [comment]
https://gotify.net/docs/config

> gotify/server looks in the following paths for config files
> * ./config.yml
> * /etc/gotify/config.yml

put the config.yml besides the binary.

**Comment by Sllikson** [comment]
Ah, i need to create my config by myself. Thanks
