### ISSUE TITLE
WebUI: Cannot refresh when app has no message

### ISSUE THREAD

**Issue by Bubbu0129** [gotify/server#546]
**Can the issue be reproduced with the latest available release? (Y)**

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
When creating an app or after <Delete all>, the refresh button is not available.

**What did you expect to see?**
<Delete all> should be made inaccessible but refreshing still operational.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
![image](https://user-images.githubusercontent.com/93034081/216142499-f94a2af3-2144-4231-99ec-1d5f1907c6a9.jpeg)

**Comment by Bubbu0129** [comment]
Ok. But long-stalled web client who lost web-socket connection also need to refresh, don't they?

**Comment by jmattheis** [comment]
If the web socket connection is lost, then it will automatically reconnect.
