### ISSUE TITLE
Add text/plain content-type option for POST `/message` endpoint

### ISSUE THREAD

**Issue by scottmconway** [gotify/server#547]
**Is your feature request related to a problem? Please describe.**
I'm attempting to log content that I cannot sanitize into Gotify. My options are to call the `/message` endpoint with one of `application/json`, `application/x-www-form-urlencoded`, or `multipart/form-data` content-types. As the unsanitized input could contain control characters for any of those methods, logging the message to gotify will not be reliable.

**Describe the solution you'd like**
I'd like to be able to specify `text/plain` as the content-type, and treat the entire HTTP body as the value of `message`. This would limit the declaration of other values (title, priority, etc) unless they could be read from GET parameters. Nonetheless, it would allow for the logging of unsanitized messages.

**Describe alternatives you've considered**
Proper sanitization sadly isn't an option here... But ntfy.sh does support plain-text messaging.

**Comment by jmattheis** [comment]
Why is sanitization on your side not an option?

**Comment by scottmconway** [comment]
It relates to [this issue](https://github.com/renyuneyun/Easer/issues/467) in Easer (similar to Tasker) for Android. Essentially, Easer allows you to reference "dynamics" (such as text message content) by name in network requests and other actions, but you can't post-process them. Without changing Easer, the only foolproof way to perform sanitization that I can think of would be to proxy the request through my own "sanitization forwarder" that would accept plaintext, and forward the message to gotify in a properly escaped JSON. I'd just really rather not go with that approach, as it adds another moving part to my logging infrastructure.

**Comment by jmattheis** [comment]
Hmm, I'm not sure if I want to support this, most other tools that support sending http requests can build a proper request themselves. I don't think it's gotify's responsibility to workaround this missing functionality from Easer.
