### ISSUE TITLE
Multiple websocket message interceptors not working proplerly.

### ISSUE THREAD

**Issue by siredwin** [gotify/server#548]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [X] Docker
- [X] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I have managed to build three plugins that intercept the messages and re-route them to email, sms, and whatsapp.
Individually, they all work great.
Another feature of my service is that I should be able to change the emails, sms numbers, and whatsapp numbers dynamically. 
This feature works but it tends to use the last websocket connection which now has changed values.
I have however managed to get the service to work but my method seems too hacky.

Please advice me on how to treat the three(or more) websocket connections and have them accept dynamic information.
My plan was to have all of them constantly listening(goroutines) and only send a message if there is a valid email, sms or whatsapp number.

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

My current errors are related to websocket connections trying to use changed information that is wrong because of the changes made dynamically.

</pre></details>

**Comment by jmattheis** [comment]
The gotify plugin api doesn't provide a way to intercept messages, do you just open a new connection to the websocket? I don't understand why you need three websocket connections, because all connections will receive the same messages (if they are from the same user).

> This feature works but it tends to use the last websocket connection which now has changed values.

What does "use the last websocket connection" mean, and what are changed values?

> websocket connections and have them accept dynamic information.

Websocket connection don't accept anything, they are read only / only the server can write messages, could you clarify what this means?

**Comment by siredwin** [comment]
Yes, these are just new websocket connections that are listening to incoming messages for users.
The main service calling Gotify is the one that allows users to change phone numbers or emails on the fly.
Maybe you can explain to me how the plugins work in this case.  I thought that they all run on the main thread as one thing but it looks like they each run individually.
I thought about keeping the plugins as one but the config "yaml" would be a mess.
So far, it works, but I am trying to see if there is a better way or how you would do it.

**Comment by jmattheis** [comment]
Gotify create a plugin instance for each user separately. I'm not sure what you are trying to achieve or currently doing, show your code, otherwise I can't help you.

**Comment by siredwin** [comment]
It is ok. It is working now. I think I am realising that every plugin is separate from each other, and my initial problems were not arising from the websockets. I will close this issue for now while I keep an eye on my current setup.
