### ISSUE TITLE
How to create a service for gotify server in standalone AlmaLinux 9 VM?

### ISSUE THREAD

**Issue by arvindjkhr** [gotify/server#555]
**Have you read the documentation?**
- 

- [x] Yes, but it does not include related information regarding my question.

**You are setting up gotify in**
- [ ] Docker
- [x] Linux native platform OS Details are as follows
`NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"`
- [ ] Windows native platform

**Describe your problem**

I'm having difficulties setting up as a service as well as how do I include my config file when running that?
....
**Document following**
https://gotify.net/docs/install

**Comment by jmattheis** [comment]
What have you tried so far, and what doesn't work?

**Comment by arvindjkhr** [comment]
I did not find this in the main installation document so got panic. 
Thank you. for the swift response.
