### ISSUE TITLE
Apps and client mapping 

### ISSUE THREAD

**Issue by arvindjkhr** [gotify/server#557]
**Is your feature request related to a problem? Please describe. **
I want to send push to specific group of people who are subscribed for an app. How do I make sure only those clients get the notification who are subscribed to that specific application not all.

**Describe the solution you'd like**
create a mapping option between client and Apps. where multiple clients can be mapped in an app and then we can send the notification to app only so only those people will get the notifications who are subscribed for that

**Describe alternatives you've considered**
I have used **one signal** for this purpose for that I had to subscribe for each application I wanted push messages for. and that use to be segregated based on applications.

**Comment by jmattheis** [comment]
See https://github.com/gotify/server/issues/382
