### ISSUE TITLE
how can i transfer sqlite data to postgres?

### ISSUE THREAD

**Issue by xiaoweihong** [gotify/server#562]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
how can i transfer sqlite data to postgres?

**Comment by jmattheis** [comment]
There is currently no automatic way to do this. You could try to dump the sqlite database and adjust the schema, so it'd fit postgres.
