### ISSUE TITLE
Link to release incorrect when building git master

### ISSUE THREAD

**Issue by tessus** [gotify/server#569]
**Can the issue be reproduced with the latest available release? y**

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x] Linux machine
- [ ] Windows machine

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [ ] Nginx
- [x] Apache
- [ ] Caddy

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

Compile gotify-server from git master

**What did you expect to see?**

A correct link on the top left when you click on the gotify version:

e.g.: `https://github.com/gotify/server/tree/5cd2d54`

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

```
https://github.com/gotify/server/releases/tag/v2.2.4-7-g5cd2d54
```

Gotify uses the version that is passed during the build with `-X main.Version=whatever`, so the link that is presented will be `https://github.com/gotify/server/releases/tag/whatever`.

I am just wondering, if there is a way to get a correct link when not built from a release tarball or git tag.

Maybe an optional var that can be passed, e.g. `-X main.VersionLink='https://github.com/gotify/server/tree/5cd2d54'`

Is this something doable?

**Comment by jmattheis** [comment]
You could pass a valid version there by using
```
git describe --tags --abbrev=0
```
instead of
```
git describe --tags
```
when defining the main.Version.

**Comment by tessus** [comment]
Yep, I know, but that's not the version then, is it?

version 2.2.4 is 7 commits old. But If I show the same version for git master as for 2.2.4, the information is not correct. The link might be, but the code is not version 2.2.4.

**Comment by tessus** [comment]
Another option would be to check for a valid tag. I don't know, if you use letters in your releases, but you can check the version against `v[0-9](\.[0-9])?(\.[0-9])?` and if it's not a match, don't show a link to the tag, but just the repo.

**Comment by jmattheis** [comment]
You could create a tag in your local repo, then the regex would match, but the link would still lead to a 404. I don't think it's much of a problem if the link is broken for custom non released builds.

**Comment by tessus** [comment]
I think a link to a version that is presented to the user should be valid and should point to the correct code. But there is nothing I can do to convince you otherwise, if you don't think so.

Closing this issue...
