### ISSUE TITLE
Unable to login after fresh install (docker original image)

### ISSUE THREAD

**Issue by jfromeo** [gotify/server#571]
**Can the issue be reproduced with the latest available release? (y/n)**
Yes (2.2.4)

**Which one is the environment gotify server is running in?**
- [X] Docker (arm64)
- [ ] Linux machine
- [ ] Windows machine

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [X] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Initial login with default credentials (admin/admin). 

Tried defining another user on docker enviromental variables
- GOTIFY_DEFAULTUSER_NAME=admin
- GOTIFY_DEFAULTUSER_PASS=admin

Tried defining another user on config.yml placed on "./"
- defaultuser: 
  - name: admin
  - pass: admin

**What did you expect to see?**
Successful login in

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

Starting Gotify version 2.2.4@2023-01-10-18:33:52
Started Listening for plain HTTP connection on :80
Error #01: you need to provide a valid access token or user credentials to access this api

**Comment by jmattheis** [comment]
The user is created when gotify is started for the first time. Changing the GOTIFY_DEFAULTUSER settings afterward has no effect. You could delete the database.

**Comment by jfromeo** [comment]
> The user is created when gotify is started for the first time. Changing the GOTIFY_DEFAULTUSER settings afterward has no effect. You could delete the database.

Thank you.

Deleted the database, restarted the container and I successfully logged in.
