### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by tessus** [gotify/server#573]
This can be closed right away. Just wanted to put it out there.

**Comment by jmattheis** [comment]
Sure thing -> https://github.com/gotify/server/releases/tag/v2.2.5

**Comment by tessus** [comment]
Thank you! 🎉

**Comment by tessus** [comment]
Oh, just FYI in case you want to put it somewhere e.g. on a wiki or whatever.

I started to create RPM packages for Fedora (current version and one version prior (38, 37 at the time od this writing)):

```
dnf config-manager --add-repo https://evermeet.cx/pub/repo/fedora/evermeet.repo
dnf install gotify-server gotify-cli
```

The server package creates a `gotify` service user and a systemd service.
