### ISSUE TITLE
Browser session/cookie overriding ?

### ISSUE THREAD

**Issue by baudneo** [gotify/server#575]
**Can the issue be reproduced with the latest available release? (y/n)**
y

**Which one is the environment gotify server is running in?**
- [x ] Docker
- [ ] Linux machine
- [ ] Windows machine
```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>
```
I use CF argo tunnels to serve gotify publicly
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
I use markdown to show an image in the body of the push notification The URL has an auth token or user&pass in it to grab the image. If I am logged into the web front end of the service that serves the image and gotify web client requests the images to display. My session/cookies for my main user that is logged into the service are overwritten and replaced with the gotify session/cookies. 

**What did you expect to see?**
I dont know html js and web tech well but, I am assuming there must be a way to bind the session or cookies to the gotify web client instead of overwriting my session? Maybe I am incorrect but, I thought I would ask.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

**Extra Info**
The service I am running is zoneminder NVR so, I have to be logged into it to view my camera feeds. Gotify is used to send poush notifications when a ZM event has used ML and detected an object I want to be notified about. So, I need ZM and gotify open in browser windows.

My current fix is to open ZM in an incognito window and Gotify in my non incognito window. that way the session/cookies arent overwritten by each other. I do realize this may not be a gotify issue but my google-fu is not good enough to drill down and find a solution.

As always, thank you for your work and contribution to OSS.

**Comment by jmattheis** [comment]
The gotify web ui doesn't use cookies/sessions, so it's unlikely that this is the fault. Does the standalone image url with the user/pass or token work with a browser where you aren't logged into any service?

**Comment by jmattheis** [comment]
Looks like your ZM frontend overrides the cookie itself, nothing gotify can do about this. If you're logged into ZM and open an ZM image url, then the cookie will probably overridden by ZM. 

You could try serving ZM on two different subdomains, using one for the image embedding and one for your normal login, like this you'll get two sessions on two subdomains and they probably don't override each other. But I don't know ZM maybe this doesn't work.

**Comment by baudneo** [comment]
Sorry, I thought I closed this issue. Thanks for your input Ill try and use your advice for the workaround!
