### ISSUE TITLE
Send RSS to Gotify?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [gotify/server#587]
I  did some sniffing around but if it's possible I can't seem to find it; I have a [RSS page](https://sourceforge.net/projects/asuswrt-merlin/rss?path=/GT-AX6000/Release) that I essentially want to send me notifications when a new firmware version is released.

Is there some way to send RSS to Gotify?

**Comment by jmattheis** [comment]
No, not supportet yet. See https://github.com/gotify/contrib/issues/2
