### ISSUE TITLE
text/markdown open links in new tab for gotify web ui

### ISSUE THREAD

**Issue by gyandoo** [gotify/server#589]
**Have you read the documentation?**
- [* ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [*] Linux native platform
- [ ] Windows native platform

**Describe your problem**
trying to find a way to open links in new window , using markdown, for webui

tried [this](https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link) , [this](https://stackoverflow.com/questions/40026947/open-new-tab-on-link-markdown) and [this](https://www.eddymens.com/blog/how-to-make-a-markdown-link-open-in-another-tab) 

I understand this question is not directly related to gotify-server however was hoping anyone could share a working solution, thanks

ps:- I know I can just hold down `ctrl` while clicking, looking for a lazier solution :)

**Comment by jmattheis** [comment]
No, there is no supported way to do this because html in markdown is disabled for security reasons.

**Comment by gyandoo** [comment]
makes sense, thanks and thanks for keeping gotify simple and secure!
