### ISSUE TITLE
Browser 502 error

### ISSUE THREAD

**Issue by slopsjon** [gotify/server#593]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [X] Docker
- [X] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>
Upgrade to docker version 2.4.0 a couple of days ago and stopped working. Web and Client report 502 error the docker image appears to be running but no alerts received.
```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [X] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>
Same problem without proxy
```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [X] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Restored docker version 2.3.0, working ok.

**What did you expect to see?**

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

**Comment by slopsjon** [comment]
`runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc000041fc8 sp=0xc000041fa0 pc=0x6f2339
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:201 +0x25 fp=0xc000041fe0 sp=0xc000041fc8 pc=0x6e95c5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x73b141
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:201 +0xa5
goroutine 5 [finalizer wait]:
runtime.gopark(0xff3ce0?, 0x10070bb01?, 0x0?, 0x0?, 0x712c65?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000040628 sp=0xc000040608 pc=0x70aa4e
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000407e0 sp=0xc000040628 pc=0x6e86a7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x73b141
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:163 +0x3d
goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000042750 sp=0xc000042730 pc=0x70aa4e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc0000427e0 sp=0xc000042750 pc=0x6eb1a5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x73b141
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x1c
goroutine 7 [GC worker (idle)]:
runtime.gopark(0x1e476279bb62?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000042f50 sp=0xc000042f30 pc=0x70aa4e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000042fe0 sp=0xc000042f50 pc=0x6eb1a5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000042fe8 sp=0xc000042fe0 pc=0x73b141
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x1c
goroutine 18 [GC worker (idle)]:
runtime.gopark(0x1e4762869da2?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00003c750 sp=0xc00003c730 pc=0x70aa4e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc00003c7e0 sp=0xc00003c750 pc=0x6eb1a5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x73b141
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x1c
goroutine 8 [GC worker (idle)]:
runtime.gopark(0x1e476287eae1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000043750 sp=0xc000043730 pc=0x70aa4e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc0000437e0 sp=0xc000043750 pc=0x6eb1a5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000437e8 sp=0xc0000437e0 pc=0x73b141
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x1c
goroutine 9 [select]:
runtime.gopark(0xc00003cf88?, 0x2?, 0x0?, 0x0?, 0xc00003cf84?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00003ce30 sp=0xc00003ce10 pc=0x70aa4e
runtime.selectgo(0xc00003cf88, 0xc00003cf80, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc00003cf50 sp=0xc00003ce30 pc=0x71a845
database/sql.(*DB).connectionOpener(0xc000550d00, {0x1674658, 0xc0000a53b0})
	/usr/local/go/src/database/sql/sql.go:1218 +0x87 fp=0xc00003cfb8 sp=0xc00003cf50 pc=0xca3ec7
database/sql.OpenDB.func1()
	/usr/local/go/src/database/sql/sql.go:791 +0x28 fp=0xc00003cfe0 sp=0xc00003cfb8 pc=0xca21e8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00003cfe8 sp=0xc00003cfe0 pc=0x73b141
created by database/sql.OpenDB in goroutine 1
	/usr/local/go/src/database/sql/sql.go:791 +0x165
goroutine 10 [chan receive]:
runtime.gopark(0x72729e?, 0xc000034f00?, 0x8?, 0x80?, 0x1e8d3c6aed43?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00003d6b8 sp=0xc00003d698 pc=0x70aa4e
runtime.chanrecv(0xc00006c180, 0xc00003d7b8, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc00003d730 sp=0xc00003d6b8 pc=0x6d506d
runtime.chanrecv2(0x45d964b800?, 0x0?)
	/usr/local/go/src/runtime/chan.go:447 +0x12 fp=0xc00003d758 sp=0xc00003d730 pc=0x6d4c92
github.com/gotify/server/v2/router.Create.func1()
	/proj/router/router.go:36 +0x78 fp=0xc00003d7e0 sp=0xc00003d758 pc=0xda6ff8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00003d7e8 sp=0xc00003d7e0 pc=0x73b141
created by github.com/gotify/server/v2/router.Create in goroutine 1
	/proj/router/router.go:34 +0x578
goroutine 11 [chan receive]:
runtime.gopark(0xc00003dee8?, 0x6dbac5?, 0x20?, 0xc4?, 0x60?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00003de80 sp=0xc00003de60 pc=0x70aa4e
runtime.chanrecv(0xc0000ca5a0, 0xc00003df70, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc00003def8 sp=0xc00003de80 pc=0x6d506d
runtime.chanrecv1(0x0?, 0x0?)
	/usr/local/go/src/runtime/chan.go:442 +0x12 fp=0xc00003df20 sp=0xc00003def8 pc=0x6d4c72
github.com/gotify/server/v2/plugin.NewManager.func1()
	/proj/plugin/manager.go:69 +0xc9 fp=0xc00003dfe0 sp=0xc00003df20 pc=0xd863c9
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00003dfe8 sp=0xc00003dfe0 pc=0x73b141
created by github.com/gotify/server/v2/plugin.NewManager in goroutine 1
	/proj/plugin/manager.go:67 +0x265
`
Log from Portainer

**Comment by jmattheis** [comment]
you probably use plugins which are incompatible with the updated version.

**Comment by slopsjon** [comment]
Yes, I have the MQTT plugin.

**Comment by jmattheis** [comment]
Okay, the plugin must be built for 2.4.0 to be usable their.
