### ISSUE TITLE
tailscale notifications via webhooks

### ISSUE THREAD

**Issue by hs6666** [gotify/server#597]
Hi, newbie here, can anyone help with the url format for webhook notifications to gotify from tailscale please....

https://tailscale.com/kb/1213/webhooks/

if i add an application and then put following url in tailscale webhook settings... https://gtfy.xyz/message?token=xxxxxxxxxxxxxxxxx, nothing happens when I do a test push notification from tailscale

thanks

**Comment by jmattheis** [comment]
Webhooks don't have a standard format, so tailscale likely doesn't send the events in the format required by gotify. https://gotify.net/api-docs#/message/createMessage

**Comment by jmattheis** [comment]
Gotify doesn't support this, you could probably write a gotify plugin for this functionality. It's out of scope for gotify to support this natively.
