### ISSUE TITLE
the ability to turn off push notifications in server

### ISSUE THREAD

**Issue by gyandoo** [gotify/server#598]
**Is your feature request related to a problem? Please describe.**
i have nothing against unified push, i just don't need it, im happy checking for new messages like i do for email by loading webapp or opening the app, im guessing the server pushes the notification, if i have a android client or not

**Describe the solution you'd like**
a simple toggle switch to switch on or off push notifications as a sever setting, default can be on if that is the popular choice

thank you for your work

**Comment by jmattheis** [comment]
Not sure exactly why you mention unified push. Gotify works with message priorities. When you define a priority of 0, then the android client will only send a silent push notification. If you don't want any notification you can suppress them in the android notification settings.

**Comment by gyandoo** [comment]
> Not sure exactly why you mention unified push. Gotify works with message priorities. When you define a priority of 0, then the android client will only send a silent push notification. If you don't want any notification you can suppress them in the android notification settings.

thanks for clearing that for me

i misunderstood how the notifying works, thought instead of GCM (Google Cloud Messaging) the message goes through UnifiedPush, irrespective if there is an android app to receive the message or not

i like to open appwebapp to see messages and refresh to see new messages, i don't like the message going through any other service except local

i noticed the android app is always running in the background and uses alarms and reminders to check for new notifications, i have turned on battery optimization and turned off alarm and reminder so there is less battery drain and no push notifications anymore instead of turning off notifications 

i guess now the server does not push the notifications through any other service
