### ISSUE TITLE
request to add app icon left to name in webui

### ISSUE THREAD

**Issue by gyandoo** [gotify/server#599]
**Is your feature request related to a problem? Please describe.**
cosmetic change request - would be nice to see the app icon next to name of the app in web ui under all messages

**Describe the solution you'd like**
would be nice to see the app icon next to name of the app in web ui

![gotify-web](https://github.com/gotify/server/assets/113236440/64f1a529-ace7-4c7a-adef-96a1327dcc1f)

**Comment by jmattheis** [comment]
duplicate: https://github.com/gotify/server/issues/405
