### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by Mohsen6558** [gotify/server#601]
Hi
I'm windows user and noob on Go
we changed in source code but on windows CMD how we can build EXE file?

I use this code:
 go build -ldflags="-w -s -X main.Version=$(git describe --tags | cut -c 2-) -X main.BuildDate=$(date "+%F-%T") -X main.Commit=$(git rev-parse --verify HEAD) -X main.Mode=prod" -o gotify-server

but see this error:
ui\serve.go:15:12: pattern build/*: no matching files found

go version go1.21.3 windows/amd64

thanks

**Comment by jmattheis** [comment]
You need to build the UI before building the Go binary. https://gotify.net/docs/build

**Comment by Mohsen6558** [comment]
thanks for answer
on try build ui 
we see this error:
![6331a8cf-f87e-4231-9962-55b8fb578747](https://github.com/gotify/server/assets/65843645/c2d46e82-0a27-417b-a777-7186390d681f)


and after that how build for windows?
please check this image

![06a5d591-3291-4d8c-b420-38ccb65c4acb](https://github.com/gotify/server/assets/65843645/1a0d0a38-5d98-40ea-b132-99909f641b5b)

**Comment by jmattheis** [comment]
Have a look at existing tickets. https://github.com/gotify/server/issues/574

> and after that how build for windows?
> please check this image

what's the problem? Describe what you expect and what you want.

**Comment by Mohsen6558** [comment]
we have error on yarn build
and we don't know how set flags for build Windows 64x

**Comment by jmattheis** [comment]
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/set_1

Building gotify is for experienced users. You can download the built binary for windows here https://github.com/gotify/server/releases/latest
