### ISSUE TITLE
ability to have webUI and API on different ports

### ISSUE THREAD

**Issue by d03j** [gotify/server#605]
**Is your feature request related to a problem? Please describe.**
I am running a gotify container on podman and have the service running fine behind a reverse proxy. I'd like to limit access to the webUI to my lan for security, which can be done easily on the proxy but this prevents the android client from accessing the server.

**Describe the solution you'd like**
have the webUI and API listening to different ports, so we can limit one to lan / specific IPs and have the other open the the internet.

**Describe alternatives you've considered**
I can't see another way to disable access to the webUI while allowing access to the API.
I have considered feeding the server logs for webUI login attempts into crowdsec but wasn't able to find them. :)

**Additional context**

**Comment by jmattheis** [comment]
You don't get any additional security by limit access to the web ui. A potential attacker can do everything that's available in the WebUI and more through the API.

**Comment by d03j** [comment]
currently people reaching gotify's port (e.g., through a reverse proxy mapping sub1.example.com to gotify) are able to tell what service is running. if you go straight to the API (e.g., sub1.example.com/message)  you get a 401 in most cases and the health and version infos are a bit less helpful. 

on a parallel note, does the app log http errors anywhere?

**Comment by jmattheis** [comment]
You can almost be 100% sure if you only try the /message api because the error description is probably unique and no other app uses it exactly like that. If you still want to do this block the UI paths via your reverse proxy from external access or compile gotify yourself without the ui part.

This isn't something that will be natively supported because you don't really gain anything.

**Comment by d03j** [comment]
ok, thanks. I'll close it as not planned. :)
