### ISSUE TITLE
How to Setup Nginx to use with Nginx Proxy Manager

### ISSUE THREAD

**Issue by BenjaminCz0101** [gotify/server#608]
**Have you read the documentation?**
-  X Yes, but it does not include related information regarding my question.
-  X Yes, but the steps described in the documentation do not work on my machine.
-  X Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**

-  Proxmox lxc Container Ubuntu 20.4

**Describe your problem**
Hi i installed Gotify in a LXC Container with Fail2Ban on my Proxmox Home Server and it Works with Nginx Proxy Manager for a Subdomain Fine. But my Problem is when i Make a test with 
https://observatory.mozilla.org/ 
says the Server is Not Safe (Note D+) my goal is A or A+

My Question is is there anybody to have a Final Config like config.yml and Nginx config file or a Tutorial to Make Gotify Safer ?

I found only Tutorial to Create Gotify in Proxmox or Docker but not to Secure it.

Thanks for your Help!

**Comment by jmattheis** [comment]
This is unrelated to gotify. You likely want to have every service you host via nginx proxy manager to have reasonable settings. So you should find a generic tutorial for security headers for nginx. As you already linked a mozilla resource I'd recommend: https://ssl-config.mozilla.org/
