### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by gerroon** [gotify/server#61]
Hi

Can you please add some examples of how to use the rest api and all that?

thanks

**Comment by jmattheis** [comment]
@gerroon There is already an api documentation which can be found here https://gotify.github.io/api-docs/ 

But still it would be good to have some examples with wget, curl and others that can be easily copy and pasted.

**Comment by gerroon** [comment]
Yes Api is good but not all of us understands APi stuff, we just wnat to use it.


I saw this on Reddit, and it seems like people can need some help there!

https://old.reddit.com/r/selfhosted/comments/9upygi/a_restapi_for_sending_and_receiving_messages_in/

**Comment by Zippyyy** [comment]
Agree, I'm confused where to put my token.

**Comment by Leopere** [comment]
I realise this project is fairly young but it would be great to be able to send notifications via this system from the CLI will there be reasonable documentation soon?

**Comment by ocomsoft** [comment]
Hey I felt the same way.. It's taken me all day but this is what I have come up with. https://github.com/ocomsoft/vhat Please excuse the rough UI but I am no expert in Vuetify, however, I think this project shows the basics of a Javascript Chat app. I hope it helps someone else. Please feel free to do whatever you want with it.

**Comment by jmattheis** [comment]
@ocomsoft Nice! Tho Gotify isn't really architected for communication between users because they currently need to share an account.

**Comment by ocomsoft** [comment]
So I learnt!! I thought I was doing something wrong.. :) You know once you let it out there people will try and do all sorts of things with it.. Thanks for your efforts..

**Comment by jmattheis** [comment]
Done in #64

**Comment by gerroon** [comment]
It seems like some examples added, but I cant find them, any pointers?

**Comment by gerroon** [comment]
thanks, that is barebones :)
