### ISSUE TITLE
Windows Application for Gotify

### ISSUE THREAD

**Issue by cxtal** [gotify/server#612]
So many Android clients and none for poor-old Windows! We have developed an application called Winify ( https://grimore.org/windows/winify ) that is small but seems to work very well for receiving notifications on Windows. The fun part is that Winify is backward-compatible all the way to Windows 7 so if there are some other people out there stuck, either deliberately or incidentally, on Windows 7, Winify should work for them great. We have a bug tracker ( https://bugs.grimore.org/ ) and a Discord server that is read-only, for announcements and updates ( https://discord.gg/rFB9EjjcwX  ).  Of course, it's all free and we do not even have any monetization such that we are really not winning much out of this.

Sorry for the shameless advertising, but we really want to get the app out there because we use Gotify a lot for our own purposes (right now we have one server relaying IoT notifications for various projects we created, one separate server for PVRs like the *arr family of PVRs and another used to send server uptime notifications).

If you could relocate this bug / feature report to some wiki or the README or somewhere where it would be suitable (similar to mentioning the Android app), that would be great because this obviously is not a bug or feature request. Maybe even open up a separate section with 3rd party software? Spares having people search the Internet for clients if 3rd party creators can just let you know and you can add them to the list. Thanks!

**Comment by jmattheis** [comment]
You can add your tool here: https://github.com/gotify/contrib
