### ISSUE TITLE
Is there any way to automatically enable plugins after container restart?

### ISSUE THREAD

**Issue by AmamiyaHotaru** [gotify/server#616]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

contents here

</pre></details>

**Comment by jmattheis** [comment]
Could you elaborate how to reproduce this? The state should persist:
![restart.webm](https://github.com/gotify/server/assets/14895212/b3795d60-23cf-46e2-879c-ffdd4477899b)

**Comment by AmamiyaHotaru** [comment]
I have found the cause of this issue.
When the Gotify server loads the plugin, the WebSocket server is not yet started, causing an error to be thrown.
I apologize for taking up your time.
