### ISSUE TITLE
Windows server command line options

### ISSUE THREAD

**Issue by Dirk6665** [gotify/server#617]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [ ] Linux native platform
- [X ] Windows native platform

**Describe your problem**
Cannot change default port of 80.  All documentation seems to center around DOCKER installation.  Is there a Win32 documentation available?

The Windows executable seems to be very sparse.  Any assistance would be appreciated.

**Comment by jmattheis** [comment]
Have you tried creating the config.yml? https://gotify.net/docs/config
