### ISSUE TITLE
Running multiple plugin instances

### ISSUE THREAD

**Issue by mStirner** [gotify/server#618]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I have the need to run a plugin multiple times. 
Simply copying the file multiple times to ´/app/data/plugins/´ does not work and let the container crash.

I want to subscribe to  multiple mqtt topics (https://github.com/tystuyfzand/gotify-mqtt), where each topic should be his own gotify application.

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>docker logs output</summary><br><pre>

```
Starting Gotify version 2.4.0@2023-09-17-08:24:00
Loading plugin data/plugins/mqtt-linux-amd64-2.so
Loading plugin data/plugins/mqtt-linux-amd64.so
panic: error while loading plugin mqtt-linux-amd64.so: plugin.Open("data/plugins/mqtt-linux-amd64"): plugin already loaded

goroutine 1 [running]:
github.com/gotify/server/v2/router.Create(0xc00053e9e0, 0xc00049f9b0, 0xc00010ca80)
	/proj/router/router.go:59 +0x2cbb
main.main()
	/proj/app.go:51 +0x2ec
Starting Gotify version 2.4.0@2023-09-17-08:24:00
Loading plugin data/plugins/mqtt-linux-amd64-2.so
Loading plugin data/plugins/mqtt-linux-amd64.so
panic: error while loading plugin mqtt-linux-amd64.so: plugin.Open("data/plugins/mqtt-linux-amd64"): plugin already loaded

goroutine 1 [running]:
github.com/gotify/server/v2/router.Create(0xc0000a09c8, 0xc0006297d0, 0xc000002a80)
	/proj/router/router.go:59 +0x2cbb
main.main()
	/proj/app.go:51 +0x2ec
``

</pre></details>

**Comment by jmattheis** [comment]
Golang currently doesn't allow loading the same plugin twice with different names https://github.com/golang/go/issues/47298

Your required functionality could be included as a feature request in the gotify-mqtt project or you could build the plugin with a different package path yourself.
```bash
$ git clone https://github.com/tystuyfzand/gotify-mqtt.git
$ cd gotify-mqtt
$ sed -i 's|gotify-mqtt|gotify-mqtt-copy|' go.mod plugin.go
$ make GOTIFY_VERSION="v2.4.0" FILE_SUFFIX="for-gotify-v2.4.0" build-linux-amd64
```
and then move the `build/mqtt-linux-amd64for-gotify-v2.4.0.so` file into your plugin directory.

**Comment by mStirner** [comment]
Have opend a issue on the plugin, but i think this also get ignored like my other question. 
I think the only solution i have is the one you provided.

**Comment by jmattheis** [comment]
Try running `make download-tools` before the other make command.

**Comment by jmattheis** [comment]
`make download-tools` installs a go binary in `$HOME/go/bin`, you need to have this directory on your `$PATH`.
