### ISSUE TITLE
just provide the comprehensive docs about stream via websocket

### ISSUE THREAD

**Issue by ZinedineR** [gotify/server#622]
**Have you read the documentation?**
- [ v ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ v] Docker
- [ ] Linux native platform
- [ v] Windows native platform

**Describe your problem**
I'm having difficulty using gotify via websocket, even the /stream docs does not include the parameter using query or something, please provide

**Comment by jmattheis** [comment]
See authentication in https://gotify.net/api-docs and then you have to establish a proper websocket connection via a library. Here as an example using wscat
```
$ wscat -H "Authorization:Bearer Cwwu45HR7bK9L6T" -c "ws://localhost:8080/stream"
Connected (press CTRL+C to quit)
< {"id":636,"appid":10,"message":"test","title":"aa","priority":1,"date":"2024-01-16T18:40:29.541151251+01:00"}

```
