### ISSUE TITLE
[Feature Request] Ability to hide login-screen elements

### ISSUE THREAD

**Issue by OdinVex** [gotify/server#625]
**Describe the solution you'd like**
I'd like the ability to hide some web ui elements on the *login screen*, such as which version of Gotify it's using (and simply link to the GitHub repo without tag information) and the sidebar entirely. This is just for the login screen. (I'm fine with a link to the project page, of course, just the tag/version info I wish to not print (html, so not just a css 'display: none'). The sidebar appears like a placeholder on a production system with those stock placeholder 'apps'.

**Describe alternatives you've considered**
Modifying the src every time, but that does get a tiny bit tedious. Simple config options to lean the login page would be nice.

**Comment by jmattheis** [comment]
What's the problem with showing the version and the placeholder apps? Gotify is opinionated and I'll only add settings if they are needed by the general user-base. This doesn't seem like a common use-case.
