### ISSUE TITLE
Wrong token copied after application rename

### ISSUE THREAD

**Issue by disconn3ct** [gotify/server#628]
**Can the issue be reproduced with the latest available release? (y/n)**
y
**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Rename an application (app1), then click the "copy token" on the same application without leaving the page.

**What did you expect to see?**
Messages with that token are received on that application (app1).

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
The token was for a different app (app2). When opening the apps page again, the row holding app1 was now holding app2. It looks like the rename caused the tokens to be reordered without changing the visible names.

**Comment by jmattheis** [comment]
Cannot reproduce, could you give more detailed steps on how to reproduce this?
[repro.webm](https://github.com/gotify/server/assets/14895212/f57bc8e8-01a2-491e-8634-d8b48d22aa42)

**Comment by disconn3ct** [comment]
I tried a few times and could not get it to reproduce. It visually reorders them as soon as the new name is submitted and the tokens match the names.

I think there must have been something wedged that prevented the refresh. Maybe still a bug, but not a useful one :( Sorry for that.
