### ISSUE TITLE
[Request] Clear Messages After 30 Days

### ISSUE THREAD

**Issue by zero77** [gotify/server#630]
**Is your feature request related to a problem? Please describe.**
if you don't keep clearing them down the messages can fill up, especially when there are multiple users.

**Describe the solution you'd like**
It would be great if the gotify server automatically cleared the messages after a chosen number of days.

**Describe alternatives you've considered**
If there is a way to do this with SQL Lite, please let me know as I have only been able to display the messages and not filter on messages older than X days.

**Comment by jmattheis** [comment]
Duplicate: https://github.com/gotify/server/issues/376
