### ISSUE TITLE
Fresh install on CasaOS (via BigBearCasaOS)

### ISSUE THREAD

**Issue by Mattieblower** [gotify/server#634]
I've installed this on CasaOS, brand new server (Ubuntu) running CasaOS, and Gotify installed within CasaOS.

Loads up, but the default username and password don't work (admin).

I've tried searching around incase BigBearCasaOS alter the login for their repo, but can't find anything. Has anyone got any idea, or know how I can force the change.

I'm very new to this, and learning, so as dummy like help as possible would be great, thank you!

**Comment by jmattheis** [comment]
BigBearCasaOS uses `custom` as default password.

https://github.com/bigbeartechworld/big-bear-casaos/blob/692ab0102bab5aadad682ea5a7a54d5ca8df9743/Apps/gotify/docker-compose.yml#L13

**Comment by Mattieblower** [comment]
> BigBearCasaOS uses `custom` as default password.
> 
> https://github.com/bigbeartechworld/big-bear-casaos/blob/692ab0102bab5aadad682ea5a7a54d5ca8df9743/Apps/gotify/docker-compose.yml#L13

Thank you! <3
