### ISSUE TITLE
Is it Possible to Only Use a URL to Forward Messages?

### ISSUE THREAD

**Issue by AHCorn** [gotify/server#643]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [x] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I'm trying to forward SMS from my iOS device to my Android phone using the Gotify server deployed on my server in conjunction with the iOS Shortcuts feature. I've followed the official documentation but it seems that forwarding cannot be achieved by simply accessing a URL. Is there a way to accomplish this, or have I missed some steps or configurations? Any guidance or suggestions would be appreciated.

**Comment by jmattheis** [comment]
What do you mean by "Use" or "access" an URL. You can send messages via a POST request to the `/message` endpoint. See https://gotify.net/docs/pushmsg if you mean sending a message via a GET request, then no, this isn't possible.

**Comment by AHCorn** [comment]
Thank you for your explanation. I meant the latter, as you described. I apologize for any confusion my phrasing may have caused.

My question arose because I previously used a messaging forwarding tool exclusive to iOS, which adopted a similar request-forwarding approach. This led me to wonder if Gotify also supports this method, prompting my inquiry here.

Once again, thank you very much for your reply; I greatly appreciate it.
