### ISSUE TITLE
Configure app graylog to use gotify for notifcations

### ISSUE THREAD

**Issue by Compukid** [gotify/server#646]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [X ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ X] Docker

**Describe your problem**
1) I would like to let you know gotify is up in running and apps configured like Uptime Kuma and a small script with a curl command 

2) my issue / misunderstanding is setting up app called graylog. I am trying configure an HTTP  notification in graylog 
....
my config for graylog is ...
![Screenshot_20240418_104247_Chrome](https://github.com/gotify/server/assets/7535046/79cd66be-2f86-4e3e-a4c2-fb3ed1587d22)

-->

**Any errors, logs, or other information that might help us identify your problem**
When testing the notification in graylog I get a 400 and not sure why. 

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

Can you please guide me on how I could setup graylog notification? Do you know of a plug-in I could use? 

Thank you

</pre></details>

**Comment by jmattheis** [comment]
Graylog uses a different message schema than gotify. So just adding this like this because gotify expects different types.

**Comment by Compukid** [comment]
> Graylog uses a different message schema than gotify. So just adding this like this because gotify expects different types.

Is there a plug in or anything I can do to get it to work with gotify? Or should I just configure graylog with a different notification app? 🤔

**Comment by jmattheis** [comment]
There is currently no gotify plugin for greylog.

**Comment by Compukid** [comment]
> There is currently no gotify plugin for greylog.

Thank you for your quick response, I appreciate it.

**Comment by mrtnbr** [comment]
I have successfully configured Gotify as a Notification method in Graylog using the new "Custom HTTP Notification" Notification Type in Graylog 6.0 (recently released).
