### ISSUE TITLE
Filter by Message

### ISSUE THREAD

**Issue by artsmorgan** [gotify/server#647]
**Is your feature request related to a problem? Please describe.**
My issue is distributing the messages to the proper users, right now I can only stream the messages to all the connections subscribed to my web socket.

**Describe the solution you'd like**
A way to distribute the messages to specific users in my platform

**Describe alternatives you've considered**
Extend the API and model  to add a new endpoint to filter by customerId

**Comment by jmattheis** [comment]
Dupe: https://github.com/gotify/contrib/issues/5
