### ISSUE TITLE
how about a new release?

### ISSUE THREAD

**Issue by tessus** [gotify/server#655]
What is the release strategy? I am just wondering, because there are no milestones and the last commit has been a while ago.

Maybe it would make sense to create a new release....

**Comment by jmattheis** [comment]
The release strategy is: "when there is something to release, then there is a release". I recently tried to update the front end deps, but this is much more work than anticipated and not something that's fun.

**Comment by tessus** [comment]
Thanks. I think this issue can be closed then. Feel free to do so.
