### ISSUE TITLE
Creating user specific applications and clients through the api

### ISSUE THREAD

**Issue by mschipperheyn** [gotify/server#657]
**Have you read the documentation?**
- [x ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
My objective is to use Gotify in a multi tenant system where each tenant needs to has its own sandbox of a single application and client and a stream for the website with only messages for that tenant

From the discussions [here](https://github.com/gotify/server/issues/334) and [here](https://github.com/gotify/server/issues/648), I now understand that applications and client are scoped to a user. So, creating a user and then creating apps and clients with that user would be the ticket. However, I have to do all of this using the api. And I don't see an obvious way to create a user and then create an application and client as that user. 

Is there a way to do this?

**Comment by jmattheis** [comment]
Have you seen the APIs listed here? https://gotify.net/api-docs

**Comment by mschipperheyn** [comment]
I have. I can see how I can create an app, a user, a client and a message. But how do I create a user and then an app as that user just by using the API? I don't see a way to authenticate as the created user through the api? Perhaps I'm missing something. But I'm looking to do all this with zero use of the UI

**Comment by jmattheis** [comment]
Create a new user with name and pass, and then use the name and pass to create the application.
```bash
ADMIN_CREDS=admin:admin

NEW_NAME=myuser
NEW_PASS=mypass

curl -u "$ADMIN_CREDS" -F "name=$NEW_NAME" -F "pass=$NEW_PASS" 'http://localhost:8080/user'

APP_TOKEN=$(curl -u "$NEW_NAME:$NEW_PASS" -F 'name=newapp' 'http://localhost:8080/application' | jq -r '.token')

echo create app with token "$APP_TOKEN"
```
