### ISSUE TITLE
[UI] Show loading indicator when loading messages instead of "No messages"

### ISSUE THREAD

**Issue by MexHigh** [gotify/server#658]
**Is your feature request related to a problem? Please describe.**
I have around 10 applications in Gotify, all of them receiving messages regularly. When I want to check them in the UI, I usually do this app by app and not via the "All messages" tab. When switching between application tabs, there is a short amount of time, where the messages are being fetched and the messages panel is empty saying "No messages".

If I want to quickly take a look at all application tabs, sometimes I'm not waiting long enough for the messages to come in and then assume that there are none, because there was no loading indicator.

**Describe the solution you'd like**
There should be some kind of loading indicator (e.g. a spinner) when opening an application tab the first time. This should only introduce changes in the ui, not the backend code.

**Describe alternatives you've considered**
None.

**Additional context**
Not required, I think.

**Comment by jmattheis** [comment]
Sounds like a useful addition :+1:

**Comment by MexHigh** [comment]
If I find some time, I'll try to implement this next week myself and open a PR

**Comment by MexHigh** [comment]
So, after a wrongly pushed branch it should work now, feel free to review #660
