### ISSUE TITLE
Error fetching registration token

### ISSUE THREAD

**Issue by Sebeck81** [gotify/server#666]
**Have you read the documentation?**
- [ x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [x ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Hello everyone, 

After updating the iOS app and the server, I receive the following message in the app: Error fetching registration token.

Does anyone have an idea? 

Kind regards Sebastian
....
my config is ...
-->version: '3.8'

services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server          # Uncommand correct server image
    # image: gotify/server-arm7
    # image: gotify/server-arm64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - net
    ports:
      - "8680:80"
    volumes:
      - data:/app/data
    environment:
      TZ:                       'Europe/Berlin'
      GOTIFY_DEFAULTUSER_PASS:  'xxxxx'   # Change me!!!!!

  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

contents here

</pre></details>

**Comment by Reginard** [comment]
I have the same issue

**Comment by jmattheis** [comment]
This app isn't maintained by Gotify. Report issues directly in the igotify repo: https://github.com/androidseb25/iGotify-Notification-Assistent
