### ISSUE TITLE
Let other applications see other application channels

### ISSUE THREAD

**Issue by StarZNighT** [gotify/server#668]
**Is your feature request related to a problem? Please describe.**
I thought plugin like gotify-broadcast could read inside other "channel"/Application so that plugin could become a real relay to send messages to N users

**Describe the solution you'd like**
I'm not a programmer anymore and i don't really know golang so eternal flame @eternal-flame-AD wrote the possible solution

https://github.com/eternal-flame-AD/gotify-broadcast/issues/10 

This could be the flow (i thought)

Message -> Application Token -> Gotify-Broadcast reads inside "Application Token" -> Sends to user 1,2,3 via plugin policy

**Describe alternatives you've considered**

**Additional context**

**Comment by jmattheis** [comment]
Another possibility is, that the plugin exposes another message endpoint and then pushes the messages to all users from there.

This feature request duplicates the already existing feature request in https://github.com/gotify/plugin-api/issues/3
