### ISSUE TITLE
Doesn't work with Synology

### ISSUE THREAD

**Issue by rightsaidfred99** [gotify/server#669]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [x ] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [ x] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

You can follow this guide to a T to replicate the issue

https://mariushosting.com/how-to-install-gotify-on-your-synology-nas/

**What did you do?**

Unable to send message

**What did you expect to see?**

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

**Comment by jmattheis** [comment]
What error messages are you receiving?

**Comment by rightsaidfred99** [comment]
Omg, my fault I didn't create an app but a token. Massive facepalm
