### ISSUE TITLE
gotify-windows-amd64 error report

### ISSUE THREAD

**Issue by pinoren** [gotify/server#671]
on windows 7 run gotify-windows-amd64.exe has some bug

version 2.5.0

like this:

E:\gotify-windows-amd64>gotify-windows-amd64
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x2df478)
        /usr/local/go/src/runtime/sys_windows_amd64.s:75 +0x7a fp=0x2df400 sp=0x
2df3e0 pc=0xc086da
rax     0x0
rbx     0x214d158
rcx     0x21d3f08
rdx     0x20
rdi     0x7fffffde000
rsi     0x2df5f8
rbp     0x2df540
rsp     0x2df3d8
r8      0x0
r9      0x2df668
r10     0x4fa2e8
r11     0xc000004000
r12     0x2df648
r13     0x0
r14     0x214b8c0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

E:\gotify-windows-amd64>

why......?

**Comment by jmattheis** [comment]
Windows 7 has been EOL for some time and Go stopped supporting it https://github.com/golang/go/issues/64622. You could build gotify yourself with an older Go version, use the docker gotify/server image, or use an older gotify version.
