### ISSUE TITLE
Add an option to display the receive time of messages with absolute time or relative time

### ISSUE THREAD

**Issue by xtay573269555** [gotify/server#672]
**Add an option to display the receive time of messages with absolute time or relative time**
Hope to add an option to display the receive time of messages with absolute time or relative time, as its android app does.

**Describe the solution you'd like**
Sometimes i need the exact time of the message to locate the source log(maybe large) in the other application which trigger the notify.

**Comment by jmattheis** [comment]
Dupe https://github.com/gotify/server/issues/465
