### ISSUE TITLE
Gotify dies after a few hours of working fine 

### ISSUE THREAD

**Issue by zeusraman** [gotify/server#673]
**Have you read the documentation?**
- [X ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ X] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

contents here

</pre></details>

**Comment by zeusraman** [comment]
Hey All,
 I am running gotify under docker 
 I have tried without logging ( just standard gotify/server ) and with logging. My gotify server dies after a couple of hours of working fine.
 
 There is nothing in the logs , docker container just dies.
 
 Any ideas  where to check ?
 
 cheers
 
 Configuration 
 
 gotify:
    #image: gotify/server
    image:  server/gotify:logger
    container_name: gotify
    ports:
      - "8081:80"
    volumes:
      - ./data/gotifydata:/app/data
    networks:
      - net

Dockerfile
      
FROM gotify/server
ENTRYPOINT /bin/bash -c '/app/gotify-app | tee /app/data/gotify.log'

**Comment by eternal-flame-AD** [comment]
@zeusraman  Sorry you are having problems. Two things you might need to do to see the actual error:

- Log the stderr as well: `./gotify-app 1>&2 | tee gotify.log`
- Check the logs of docker-compose: [docs](https://docs.docker.com/reference/cli/docker/compose/logs/).

You should see some error with at least one of the above!

**Comment by jmattheis** [comment]
closed because of inactivity
