### ISSUE TITLE
Same apps for every user

### ISSUE THREAD

**Issue by psyciknz** [gotify/server#676]
**Have you read the documentation?**
- [x ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [x ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I logged in as admin, and change password.   And then created a few apps with tokens for messages.  Very nice.  Having come from pushover I understand this method of operation.
I'd like a new user name now, but all the same apps.  Is this possible?

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

contents here

</pre></details>

**Comment by eternal-flame-AD** [comment]
You probably can connect to the database and modify the username manually but it won't be officially supported. The recommended way is to recreate the user and apps.

**Comment by psyciknz** [comment]
Thanks, yeah did wonder about that.
