### ISSUE TITLE
GUI displays "Some Server" and "A Rasberry PI"

### ISSUE THREAD

**Issue by JPElectron** [gotify/server#679]
Can the issue be reproduced with the latest available release? - Y

Which one is the environment gotify server is running in? - Windows machine

Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy) - None

On which client do you experience problems? (Select as many as you can see) - WebUI

Webpage shows "Some Server" and "A Rasberry PI" in the left side menu and these options aren't clickable, not sure if bug or there's a way to hide this.  Also why show "All messages" until a user is actually logged in?

**Comment by jmattheis** [comment]
These are greyed out placeholder texts. They aren't necessary but I don't think they are much of a problem.
