### ISSUE TITLE
Correctly show message newlines in Web-UI

### ISSUE THREAD

**Issue by schwma** [gotify/server#68]
Currently newline characters seem to be replaced by spaces in the messages Web-UI.

Example curl:
`curl -X POST "http://localhost/message?token=<token>" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"message\": \"This\nis\na\n\ntest\",  \"priority\": 0,  \"title\": \"Test\"}"`

**Comment by jmattheis** [comment]
Fixed in https://github.com/gotify/server/commit/141193136d14d8645bd4f79e1db93ce8c6284746

**Comment by schwma** [comment]
Great, thanks!
