### ISSUE TITLE
Get Messages does not honor the "since" query filter

### ISSUE THREAD

**Issue by MillanAireson** [gotify/server#682]
**Can the issue be reproduced with the latest available release? (y/n)** YES

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [ ] Linux machine
- [ X ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)** NO
- [ ] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ X ] 3rd-party API call (Please include your code)

returns:

**What did you do?**
invoke-RestMethod -uri "http://locahost/message??limit=100&since=1725667200&token=<INSERT TOKEN>"

**What did you expect to see?**

@{size=6; **since=1725667200**; limit=100}

With ONLY the messages since that date.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

@{size=6; **since=0**; limit=100}

With all messages (max 100)

**Comment by MillanAireson** [comment]
My apologies.  Thank you for clearing that up.  Not sure how I missed that in the swagger docs.  My mind must have just been telling me it was a datetime.....

**Comment by MillanAireson** [comment]
@jmattheis shouldn't the since query return all messages with an ID greater than the specified ID?

In my mind when you say, "since" you are referring to everything that has happened after.

**Comment by jmattheis** [comment]
See https://github.com/gotify/server/issues/34#issuecomment-644077391
