### ISSUE TITLE
Gotify, Nginx Proxy Manager, and Cloudflare 

### ISSUE THREAD

**Issue by Wikid82** [gotify/server#684]
Hello,

I seem to be having an issue with the android app after setting my domain nameservers to cloudflare. Before I added cloudflare everything was working as expected. I can still connect to the server via browser however that address no longer works for the app. I'm very new to all this so I'm guessing it's a setup issue but unsure where to begin troubleshooting. 

![Screenshot_20240917_161210_Gotify](https://github.com/user-attachments/assets/5841fa9f-9c5d-415f-9be5-51ec303b404e)

Thank you.

**Comment by eternal-flame-AD** [comment]
You probably have cf DDOS protection enabled, see: https://developers.cloudflare.com/ddos-protection/managed-rulesets/http/configure-dashboard/

**Comment by Wikid82** [comment]
I figured it wasn't anything with Gotify itself. I really appreciate the direction even though it's not necessarily anything to do with your app exactly. Now I have a starting point. Thank you.
