### ISSUE TITLE
Allow updating app name and description through API/UI

### ISSUE THREAD

**Issue by schwma** [gotify/server#69]
I could not find a way to update an application's name and description through the UI or the API. Since its possible to change the application image after creating an application, I expected to be able to change other application properties as well.

**Comment by jmattheis** [comment]
I though about doing this in the start but decided not to, because normally its possible to just delete and re add the application. But yeah this would be better UX and the application token would not change.

**Comment by madding** [comment]
Add end-point for this to API @jmattheis

**Comment by geeseven** [comment]
Any chance could we also get the ability to change a client name?  I got like 6 Firefox 64.0 clients and no way to tell them apart.

**Comment by jmattheis** [comment]
@geeseven I've created an issue for this: https://github.com/gotify/server/issues/101

In this issue the frontend part for updating the application stills needs to be done.
