### ISSUE TITLE
fix --openssl-legacy-provider

### ISSUE THREAD

**Issue by icetech233** [gotify/server#694]
--openssl-legacy-provider

**Comment by najtin** [comment]
Based on the information in #693 and the proposed solution to a very similar problem on [stackoverflow](https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e) this seems to be a duplicate of #693.

**Comment by eternal-flame-AD** [comment]
I tried, it's not trivial to get around this and I think there is low practical value to practically rewrite the UI that don't fix any functionality but just to get around an well accepted workaround.

**Comment by jmattheis** [comment]
Dupe -> #574
