### ISSUE TITLE
Server minimum resources required?

### ISSUE THREAD

**Issue by eric-hansen** [gotify/server#697]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ ] Docker
- [x] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm not usually a Go person, but I'm quite interested in this project.  However, I don't know what the minimum requirements are for the server.

My end goal is to host this on a VPS using the native build (i.e.: not Docker), and would like to budget my resources appropriately.

Disk space isn't as much of a concern to me right now as RAM.

**Any errors, logs, or other information that might help us identify your problem**

N/A

**Comment by eternal-flame-AD** [comment]
It should be really small, for a personal or family server I think any $5 VPS or equivalent is more than enough.

**Comment by jmattheis** [comment]
I run it on a $1/month VPS in docker. The server probably needs ~100mb RAM and at least one cpu core to run gotify for a small userbase.
