### ISSUE TITLE
First login issue

### ISSUE THREAD

**Issue by mredodos** [gotify/server#698]
**Have you read the documentation?**
- [x] Yes, but the steps described in the documentation do not work on my machine.

**You are setting up gotify in**
- [x] Docker

**Describe your problem**
 first login: Login failed

**Any errors, logs, or other information that might help us identify your problem**

2024-10-15T14:16:54.375515220Z Error #01: you need to provide a valid access token or user credentials to access this api

**Comment by jmattheis** [comment]
Solved in chat. Same issue as this one https://github.com/gotify/android/issues/381
