### ISSUE TITLE
 Fehler beim hinzugefügen des Gerätes! Successful: false Token:

### ISSUE THREAD

**Issue by Kiter1988** [gotify/server#704]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Gotify runs in Docker
I try to connect it with Webhook from Synology DSM to get messages. 

Gotify Log

```
10:06:21.460 INFO Logger.init():26 - ♻️ - Initialize iGotify Logger

10:06:21.674 VERBOSE AppDelegate.application():56 - APNs token retrieved: 32 bytes

10:06:21.676 VERBOSE AppDelegate.application():59 - The token: C5E0C*****D62CD

10:06:21.679 INFO SecNtfy.setApnsToken():136 - C5E0C*****D62CD

10:06:23.221 INFO SecNtfy.PostDevice():166 - ♻️ - Device already added NTFY-DEVICE-ufnXHH8r0TilY8e2SYeAffcbJf3PCEJOkC9wGspoCEMTmjju1dnuc

10:06:23.228 VERBOSE Functions.sendTokenToSecNtfy():232 - registration token: NTFY-DEVICE-ufnXHH8r0TilY8e2SYeAffcbJf3PCEJOkC9wGspoCEMTmjju1dnuc

10:06:23.236 VERBOSE Functions.sendTokenToSecNtfy():242 - result: Fehler beim hinzugefügen des Gerätes! Successful: false Token: NTFY-DEVICE-ufnXHH8r0TilY8e2SYeAffcbJf3PCEJOkC9wGspoCEMTmjju1dnuc
```

**Comment by jmattheis** [comment]
The iGotify project is separate from gotify. Report issues in their repository -> https://github.com/androidseb25/iGotify-Notification-Assistent
