### ISSUE TITLE
MultiUser Support

### ISSUE THREAD

**Issue by hallerdavid** [gotify/server#705]
I would like to request the option of sending one notification to many "Users / App" in one api call.

For example http://url/token=token1;token2;token3; ... 

So we can build up a good notification system for all my family users in my smarthome. I think many persons would like that feature.

**Comment by hallerdavid** [comment]
At the moment the only way is to copy and paste the api call many times and change the token for every user. Not really easy to handle for many notifications and no "clean code" :-)

**Comment by jmattheis** [comment]
See https://github.com/gotify/server/issues/382
