### ISSUE TITLE
Accept POST messages without title

### ISSUE THREAD

**Issue by JohnnyLeone** [gotify/server#71]
I'd like to use the requests for a application without always specifying a title for it. The title should not a mandatory field and if no title got specified we should always pick the application name for it. This also reduces the minimum size of a API request.

**Comment by madding** [comment]
@jmattheis I make pull request in my fork, because I don't have permission. Please, try to check it https://github.com/gotify/server/pull/72

**Comment by jmattheis** [comment]
Done in #72
