### ISSUE TITLE
notifications are not being send when using UFW

### ISSUE THREAD

**Issue by asbeel1** [gotify/server#710]
**Have you read the documentation?**
- [* ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ *] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Notifications aren't being send when using UFW.
I have to allow port 443 in UFW and only than notifs are being send.
I tried exposing port 443 in the docker compose but this didn't work.
Does anyone know why this is the case?

**Any errors, logs, or other information that might help us identify your problem**
diun: error: rpc error: code = Unknown desc = Post "<my_url>/message?token=<my_token>": context deadline exceeded (Client.Timeout exceeded whi                                             le awaiting headers)

**Comment by eternal-flame-AD** [comment]
Docker only "registers" to the kernel that gotify is available to handle packets on that port. `ufw` sets your kernel network stack to reject all incoming packets on that port. Both must be in place for external access.

**Comment by asbeel1** [comment]
How would I go about doing so?

**Comment by asbeel1** [comment]
I see. I will work with this, thank you for your help!
