### ISSUE TITLE
FTL Cannot initialize Diun error=timeout

### ISSUE THREAD

**Issue by asbeel1** [gotify/server#711]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ *] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
When using notifs test it works and sends it to my gotify but when I use 'diun serve' it gives me 'FTL Cannot initialize Diun error=timeout'

**Any errors, logs, or other information that might help us identify your problem**

FTL Cannot initialize Diun error=timeout

**Comment by eternal-flame-AD** [comment]
Have you tried asking on Diun? This doesn't feel like a gotify issue

**Comment by asbeel1** [comment]
Sure, sorry for that. Thanks for pointing that out.
