### ISSUE TITLE
I am unable to use WebSocket links gotify in web app

### ISSUE THREAD

**Issue by hallejuyahaha** [gotify/server#730]
**Have you read the documentation?**
- [ *] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [ ] Docker
- [ *] Linux native platform
- [ *] Windows native platform

**Describe your problem**

I am unable to use WebSocket links in web pages:
![微信截图_20241111170523](https://github.com/user-attachments/assets/c88f355a-fb86-47f1-a37b-02f98a2cdca3)

My gotify webui is able to receive messages normally.
My Vue JS code looks like this:
      const token = 'Cj8ZU5BYA9ct8Qc';
      const wsUrl = `ws://172.96.194.186/stream?token=${token}`;
      this.socket = new WebSocket(wsUrl );
      
      My server config
        stream:
    pingperiodseconds: 45 # the interval in which websocket pings will be sent. Only change this value if you know what you are doing.
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed, default only same origin)
      - "159.65.50.159*"   #my web app page server ip
      - "localhost*"

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

contents here

</pre></details>

**Comment by eternal-flame-AD** [comment]
What is the URL of the page you made this screenshot with? The URL of the website before path is the origin required for authentication.

Please try look at the DevTools -> Network page and fine the WebSocket connection request. Make sure the origin header value matches the `allowedorigins`:

![image](https://github.com/user-attachments/assets/d48e85d1-9e5d-470e-9e9f-29aa2ff3fd66)

Additionally, I have heard about (not a chrome user myself so did not verify) that insecure websocket are disallowed globally in Chrome. You probably should not do them even under a LAN. There will likely be related console messages if this is the case.

**Comment by eternal-flame-AD** [comment]
The screenshot you shown shows a websocket connection to /ws (likely the auto reload function of development servers or other ws servers), can you find the one that goes to /stream?

It is hard to see what is happening just with this, it would help if you can post a minimal HTML file that reproduce the problem.

**Comment by jmattheis** [comment]
It's likely https://github.com/gotify/server/issues/372 the cors allowed origins must be configured too.
