### ISSUE TITLE
Unable to update since v2.2.4

### ISSUE THREAD

**Issue by eskiiom** [gotify/server#737]
**Can the issue be reproduced with the latest available release? (y/n)**
Yes
**Which one is the environment gotify server is running in?**
- [X] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>
I've tried all the versions available from 2.2.4 to 2.6.0, and they are all failing the same way.
The only working version is 2.2.4, when I try later versions I have the following message associated with a memory dump
```
2024-11-18T13:12:59.524150012Z runtime/cgo: pthread_create failed: Operation not permitted
2024-11-18T13:12:59.527488276Z SIGABRT: abort
2024-11-18T13:12:59.527512142Z PC=0x7fbe3ca1ae2c m=0 sigcode=18446744073709551610
```

What happens it also wipes the configuration, clients and apps are empty
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [X] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
This is not related to reverse proxy, the container fails to start
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Tried all versions available
**What did you expect to see?**
Working container
**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
error log

**Comment by eternal-flame-AD** [comment]
Can you post the log? There is nothing we can do just by knowing that you have errors.

**Comment by eskiiom** [comment]
woops sorry of course I can ! I was so sure I did it, I didn't look back :)
[_Gotify_logs.txt](https://github.com/user-attachments/files/17803374/_Gotify_logs.txt)

**Comment by jmattheis** [comment]
Post your os and `docker version`. Likely outdated docker version or you are using outdated plugins.

**Comment by eskiiom** [comment]
Hello,

OS is : TurnKey GNU/Linux 16.1 (Debian 10/Buster) running kernel 5.15.158-2-pve
Docker is : 
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 21 Feb 2021 18:18:35 +0100
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Feb 21 17:18:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false

Thanks

**Comment by eternal-flame-AD** [comment]
Can you update if you are able to? I think it is likely to solve the issue given your system is more than 3 years old. We never used any manual threading so it is likely sqlite or the go runtime not compatible with your environment.

**Comment by eskiiom** [comment]
I checked yesterday whil I was connected and there seem to be no new version available for this version of container. I had a migration of this machine on the roadmap, i'll try to do this one first.
I don't know when I can do that so I'll close this issue and open a new one if it persists once I migrated/upgraded my environment.
thanks for the help !
