### ISSUE TITLE
Command line push client for Gotify

### ISSUE THREAD

**Issue by schwma** [gotify/server#74]
I created a command line push client, written in python, for Gotify that makes creating notifications from the CLI or from scripts a little easier. My client uses default values for each notification parameter, but parameters can be overridden by supplying the respective arguments.

Check it out at: https://github.com/schwma/gotify-push
Feel free to give me feedback on what to improve or create a pull request.

Sorry, I realize that this is not an issue with the server, but this is the best place I could think of to place this.

**Comment by Leopere** [comment]
@schwma it would be pretty incredible if your CLI client didn't stop at making sending messages "easier" if it could go so far as to add End to End Encryption to some degree it'd be lovely.

**Comment by schwma** [comment]
@Leopere Theoretically, if you use the UNIX philosophy of piping data from one program to another, you can already send end-to-end encrypted notification message contents with gotify-push. For example, if you set up your devices to use gpg (or another command line encryption tool of your choice), you can do the following to send an encrypted notification:

```bash
echo "This is an encrypted message" | gpg --encrypt --sign --armor -r person@email.com | gotify-push -m -
```

To decrypt the message you would currently need to use curl (since gotify-push is only meant to be a client for sending notifications), filter out the message and pipe it back into gpg.

Obviously this is a workaround and not very user friendly. But any other E2E encryption scheme without server support for key exchanges would require a workaround similar to this one, even if built directly into the client.

**Comment by Leopere** [comment]
What do push players like GCM and FCM APNS etc... do?

**Comment by schwma** [comment]
Those services cannot be directly compared to how Gotify works since Gotify combines its messaging and notification protocols. The services you mentioned are mostly only messaging protocols on top of which E2E encryption is built. Clients then interpret the message and show the decrypted message as a notification. To send an encrypted message, several messages need to be sent. At the very least keys must be exchanged between two clients at some point and an encrypted message is transmitted. Gotify interprets each message as a notification. So if E2E encryption were to be built on top of Gotify, without changing how the API works, any connected client (such as the web UI and the Android client) would show each received message as a notification, including key requests/exchanges and messages in their encrypted state.
