### ISSUE TITLE
Unix Domain Socket - Permissions

### ISSUE THREAD

**Issue by lgranie** [gotify/server#741]
Hi,

If we start gotify server listening on a unix domain socket, the permissions are :
```
podman exec -it monitor-gotify ls -l /var/run/gotify
srwxr-xr-x 1 root root 0 Nov 21 09:49 server.sock
```
In the container image, the server is started by root.

If I want ( in a pod ), use a nginx to proxy /var/run/gotify/server.sock, then nginx ( who is not started by root in the default container image ) can not access to /var/run/gotify/server.sock

Can the socket be created with 777 permissions ( like postgres socket ) ?

**Comment by najtin** [comment]
I had the exact same issue. I wrote a small script to change the permissions of the socket after it has been created. I will share it in a few hours here.

**Comment by eternal-flame-AD** [comment]
I agree. Users can choose to wrap them in more restrictive directories if that is what they want.

**Comment by najtin** [comment]
Just in case anyone needs it for something else:

```bash
/usr/bin/bash -c "
  (inotifywait  -e create /home/gotify/socket/; chmod 660 /home/gotify/socket/gotify.sock) 
  & /usr/bin/podman run --pull=newer --rm --replace --name gotify --read-only --cap-drop all --network=none -v /home/gotify/config:/etc/gotify:ro -v /home/gotify/data:/app/data -v /home/gotify/socket:/socket docker.io/gotify/server
"
```
