### ISSUE TITLE
Ability to disable web socket and use just REST API

### ISSUE THREAD

**Issue by GitStorageOne** [gotify/server#745]
**Is your feature request related to a problem? Please describe.**
I often see WebSocket connection errors (timeout) right after sending message to the API.
The port stops responding to any requests, this fixes itself after a few minutes.
When no messages are sent to the API, the websocket problem does not occur.
The problem also occurs when I use the mobile app simultaneously with the web interface.

**Describe the solution you'd like**
Option to use only REST API, without websoket for client APPs (phone and browser).
WEB app and phone APP can get new messages just by requesting API every 5 seconds.

**Additional context**
I don't use reverse proxy for simplicity, I use port shared by the docker.  
Mobile phone is always connected to the router using VPN, so application and docker are on separate networks, 
but reachable for each other.

Few possible reasons that could cause the issue:

- Bug in the code;
- Problems on the router side (in part of maintaining websocket connections) - an unlikely reason.
- Sometimes, issue could be involved with Android OS, which force app to sleep.  

I'm getting SYSLOG from router when this issue occurs:
`Warn: get out iface failed, srcIp:[MY PHONE-IP], srcPort:52726, dstIp:[GOTIFY HOST-IP], dstPort:1080, protocol:TCP, err:no OutIface found; `  
Looks strange and I not fully understand what does it mean.

**Comment by eternal-flame-AD** [comment]
If this worked but only sometimes, It is likely your router lost connection or a hardware issue causing your network adapter to become disconnected from it. If it never worked it is likely there is somewhere in your network config there was a typo in which interface or address to use.

**Comment by GitStorageOne** [comment]
The Issue was not related to gotify.  
It was the "Intrusion Prevention System" from the Unifi router. 

Solution for Unifi and pfsense users:
In case the IPS is configured to notify **and block** suspicious network activity, check the IPS reports.
Unifi seems to be using Snort, rule [SID 1:1603](https://www.snort.org/rule-docs/1-1603) caused gotify to be unavailable for a while.  
Just suppress that rule.
