### ISSUE TITLE
Notification sound plays twice on the phone

### ISSUE THREAD

**Issue by marvinwankersteen** [gotify/server#76]
Hey,
this project is really nice, because I can host it myself! Thanks!

Is it normal, that my phone plays the notification sound twice, if I send one message via curl?
I use Android 8.1 on OnePlus5 with LineageOS.
Gotify runs in docker.

**Comment by jmattheis** [comment]
This is probably fixed in https://github.com/gotify/android/pull/16/commits/c53ad9b5fc51e6042339686e2137c74b326f612f it is shipped with android app version 2.0.2

**Comment by marvinwankersteen** [comment]
Okay nice. I use 2.0.1 from F-Droid.

**Comment by jmattheis** [comment]
Fdroid already noticed the update (https://gitlab.com/fdroid/fdroiddata/commit/94be27ff43224522ad30ab9a2f44a8772d66c229) so it will be built soon.

**Comment by jmattheis** [comment]
If the issue still occurs after the update, then open an issue on [gotify/android](https://github.com/gotify/android).

**Comment by marvinwankersteen** [comment]
It's fixed with 2.0.2 from Fdroid. Thanks!
