### ISSUE TITLE
Bind to IP address

### ISSUE THREAD

**Issue by flocke** [gotify/server#79]
I would love to have the option to bind the gotify server to an IP address (in my case 127.0.0.1).

I run it behind an nginx reverse proxy under its own subdomain. Nginx takes care of HTTPS, so I only have HTTP enabled in gotify. I would like to only allow the localhost to connect to gotify.

I could easily do this with iptables (and I probably will until this is implemented) but I think a solution in the server would be more elegant.

**Comment by gedw99** [comment]
Maybe use Caddy ? alot easier.

**Comment by flocke** [comment]
@gedw99 That won't fix this, it would just be switching the reverse proxy, gotify would still be listening on the HTTP port accessible from any IP.

**Comment by geeseven** [comment]
I took at a look at this one, as it was tagged 'good first issue'.  Although in my case it would be 'good first go issue'.

The current functionality is the gotify server listens on '::' which all IPv4 and IPv6 addresses, see [here][0] for http.  It appears that '::' is the only way for go's net listen feature to allow multiple IPs to be bound to a port.  There does not appear to be a way to allow both 127.0.0.1 and [::1], except with '::'.  

Is sacrificing dualstack or multiple IP support an acceptable trade off?  Previously, I had to deal with IPv4 only clients and IPv6 only clients and not dealing with IPv4->IPv6 or IPv6->IPv4 was preferred.  That may not be the case with this application.  


[0]: https://github.com/gotify/server/blob/44b46dac557997b025035ec47220c01a1df7443c/runner/runner.go#L45

**Comment by flocke** [comment]
@geeseven In my case that would be totally fine since I only need `127.0.0.1` as endpoint for my nginx proxy. It may even be enough to only use a unix socket so that only local clients (nginx) can connect but I'm not sure that is as easy as just binding to an IP address.

**Comment by webracer999** [comment]
I've the same issue. I would like to put gotify behind a reverse proxy (apache).
My VPS has a firewall, but despite it would be better, if I can bind gotify to ::1 or 127.0.0.1

**Comment by wiebel** [comment]
This Feature is quite essential. Dropping dual stack is a non issue, as configuration behind a reverse proxy will fix it on one stack anyway, at least in amost cases..

**Comment by pm-pm** [comment]
The reverse proxy issue is almost solved. :-) Thanks.
It would be nice to bind the Server to IP "127.0.0.1" or "localhost". I do not see the binding to another IP as necessary.
