### ISSUE TITLE
data not saving

### ISSUE THREAD

**Issue by ktpx** [gotify/server#80]
I can't get the app to create a database when running in docker.  On restart, everything is back to default

Also, how do you correctly map the volume to config? -v /etc/config:/etc/config seems to be the only possibly way (yet it still says (failed to find configuration config.yml) but it works.

docker run -p 8456:80 -v /etc/gotify:/etc/gotify  gotify/server 

In the config, it wants data/gotify.db.  However, no matter how I map it with -v , it does not save a file.

**Comment by ceptonit** [comment]
I think the volume needs to be defined in the DockerFile.
So you'd need to build the docker image yourself, which I've failed to do so far.

The gotify docker image source doesn't seem to be up-to-date, I could be wrong though.

**Comment by jmattheis** [comment]
The database and images are in the `data` folder. This is a *relative* path outgoing from the gotify executable. So, the path you need to mount is `/app/data` because the executable is placed in the `/app` folder. 
```
[root@test1 ~]# docker run -p 8456:80 -v /etc/gotify/data:/app/data gotify/server
Starting Gotify version 1.1.6@2018-05-10-12:40:59
Failed to find configuration /etc/gotify/config.yml
Failed to find configuration config.yml
Started Listening on port 80
^C
[root@test1 ~]# ls -la /etc/gotify/data
total 76
drwxr-xr-x 3 root root  4096 Nov 17 09:41 .
drwxr-xr-x 3 root root  4096 Nov 17 09:41 ..
-rw-r--r-- 1 root root 61440 Nov 17 09:41 gotify.db
drwxr-xr-x 2 root root  4096 Nov 17 09:41 images
```

**Comment by ceptonit** [comment]
@jmattheis 

Works perfect, thank you :)

**Comment by ktpx** [comment]
Thanks for the clarification, now it works correctly. 

Using docker-compose I made this file then:

  version: '2'
  services:
    gotify:
      container_name: gotify
      image: gotify/server
      volumes:
        - /data/docker/gotify/config:/etc/gotify
        - /data/docker/gotify/data:/app/data
      restart: always
      ports: 
        - "8456:80"
