### ISSUE TITLE
Reverse proxy configuration (nginx)

### ISSUE THREAD

**Issue by flocke** [gotify/server#82]
Could someone please share his working reverse proxy configuration for nginx?

I am currently running gotify under it's own subdomain using a reverse proxy with nginx,
but my client keeps reconnecting a lot. I assume there is something wrong with my timeouts,
but I don't really know which values to chose.

**Comment by fgerling** [comment]
I would be helpful if you show us your nginx config.

Did you configured the `/stream` websocket endpoint in your nginx config file? 

```
location /stream {
        proxy_pass http://127.0.0.1:8942;
        proxy_set_header   Host        $host;
        proxy_set_header   X-Real-IP   $remote_addr;
        proxy_set_header   Upgrade     $http_upgrade;
        proxy_set_header   Connection  "Upgrade";
}
```

**Comment by flocke** [comment]
I'm not home right now, but I will post my config once I am.

Right now I have the config only for `/`, which looks a lot like yours. Do I have to define `/stream` really seperately?

**Comment by jmattheis** [comment]
This is my configuration:
```
location / {
  proxy_set_header        Host $host;
  proxy_set_header        X-Real-IP $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header        X-Forwarded-Proto $scheme;
  proxy_pass http://127.0.0.1:6666/;
  proxy_buffering off;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_connect_timeout 7d;
  proxy_send_timeout 7d;
  proxy_read_timeout 7d;
}
```

**Comment by flocke** [comment]
Mine was just
```
location / {
    proxy_pass http://gotify;

    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_buffering off;
}
```
with
```
upstream gotify {
    server 127.0.0.1:8080;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
```
defined earlier.

I'm gonna try the additional headers and longer timeouts from @jmattheis and report back.

**Comment by flocke** [comment]
It seems to work out great so far. I have been running it for the last 3h and I have yet to see a disconnect. I'm gonna keep an eye on the battery consumption as well tomorrow.

**Comment by flocke** [comment]
The `7d` timeout seems to have increased the battery consumption a lot:

![](https://cloud.shadowice.org/s/2GHboy4EzMjymoX/preview)

I now switched to a timeout if `1h`, which seems reasonable to me and it has been a lot better (only about 2% in the same timeframe). I'm gonna run with it a while and see what happens. I'm gonna close this issue for now.

**Comment by L11R** [comment]
@flocke 7d is crazy timeframe. And even 1h is pretty much. Server should send pings and refresh timeout. So it should be a little bit more. According to this line:
https://github.com/gotify/server/blob/ec2c3da9d4e54c5bd12dd78430398b8ef092d99d/router/router.go#L26
We need twice timeout I guess, 400 seconds, or just 7 minutes.

**Comment by flocke** [comment]
@L11R Yeah, that seems much more reasonable. I'm gonna test it on my server and report back.

**Comment by flocke** [comment]
I went with a 7 min timeout and it seems to be working nicely. I also figured out that the high battery drain mostly occurrs when I am in an area with bad reception and Gotify has to reconnect a lot.

**Comment by doronbehar** [comment]
Hey @fgerling, I've had the same problem as @flocke with nginx and I used your configuration example from this comment: https://github.com/gotify/server/issues/82#issuecomment-439924278

But, I've had to make a small change to that - instead of `proxy_pass http://127.0.0.1:8001` I used `proxy_pass http://127.0.0.1:8001/stream` and it worked.

Additionally, speaking of perhaps there should be included in the repository an example configuration for nginx as a proxy server of gotify?
